export const ATTEST_SCOPE="Attests only that the key holder's engine produced this result from inputs with these hashes. Not a statement that input claims are true, that payment occurred, or that any economic outcome is verified.";
const enc=s=>new TextEncoder().encode(s);
export const canon=v=>v===null||typeof v!=="object"?JSON.stringify(v):Array.isArray(v)?"["+v.map(canon).join(",")+"]":"{"+Object.keys(v).sort().map(k=>JSON.stringify(k)+":"+canon(v[k])).join(",")+"}";
export async function sha256Hex(s){const d=await crypto.subtle.digest("SHA-256",enc(s));return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("")}
export const packetCore=p=>({protocol:p.protocol,inputs:p.inputs,comparison:p.comparison});
const b64=u=>btoa(String.fromCharCode(...u)),unb64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
export const generateKeyPair=()=>crypto.subtle.generateKey({name:"Ed25519"},true,["sign","verify"]);
export const exportPublicB64=async k=>b64(new Uint8Array(await crypto.subtle.exportKey("raw",k)));
export const exportPrivateB64=async k=>b64(new Uint8Array(await crypto.subtle.exportKey("pkcs8",k)));
export const importPublicB64=s=>crypto.subtle.importKey("raw",unb64(s),{name:"Ed25519"},true,["verify"]);
export const importPrivateB64=s=>crypto.subtle.importKey("pkcs8",unb64(s),{name:"Ed25519"},false,["sign"]);
export async function attest(packet,{privateKey,keyId,issuedAt,prevAttestationHash=null}){if(!packet?.packet_hash)throw new Error("PACKET_HASH_REQUIRED");const payload={packet_hash:packet.packet_hash,key_id:keyId,issued_at:issuedAt,prev_attestation_hash:prevAttestationHash,scope:ATTEST_SCOPE};const signature=b64(new Uint8Array(await crypto.subtle.sign({name:"Ed25519"},privateKey,enc(canon(payload)))));return{alg:"Ed25519",payload,signature,attestation_hash:await sha256Hex(canon({payload,signature}))}}
export async function verifyAttestation(packet,att,publicKey){const checks={};checks.packet_hash_recomputed=(await sha256Hex(canon(packetCore(packet))))===packet?.packet_hash;checks.payload_binds_packet=att?.payload?.packet_hash===packet?.packet_hash;checks.scope_unchanged=att?.payload?.scope===ATTEST_SCOPE;try{checks.signature_valid=await crypto.subtle.verify({name:"Ed25519"},publicKey,unb64(att.signature),enc(canon(att.payload)))}catch{checks.signature_valid=false}checks.attestation_hash_ok=(await sha256Hex(canon({payload:att?.payload,signature:att?.signature})))===att?.attestation_hash;return{valid:Object.values(checks).every(Boolean),checks}}
export async function verifyChain(items,publicKey,startsAfter=null){let prev=startsAfter;for(let i=0;i<items.length;i++){const v=await verifyAttestation(items[i].packet,items[i].attestation,publicKey);if(!v.valid)return{valid:false,broken_at:i,reason:"ATTESTATION_INVALID",checks:v.checks};if(items[i].attestation.payload.prev_attestation_hash!==prev)return{valid:false,broken_at:i,reason:"CHAIN_LINK_BROKEN"};prev=items[i].attestation.attestation_hash}return{valid:true,head:prev,length:items.length}}