'use strict';
const crypto=require('crypto'),fs=require('fs'),path=require('path');
const {run:runCandidateGauntlet}=require('../gauntlet/CandidateGauntlet');
const ROOT=path.join(__dirname,'..');
const SEED_FILE=path.join(ROOT,'..','public','evergreen-silo-factory.json');
const TOTAL=100000;
const BUYERS=['procurement manager','operations manager','finance manager','office manager','project manager','property manager','clinic manager','fleet manager','IT manager','facilities manager'];
const TRANSFORMS=['compare','reconcile','verify','extract','normalize','match','audit','monitor','detect','assemble'];
const VALUE_FORMS=['decision brief','exception report','normalized record','verification report','evidence pack','comparison table','risk summary','follow-up list','structured export','action queue'];
const PRICE_POINTS=[19,29,39,49,59,79,99,149,199,299];
function sha(v){return crypto.createHash('sha256').update(String(v),'utf8').digest('hex');}
function loadPainVectors(){try{const x=JSON.parse(fs.readFileSync(SEED_FILE,'utf8'));return Array.isArray(x.pain_vectors)&&x.pain_vectors.length?x.pain_vectors:[{id:'SEED-001',pain:'Resolve an operational discrepancy',primitive:'verification'}];}catch{return[{id:'SEED-001',pain:'Resolve an operational discrepancy',primitive:'verification'}];}}
const PAINS=loadPainVectors();
const SPACE=PAINS.length*BUYERS.length*TRANSFORMS.length*VALUE_FORMS.length*PRICE_POINTS.length;
function decode(index){if(index<1||index>TOTAL)throw new RangeError('offer index must be 1..100000');let n=index-1;const priceIndex=n%PRICE_POINTS.length;n=Math.floor(n/PRICE_POINTS.length);const valueIndex=n%VALUE_FORMS.length;n=Math.floor(n/VALUE_FORMS.length);const transformIndex=n%TRANSFORMS.length;n=Math.floor(n/TRANSFORMS.length);const buyerIndex=n%BUYERS.length;n=Math.floor(n/BUYERS.length);const painIndex=n%PAINS.length;return{pain:PAINS[painIndex],buyer:BUYERS[buyerIndex],transform:TRANSFORMS[transformIndex],value:VALUE_FORMS[valueIndex],price:PRICE_POINTS[priceIndex]};}
function qScore(index,d){const h=sha(JSON.stringify({index:index,decoded:d}));const raw=parseInt(h.slice(0,8),16)/0xffffffff;const urgency=/verify|reconcile|audit|detect|monitor|match/.test(d.transform)?0.12:0;const concrete=/report|table|export|brief|pack|summary|queue/.test(d.value)?0.08:0;const buyerFit=d.buyer.includes('manager')?0.06:0;return Number(Math.min(1,raw+urgency+concrete+buyerFit).toFixed(6));}
function candidateFor(index){const d=decode(index),q=qScore(index,d),slug=sha(index+'|'+d.pain.id+'|'+d.transform+'|'+d.value).slice(0,16),silo='QS-'+String(index).padStart(6,'0')+'-'+slug,offerId='QSWARM-'+String(index).padStart(6,'0');const name=d.transform[0].toUpperCase()+d.transform.slice(1)+' '+d.pain.pain;const candidate={offer_id:offerId,name:name,problem:d.pain.pain,target_buyer:d.buyer,deliverable:d.value,delivery_mechanism:'automated_digital_delivery',price:d.price,currency:'NZD',payment_adapter:'stripe',checkout_route:'/api/offer-checkout/create',approval_required:true,checkout_available:false,status:'CANDIDATE',proof_of_delivery:'durable_artifact_plus_delivery_record',verification_rules:['source_bounded','deterministic_output','delivery_record','external_payment_required_for_revenue'],provenance:{private_material:'excluded',generator:'Q-SWARM-100K-PORTFOLIO-FACTORY',seed_id:d.pain.id,q_score:q},silo:silo,kill_condition:'kill_if_q_score_below_threshold_or_gauntlet_fails',q_swarm:{score:q,threshold:0.20,verdict:q>=0.20?'PASS':'KILL',seed_space:'existing_pain_vectors_x_buyer_x_transform_x_value_x_price'},public_route:'/swarm/'+index,public_url:'https://dreamledger.org/swarm/'+index};const g=runCandidateGauntlet(candidate);const survivor=q>=0.20&&g.status==='PASS';return{index:index,survivor:survivor,candidate:candidate,q_swarm:candidate.q_swarm,gauntlet:{status:g.status,candidate_hash:g.candidate_hash},truth_status:'UNVERIFIED_CANDIDATE',economic_effect:'NONE'};}
function batch(start,count){const rows=[],end=Math.min(TOTAL,start+count-1);for(let i=start;i<=end;i++)rows.push(candidateFor(i));return rows;}
function summary(){let survivors=0;const sample=[];for(let i=1;i<=TOTAL;i++){const row=candidateFor(i);if(row.survivor){survivors++;if(sample.length<25)sample.push(row);}}return{schema:'DREAMLEDGER/Q-SWARM-100K/v1',total_candidates:TOTAL,survivors:survivors,killed:TOTAL-survivors,source_space:SPACE,q_swarm_threshold:0.20,sample:sample,truth_boundary:{verified_external_revenue_nzd:0,settled_external_payments:0,independent_external_buyers:0,verified_economic_outcomes:0}};}
module.exports={TOTAL:TOTAL,candidateFor:candidateFor,batch:batch,summary:summary};