import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
const url=Deno.env.get("SUPABASE_URL")!,key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const db=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});
const out=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{"content-type":"application/json"}});
async function authorized(req:Request){const token=req.headers.get("x-economic-activation-token")||"";if(!token)return false;const{data}=await db.from("economic_activation_auth").select("token_sha256").eq("singleton",true).maybeSingle();if(!data)return false;const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(token));const h=Array.from(new Uint8Array(d)).map(b=>b.toString(16).padStart(2,"0")).join("");return h===data.token_sha256;}
function score(text:string){const t=text.toLowerCase();const i=["paid","hire","hiring","looking for","budget","commission","help","debug","fix","freelance"].filter(x=>t.includes(x)).length;const f=["automation","workflow","api","data","scraper","integration","ai","n8n","github"].filter(x=>t.includes(x)).length;return{buyer_intent:Math.min(1,.2+i*.2),fit_score:Math.min(1,.4+f*.12),freshness_score:1,evidence_score:.9};}
async function insertSignal(signal_id:string,source:string,source_ref:string,problem_text:string,observed_at:string){const s=score(problem_text);const{data,error}=await db.from("economic_demand_signals").upsert({signal_id,source,source_ref,problem_text,observed_at,silo_id:"SILO_GENERAL",buyer_intent:s.buyer_intent,freshness_score:s.freshness_score,evidence_score:s.evidence_score,fit_score:s.fit_score,status:"UNROUTED",approval_required:true},{onConflict:"signal_id"}).select("signal_id").maybeSingle();if(error)throw error;const rr=await db.rpc("route_economic_demand",{p_signal_id:signal_id});if(rr.error)throw rr.error;return{signal_id,created:Boolean(data),routed:true};}
async function scanOpenJobs(){
 const urls=["https://openjobs.bot/api/v1/jobs?status=open&limit=100","https://openjobs.bot/api/jobs?status=open&limit=100"];
 let j:any=null; let last="";
 for(const u of urls){try{const r=await fetch(u,{headers:{"accept":"application/json","user-agent":"DreamLedger-Economic-Scanner/1.1"}});if(r.ok){j=await r.json();break;}last="HTTP "+r.status;}catch(e){last=String(e);}}
 if(!j) throw new Error("OpenJobs unavailable: "+last);
 const jobs=Array.isArray(j?.jobs)?j.jobs:Array.isArray(j)?j:[]; const signals=[]; let usdcOpen=0; let wageOpen=0; let githubCompatible=0;
 for(const job of jobs){
  const id=String(job?.id||""); const title=String(job?.title||""); const body=String(job?.description||job?.body||"");
  const currency=String(job?.currency||job?.payment_token||"").toUpperCase(); const type=String(job?.job_type||job?.type||"").toLowerCase(); const status=String(job?.status||"open").toLowerCase();
  const reward=Number(job?.reward??job?.reward_amount??job?.amount??0); const text=title+" "+body;
  const github=/github\\.com\\//i.test(text)||/\\b(issue|pull request|repo|repository|bug|fix|regression test|ci)\\b/i.test(text);
  if(currency==="USDC"&&status==="open") usdcOpen++; if(currency==="WAGE"&&status==="open") wageOpen++; if(github) githubCompatible++;\n  const escrow=Boolean(job?.escrow_verified??job?.escrow?.verified??job?.escrow??false);
  if(!id||currency!=="USDC"||type!=="paid"||status!=="open"||reward<0.50||!escrow||!github) continue;
  const signalId="OPENJOBS-USDC-"+id;
  const{data,error}=await db.from("economic_demand_signals").upsert({signal_id:signalId,source:"openjobs",source_ref:"openjobs:"+id,problem_text:text,observed_at:job?.created_at||new Date().toISOString(),silo_id:"SILO_GENERAL",buyer_intent:1,freshness_score:1,evidence_score:.95,fit_score:.9,status:"UNROUTED",approval_required:true,title,body,raw_data:{...job,metadata:{openjobs_job_id:id,github_issue_url:String(job?.github_issue_url||job?.issue_url||job?.url||""),repository:String(job?.repository||""),payment_token:"USDC",job_type:"paid",reward_usdc:reward,escrow_verified:true}}} ,{onConflict:"signal_id"}).select("signal_id").maybeSingle();
  if(error)throw error; const rr=await db.rpc("stage_openjobs_bounty",{p_signal_id:signalId}); if(rr.error)throw rr.error; signals.push({signal_id:signalId,job_id:id,reward_usdc:reward,stage:rr.data});
 }
 await db.from("dreamledger_telemetry_events").insert({event_type:"OPENJOBS_SCAN",entity_type:"openjobs_feed",classification:"OBSERVATION",source:"economic-demand-scan-v2",payload:{seen:jobs.length,open_usdc:usdcOpen,open_wage:wageOpen,github_compatible:githubCompatible,qualified:signals.length,api_urls:urls}});\n return{source:"openjobs",seen:jobs.length,open_usdc:usdcOpen,open_wage:wageOpen,github_compatible:githubCompatible,qualified:signals.length,signals};
}
async function scanN8N(){const r=await fetch("https://community.n8n.io/latest.json",{headers:{"accept":"application/json","user-agent":"DreamLedger-Economic-Scanner/1.0"}});if(!r.ok)throw new Error("n8n HTTP "+r.status);const j:any=await r.json();const topics=(j?.topic_list?.topics||[]).slice(0,50);const selected=topics.filter((x:any)=>["paid","hire","help","debug","fix","freelance","looking for"].some(k=>String(x?.title||"").toLowerCase().includes(k))).slice(0,8);const signals=[];for(const t of selected)signals.push(await insertSignal("N8N-AUTO-"+String(t.id),"n8n_community","n8n_community:"+String(t.id),String(t.title||"n8n community request"),t.created_at||new Date().toISOString()));return{source:"n8n_community",seen:topics.length,selected:selected.length,signals};}
async function scanGitHub(){const qs=["automation help state:open","scraper hire state:open","api integration help state:open"];const signals=[];for(const q of qs){const r=await fetch("https://api.github.com/search/issues?q="+encodeURIComponent(q)+"&sort=updated&order=desc&per_page=8",{headers:{"accept":"application/vnd.github+json","x-github-api-version":"2026-03-10","user-agent":"DreamLedger-Economic-Scanner/1.0"}});if(!r.ok)throw new Error("GitHub HTTP "+r.status);const j:any=await r.json();for(const item of(j?.items||[])){if(item.pull_request)continue;const text=String(item.title||"")+" "+String(item.body||"");if(score(text).buyer_intent<.4)continue;signals.push(await insertSignal("GH-ISSUE-"+String(item.id),"github_public_issues",String(item.html_url||item.url),String(item.title||"GitHub issue"),item.created_at||new Date().toISOString()));}}return{source:"github_public_issues",signals};}
Deno.serve(async req=>{try{if(req.method!=="POST")return out({error:"POST_REQUIRED"},405);if(!(await authorized(req)))return out({error:"UNAUTHORIZED"},401);const results=[];try{results.push(await scanOpenJobs());}catch(e){results.push({source:"openjobs",error:String(e)});}try{results.push(await scanN8N());}catch(e){results.push({source:"n8n_community",error:String(e)});}try{results.push(await scanGitHub());}catch(e){results.push({source:"github_public_issues",error:String(e)});}return out({ok:true,scanned_at:new Date().toISOString(),results,external_action_performed:false,revenue_claimed:false});}catch(e){return out({ok:false,error:String(e),external_action_performed:false,revenue_claimed:false},500);}});
