/** Canonical deterministic supplier-quote comparison engine. Pure and non-economic. */
const SYMS: Record<string,string> = {"NZ$":"NZD","US$":"USD","A$":"AUD","C$":"CAD","€":"EUR","£":"GBP","$":"SYMBOL_$"};
const clean=(s:unknown)=>String(s??"").replace(/\r/g,"").replace(/[ \t]+/g," ").replace(/\n{3,}/g,"\n\n").trim();
const field=(t:string,ps:RegExp[])=>{for(const p of ps){const m=t.match(p);if(m)return clean(m[1]);}return null};
export function parseNumber(raw:unknown){let s=String(raw).replace(/\s/g,""),c=s.lastIndexOf(","),d=s.lastIndexOf(".");if(c>=0&&d>=0)s=c>d?s.replace(/\./g,"").replace(",","."):s.replace(/,/g,"");else if(c>=0)s=/,\d{1,2}$/.test(s)?s.replace(",","."):s.replace(/,/g,"");else if(d>=0&&/^\d{1,3}(\.\d{3})+$/.test(s))s=s.replace(/\./g,"");const n=Number(s);return Number.isFinite(n)?n:null}
const TOKEN=String.raw`(NZ\$|US\$|A\$|C\$|NZD|USD|AUD|CAD|EUR|GBP|\$|€|£)?\s*(\d[\d.,]*)\s*(NZD|USD|AUD|CAD|EUR|GBP)?`;
const TIERS=[String.raw`grand total|quote total|amount due|total payable`,String.raw`total(?:\s+(?:price|amount|cost|due))?`];
export function extractTotal(text:string){for(const tier of TIERS){const re=new RegExp(String.raw`\b(?:${tier})\s*(?:\(([^)]*)\))?\s*[:\-]?\s*${TOKEN}`,"gi");const all=[...text.matchAll(re)];if(all.length){const m=all[all.length-1],amount=parseNumber(m[2]),currency=m[1]?SYMS[m[1]]||m[1].toUpperCase():m[3]?m[3].toUpperCase():null;return {amount,currency,label_note:m[1]||null,matched_span:[m.index??0,(m.index??0)+m[0].length] as [number,number]}}}return {amount:null,currency:null,label_note:null,matched_span:null}}
export function taxBasis(text:string,note=""){const t=text+" "+note,ex=/\b(excl(?:uding|usive|\.)?|ex|plus|\+)\s*(gst|vat|tax)\b/i.test(t),inc=/\b(incl(?:uding|usive|\.)?|inc)\s*(gst|vat|tax)\b/i.test(t);return ex&&!inc?"EXCL":inc&&!ex?"INCL":ex&&inc?"BOTH_STATED":"UNSTATED"}
export function parseQuote(name:string,rawText:string){const t=clean(rawText),tot=extractTotal(t);return {file:name,extraction_status:t?"PARSED":"EMPTY",text_length:t.length,supplier:field(t,[/(?:supplier|vendor|seller|company)\s*[:\-]\s*([^\n]{2,120})/i,/^\s*([^\n]{2,100})\s+(?:quotation|quote|proposal)/im]),total:tot.amount,currency:tot.currency,tax_basis:taxBasis(t,tot.label_note||""),moq:field(t,[/(?:MOQ|min(?:imum)? order quantity|min(?:imum)? order)\s*[:\-]?\s*([^\n]{1,80})/i]),lead_time:field(t,[/(?:lead time|delivery time|turnaround)\s*[:\-]?\s*([^\n]{1,100})/i]),payment_terms:field(t,[/(?:payment terms|terms of payment)\s*[:\-]?\s*([^\n]{1,120})/i])}}
export function compareQuotes(rows:any[]){const ex:any[]=[],withTotal=rows.filter(r=>typeof r.total==="number");if(rows.length<2||withTotal.length<2)ex.push({type:"INSUFFICIENT_TOTALS",severity:"HIGH"});const nocur=withTotal.filter(r=>!r.currency).map(r=>r.file);if(nocur.length)ex.push({type:"CURRENCY_UNSTATED",severity:"HIGH",sources:nocur});const cur=[...new Set(withTotal.map(r=>r.currency).filter(Boolean))],explicit=cur.filter(c=>c!=="SYMBOL_$"),dollarish=(c:string)=>["NZD","USD","AUD","CAD","SYMBOL_$"].includes(c);if(explicit.length>1)ex.push({type:"MIXED_CURRENCY",severity:"HIGH",values:cur});else if(cur.length>1&&cur.every(dollarish))ex.push({type:"CURRENCY_AMBIGUOUS",severity:"HIGH",values:cur});else if(cur.length===1&&cur[0]==="SYMBOL_$")ex.push({type:"CURRENCY_AMBIGUOUS",severity:"HIGH",values:cur});const tb=new Set(withTotal.map(r=>r.tax_basis));if(tb.has("EXCL")&&tb.has("INCL"))ex.push({type:"TAX_BASIS_MIXED",severity:"HIGH"});else if(tb.size>1&&tb.has("UNSTATED"))ex.push({type:"TAX_BASIS_UNSTATED",severity:"MEDIUM",sources:withTotal.filter(r=>r.tax_basis==="UNSTATED").map(r=>r.file)});const missing_fields:Record<string,string[]>={};for(const k of ["supplier","total","moq","lead_time","payment_terms"]){const m=rows.filter(r=>r[k]===null||r[k]==="").map(r=>r.file);if(m.length){missing_fields[k]=m;ex.push({type:"MISSING_FIELD",field:k,severity:"LOW",sources:m})}}const comparable=!ex.some(e=>["INSUFFICIENT_TOTALS","MIXED_CURRENCY","CURRENCY_UNSTATED","CURRENCY_AMBIGUOUS","TAX_BASIS_MIXED"].includes(e.type)),lo=comparable&&withTotal.length?withTotal.reduce((a,b)=>a.total<=b.total?a:b):null,hi=comparable&&withTotal.length?withTotal.reduce((a,b)=>a.total>=b.total?a:b):null,verdict=ex.some(e=>e.type==="INSUFFICIENT_TOTALS")?"INSUFFICIENT_EVIDENCE":ex.some(e=>e.severity==="HIGH")?"MISMATCH":ex.some(e=>e.severity==="MEDIUM")?"UNRESOLVED":"MATCH",delivery_class=verdict==="INSUFFICIENT_EVIDENCE"?"INSUFFICIENT":verdict==="MATCH"?"COMPLETE":"PARTIAL";return {quote_count:rows.length,totals_observed:withTotal.length,comparable,lowest_total:lo&&{file:lo.file,supplier:lo.supplier,total:lo.total,currency:lo.currency},highest_total:hi&&{file:hi.file,supplier:hi.supplier,total:hi.total,currency:hi.currency},total_spread:lo&&hi?Number((hi.total-lo.total).toFixed(2)):null,exceptions:ex,missing_fields,evidence_verdict:verdict,delivery_class,refund_review_required:delivery_class==="INSUFFICIENT",evidence_status:"UNVERIFIED"}}
function canon(v:any):string{return v===null||typeof v!=="object"?JSON.stringify(v):Array.isArray(v)?"["+v.map(canon).join(",")+"]":"{"+Object.keys(v).sort().map(k=>JSON.stringify(k)+":"+canon(v[k])).join(",")+"}"}
export async function sha256Hex(s:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s));return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("")}
export async function evidencePacket(inputs:{file:string;text:string}[],comparison:any,generatedAt:string){const packet={protocol:"DL-QUOTE-COMPARE-2",inputs:await Promise.all(inputs.map(async i=>({source_id:i.file,source_hash:await sha256Hex(clean(i.text))}))),comparison};return {...packet,packet_hash:await sha256Hex(canon(packet)),generated_at:generatedAt,revenue_claimed:false,external_action_performed:false}}
