'use strict';

/*
 * Kelplantis Floor 1 browser presentation layer.
 * Browser state is a projection of Supabase RPC results.
 * The browser does not author game state or progression flags.
 */
function buildRuntimeHtml(spec) {
  const game = spec.game;
  const title = spec.name || 'Kelplantis';
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>${title} | Authoritative Floor 1</title>
<style>body{margin:0;background:#08100d;color:#eef6f0;font-family:system-ui,sans-serif}main{max-width:1100px;margin:auto;padding:18px}header{display:flex;justify-content:space-between;gap:12px;align-items:center;flex-wrap:wrap}.pill{padding:5px 9px;border:1px solid #355545;border-radius:999px;font-size:12px}.grid{display:grid;grid-template-columns:2fr 1fr;gap:14px}@media(max-width:800px){.grid{grid-template-columns:1fr}}section{background:#101b16;border:1px solid #30473a;border-radius:12px;padding:14px}button{padding:9px 12px;margin:3px;border:0;border-radius:7px;cursor:pointer;font-weight:700}#world{min-height:34px;color:#b9d9c3}#log{min-height:40px;color:#d4e9d9}.stat{display:inline-block;margin-right:14px}.presence{display:grid;gap:4px}.player{padding:5px 8px;background:#15241d;border-radius:6px}.small{font-size:12px;color:#a9bdb0}canvas{width:100%;height:auto;background:#0d1511;border:1px solid #30473a;border-radius:10px}</style></head><body><main>
<header><div><h1>${title}</h1><div class="small">Floor 1: The First Garden · Supabase-authoritative build</div></div><div class="pill" id="authority">AUTHORITY: CHECKING</div></header>
<div class="grid"><section><canvas id="game" width="800" height="500" aria-label="Kelplantis Floor 1"></canvas>
<div id="hud"><span class="stat">HP <b id="hp">-</b></span><span class="stat">LV <b id="lv">-</b></span><span class="stat">XP <b id="xp">-</b></span><span class="stat">Scene <b id="scene">-</b></span></div>
<div><button id="create">Create Wanderer</button><button id="sync">Sync</button><button id="warden">Talk to Garden Warden</button><button id="dungeon">Enter Dungeon</button><button id="engage">Engage</button><button id="attack">Attack</button><button id="flee">Flee</button><button id="home">Go Home</button></div><p id="log">Connecting to the authoritative game service…</p></section>
<section><h2>World</h2><div id="world">Loading world state…</div><h2>Floor Gate</h2><div id="gate">Checking Floor 2…</div><h2>Town Presence</h2><div id="presence" class="presence">Loading…</div></section></div>
<script>
const CONFIG=window.__KELPLANTIS_CONFIG__||{url:'${game.supabaseUrl || ''}',anonKey:'${game.supabaseAnonKey || ''}'};
const RPC={createPlayer:'kelplantis_create_player',getPlayer:'kelplantis_get_player',getWorldState:'kelplantis_get_world_state',getFloorGate:'kelplantis_get_floor_gate',getFloorProgress:'kelplantis_get_floor_progress',enterFloor:'kelplantis_enter_floor',movePlayer:'kelplantis_move_player',talkToNpc:'kelplantis_talk_to_npc',engageEncounter:'kelplantis_engage_encounter',attack:'kelplantis_attack',fleeEncounter:'kelplantis_flee_encounter',equipItem:'kelplantis_equip_item',listTownPresence:'kelplantis_list_town_presence'};
const c=document.getElementById('game'),ctx=c.getContext('2d');let player=null,world=null,gate=null,loading=false;const tokenKey='kelplantis_player_token';
function bridgeReady(){return CONFIG.url&&CONFIG.anonKey&&CONFIG.anonKey!=='PLACEHOLDER'&&!CONFIG.anonKey.includes('PLACEHOLDER')}
async function rpc(name,args){if(!Object.values(RPC).includes(name))throw Error('Unsupported RPC');if(!bridgeReady())throw Error('Supabase publishable key is not configured for this build.');const r=await fetch(CONFIG.url.replace(/\/$/,'')+'/rest/v1/rpc/'+name,{method:'POST',headers:{apikey:CONFIG.anonKey,Authorization:'Bearer '+CONFIG.anonKey,'Content-Type':'application/json'},body:JSON.stringify(args||{})});if(!r.ok)throw Error(await r.text());return r.json()}
function log(x){document.getElementById('log').textContent=x}function render(){if(!player)return;document.getElementById('hp').textContent=(player.hp??'-')+'/'+(player.max_hp??'-');document.getElementById('lv').textContent=player.level??'-';document.getElementById('xp').textContent=player.xp??'-';document.getElementById('scene').textContent=player.scene??'-';document.getElementById('authority').textContent=bridgeReady()?'AUTHORITY: SUPABASE':'AUTHORITY: UNCONFIGURED';draw()}
function draw(){ctx.clearRect(0,0,c.width,c.height);ctx.fillStyle='#0e1913';ctx.fillRect(0,0,c.width,c.height);const scene=player?.scene||'TOWN';if(scene==='TOWN'){ctx.fillStyle='#1b3a29';ctx.fillRect(80,80,640,340);ctx.fillStyle='#315f40';ctx.fillRect(120,120,180,100);ctx.fillRect(500,120,160,100);ctx.fillStyle='#dcefe0';ctx.font='20px system-ui';ctx.textAlign='center';ctx.fillText('FIRST GARDEN · TOWN',400,70);ctx.fillText('GARDEN WARDEN',210,175);ctx.fillText('DUNGEON GATE',580,175);ctx.fillStyle='#65d7ff';ctx.beginPath();ctx.arc(400+(player.pos_x-2)*45,280+(player.pos_y-2)*45,14,0,Math.PI*2);ctx.fill()}else if(scene==='DUNGEON'){ctx.fillStyle='#251d19';ctx.fillRect(70,70,660,360);ctx.fillStyle='#4a3026';ctx.fillRect(110,120,160,120);ctx.fillRect(320,120,160,120);ctx.fillRect(530,120,150,120);ctx.fillStyle='#f0d7a1';ctx.font='18px system-ui';ctx.fillText('FLOOR 1 DUNGEON',400,60);const e=player.current_encounter;if(e){ctx.fillStyle=e.type==='boss'?'#c74b4b':'#9b7542';ctx.beginPath();ctx.arc(400,300,28,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.fillText(e.enemy_name+' · '+e.enemy_hp+'/'+e.enemy_max_hp,400,360)}else{ctx.fillStyle='#a9c9b0';ctx.fillText('Choose Engage when the current room is uncleared.',400,320)}}else{ctx.fillStyle='#1b3a29';ctx.fillRect(100,90,600,320);ctx.fillStyle='#dcefe0';ctx.textAlign='center';ctx.font='20px system-ui';ctx.fillText(scene,400,70);ctx.fillText('Your persistent home',400,250)}}
async function sync(){if(!player){const saved=sessionStorage.getItem(tokenKey);if(saved){try{player=await rpc(RPC.getPlayer,{p_token:saved})}catch(_){sessionStorage.removeItem(tokenKey)}}}if(!player){log(bridgeReady()?'Create a wanderer to enter Kelplantis.':'Build is waiting for a Supabase publishable key.');return}player=await rpc(RPC.getPlayer,{p_token:player.player_token});world=await rpc(RPC.getWorldState,{p_world_key:'floor1'});gate=await rpc(RPC.getFloorGate,{p_token:player.player_token,p_floor_id:2});render();renderWorld();await presence()}
function renderWorld(){if(!world)return;const s=world.state||world;document.getElementById('world').textContent=(s.garden_state||'unknown')+' · '+(s.town_mood||'unknown')+' · '+(s.rumour||'');document.getElementById('gate').textContent=gate?.unlocked?(gate.playable?'Floor 2 unlocked and playable.':'Floor 2 unlocked but not yet playable.'):'Floor 2 remains locked until the authoritative Floor 1 clear.'}
async function presence(){if(!bridgeReady()||!player||player.scene!=='TOWN')return;try{const rows=await rpc(RPC.listTownPresence,{});document.getElementById('presence').innerHTML=(rows||[]).map(p=>'<div class="player">'+escapeHtml(p.name)+' · Lv '+p.level+' · '+p.pos_x+','+p.pos_y+'</div>').join('')||'No other players in town.'}catch(e){document.getElementById('presence').textContent='Presence unavailable: '+e.message}}
function escapeHtml(x){return String(x).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function act(fn,message){if(loading)return;loading=true;try{player=await fn();render();world=await rpc(RPC.getWorldState,{p_world_key:'floor1'});gate=await rpc(RPC.getFloorGate,{p_token:player.player_token,p_floor_id:2});renderWorld();await presence();log(message||'Server state updated.')}catch(e){log(e.message)}finally{loading=false}}
async function enterDungeon(){player=await rpc(RPC.enterFloor,{p_token:player.player_token,p_floor_id:1});let guard=0;while(player.scene==='TOWN'&&guard<8){const dx=player.pos_x<4?1:player.pos_x>4?-1:0;const dy=player.pos_y<4?1:player.pos_y>4?-1:0;if(dx!==0)player=await rpc(RPC.movePlayer,{p_token:player.player_token,p_dx:dx,p_dy:0});else if(dy!==0)player=await rpc(RPC.movePlayer,{p_token:player.player_token,p_dx:0,p_dy:dy});else break;guard++}if(player.scene!=='DUNGEON')throw Error('authoritative dungeon gate was not reached');return player}
document.getElementById('create').onclick=async()=>act(async()=>{const name=prompt('Wanderer name','Wanderer');const p=await rpc(RPC.createPlayer,{p_name:name||'Wanderer',p_color_hue:140});sessionStorage.setItem(tokenKey,p.player_token);return p},'Wanderer created on the authoritative server.');document.getElementById('sync').onclick=()=>sync();document.getElementById('warden').onclick=()=>act(()=>rpc(RPC.talkToNpc,{p_token:player.player_token,p_npc_key:'garden_warden'}),'The Garden Warden answered from server state.');document.getElementById('dungeon').onclick=()=>act(enterDungeon,'Entered the Floor 1 dungeon through authoritative movement.');document.getElementById('engage').onclick=()=>act(()=>rpc(RPC.engageEncounter,{p_token:player.player_token}),'Encounter engaged.');document.getElementById('attack').onclick=()=>act(()=>rpc(RPC.attack,{p_token:player.player_token}),'Attack resolved authoritatively.');document.getElementById('flee').onclick=()=>act(()=>rpc(RPC.fleeEncounter,{p_token:player.player_token}),'Fled safely to town.');document.getElementById('home').onclick=()=>act(()=>rpc(RPC.movePlayer,{p_token:player.player_token,p_dx:0,p_dy:1}),'Move intent sent to server.');
addEventListener('keydown',e=>{if(!player||loading)return;const k=e.key.toLowerCase();const v={w:[0,-1],s:[0,1],a:[-1,0],d:[1,0]}[k];if(v)act(()=>rpc(RPC.movePlayer,{p_token:player.player_token,p_dx:v[0],p_dy:v[1]}),'Movement resolved by server.')});setInterval(()=>{if(player&&player.scene==='TOWN')presence().catch(()=>{})},5000);sync().catch(e=>log(e.message));
</script></body></html>`;
}
module.exports = { buildRuntimeHtml };
