'use strict';

function buildRuntimeHtml(spec, dungeon) {
  const g = spec.game;
  const realtime = g.realtime || {};
  const data = JSON.stringify({ game: g, dungeon });
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Kelplantis Depth 1</title><style>body{margin:0;background:#081014;color:#eef6f5;font-family:system-ui,sans-serif}main{max-width:1000px;margin:auto;padding:14px}canvas{width:100%;height:auto;background:#102126;border:1px solid #40545a;border-radius:10px;touch-action:none}#bar{display:flex;gap:8px;flex-wrap:wrap;align-items:center;margin:8px 0}button,input{padding:9px 11px;border-radius:7px;border:1px solid #40545a;background:#111b20;color:#eef6f5}#log{min-height:28px}.panel{padding:10px;margin:8px 0;border:1px solid #40545a;border-radius:8px;background:#0d181d}.hidden{display:none}#inspect{position:fixed;right:14px;top:14px;width:min(320px,calc(100vw - 28px));z-index:3}.avatar{font-weight:800}</style></head><body><main><h1>Kelplantis: Depth 1</h1><p>Live in the town. Meet people. Make your place.</p><div id="bar"><input id="name" maxlength="24" placeholder="DreamMeez name"><button id="enter">Enter Depth 1</button><button id="save">Save</button><button id="reset">Reset</button><span id="online"></span><span id="transport"></span></div><div class="panel"><b>Controls:</b> WASD / arrows to walk. Click/tap another avatar to inspect. Enter sends chat. E emits an emote.</div><canvas id="game" width="960" height="600" aria-label="Kelplantis Depth 1 social town"></canvas><div class="panel"><input id="chat" maxlength="160" placeholder="Say something..."><button id="send">Chat</button><button id="emote">Emote</button><span id="log"></span></div><section id="inspect" class="panel hidden"><button id="closeInspect">Close</button><div class="avatar" id="iName"></div><div id="iTitle"></div><div id="iScars"></div><div id="iCosmetics"></div><div id="iSoul"></div></section></main><script>
const DATA=${data};
const G=DATA.game;
const c=document.getElementById('game'),ctx=c.getContext('2d'),W=c.width,H=c.height;
const SCALE=32,AV=24;
const town={w:40,h:40},fountain={x:20,y:20,r:3},board={x:20,y:3};
const token=(location.hash.slice(1)||'p-'+Math.random().toString(36).slice(2,9));
const saved=JSON.parse(localStorage.getItem('kelplantis-dreammeez-'+token)||'null');
const state={id:token,name:saved&&saved.name||'DreamMeez',x:saved&&saved.x||fountain.x,y:saved&&saved.y||fountain.y,title:saved&&saved.title||'New Arrival',scars:saved&&saved.scars||'None',cosmetics:saved&&saved.cosmetics||'Default',soul:saved&&saved.soul||'A new page in the Soul Tome.',emote:'',chat:'',lastPeerChat:'',lastPeerEmote:'',moved:false,last:performance.now()};
const peers=new Map();
const localChannel=('BroadcastChannel' in window)?new BroadcastChannel('kelplantis-depth-1'):null;
let socket=null,joinRef='1',ref=1,joined=false,heartbeat=null,transport='local';
const topic='realtime:'+((G.realtime&&G.realtime.channel)||'kelplantis-depth-1');
function log(t){document.getElementById('log').textContent=t;}
function publicState(){return {id:state.id,name:state.name,x:state.x,y:state.y,title:state.title,scars:state.scars,cosmetics:state.cosmetics,soul:state.soul,emote:state.emote,chat:state.chat};}
function persist(){localStorage.setItem('kelplantis-dreammeez-'+state.id,JSON.stringify({...state}));}
function emit(type,payload){const message={type,from:state.id,at:Date.now(),payload};if(transport==='supabase'&&socket&&joined){socket.send(JSON.stringify({event:'broadcast',topic,payload:{type:'broadcast',event:type,payload:message},ref:String(++ref),join_ref:joinRef}));}else if(localChannel){localChannel.postMessage(message);}}
function applyPresencePayload(id,payload){if(!payload||payload.id===state.id)return;peers.set(id,payload);}
function receiveMessage(m){if(!m||m.from===state.id)return;if(m.type==='presence'||m.type==='movement'||m.type==='hello'){applyPresencePayload(m.from,m.payload);if(m.type==='hello')emit('presence',publicState());return;}if(m.type==='leave'){peers.delete(m.from);return;}if(m.type==='chat'||m.type==='emote'){const p=m.payload||{};applyPresencePayload(m.from,p);if(Math.hypot(state.x-p.x,state.y-p.y)<=G.town.proximityChatRadiusAvatarWidths){if(m.type==='chat'){state.lastPeerChat=p.chat||'';log(p.name+': '+p.chat);}else{state.lastPeerEmote=p.emote||'';log(p.name+' '+p.emote);}}}}
function localStart(){transport='local';document.getElementById('transport').textContent='Transport: local';if(!localChannel)return;localChannel.onmessage=e=>receiveMessage(e.data);emit('hello',{});window.addEventListener('beforeunload',()=>emit('leave',{}));}
function realtimeSend(event,payload){if(!socket||socket.readyState!==WebSocket.OPEN)return;socket.send(JSON.stringify({event,topic,payload,ref:String(++ref),join_ref:joinRef}));}
function realtimePresenceState(p){for(const key of Object.keys(p||{})){const metas=(p[key]&&p[key].metas)||[];const meta=metas[metas.length-1];if(meta&&meta.id!==state.id)applyPresencePayload(key,meta);}}
function realtimePresenceDiff(p){for(const key of Object.keys((p&&p.leaves)||{}))peers.delete(key);for(const key of Object.keys((p&&p.joins)||{})){const metas=(p.joins[key]&&p.joins[key].metas)||[];const meta=metas[metas.length-1];if(meta)applyPresencePayload(key,meta);}}
function realtimeStart(){const rt=G.realtime||{};if(!rt.url||!rt.publishableKey||typeof WebSocket==='undefined'){localStart();return;}transport='supabase';document.getElementById('transport').textContent='Transport: Supabase Realtime';const wsUrl=rt.url.replace(/^http/,'ws')+'/realtime/v1/websocket?apikey='+encodeURIComponent(rt.publishableKey)+'&vsn=1.0.0';socket=new WebSocket(wsUrl);socket.onopen=()=>{joined=false;realtimeSend('phx_join',{config:{broadcast:{ack:true,self:false},presence:{enabled:true,key:state.id},private:false}});};socket.onmessage=e=>{let m;try{m=JSON.parse(e.data);}catch(_){return;}if(m.event==='phx_reply'&&m.payload&&m.payload.status==='ok'&&!joined){joined=true;realtimeSend('presence',{type:'presence',event:'track',payload:publicState()});return;}if(m.event==='presence_state'){realtimePresenceState(m.payload);return;}if(m.event==='presence_diff'){realtimePresenceDiff(m.payload);return;}if(m.event==='broadcast'&&m.payload){const p=m.payload.payload||m.payload;if(p.type==='broadcast'&&p.payload)receiveMessage(p.payload);else if(p.from)receiveMessage(p);return;}if(m.event==='phx_error'||m.event==='phx_close'){joined=false;log('Realtime disconnected.');}};socket.onerror=()=>{log('Realtime connection error.');};socket.onclose=()=>{joined=false;if(heartbeat)clearInterval(heartbeat);heartbeat=null;};heartbeat=setInterval(()=>{if(socket&&socket.readyState===WebSocket.OPEN)socket.send(JSON.stringify({event:'heartbeat',topic:'phoenix',payload:{},ref:String(++ref)}));},20000);window.addEventListener('beforeunload',()=>{if(socket&&socket.readyState===WebSocket.OPEN){realtimeSend('phx_leave',{});socket.close();}});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&joined)realtimeSend('presence',{type:'presence',event:'track',payload:{...publicState(),online_at:new Date().toISOString()}});});}
function refreshPresence(){if(transport==='supabase'&&joined)realtimeSend('presence',{type:'presence',event:'track',payload:{...publicState(),online_at:new Date().toISOString()}});else emit('presence',publicState());}
function spawn(){const a=Math.random()*Math.PI*2,r=2+Math.random();state.x=fountain.x+Math.cos(a)*r;state.y=fountain.y+Math.sin(a)*r;state.x=Math.max(1,Math.min(39,state.x));state.y=Math.max(1,Math.min(39,state.y));state.moved=false;persist();refreshPresence();log('Entered Depth 1 at the Fountain.');}
function screen(p){return{x:p.x*SCALE,y:p.y*SCALE};}
function draw(){ctx.clearRect(0,0,W,H);ctx.fillStyle='#102126';ctx.fillRect(0,0,W,H);ctx.fillStyle='#16332d';ctx.fillRect(0,0,W,H);ctx.fillStyle='#24483d';ctx.fillRect(14*SCALE,8*SCALE,12*SCALE,7*SCALE);ctx.fillStyle='#315d51';ctx.beginPath();ctx.arc(fountain.x*SCALE,fountain.y*SCALE,fountain.r*SCALE,0,Math.PI*2);ctx.fill();ctx.fillStyle='#e7f5ef';ctx.textAlign='center';ctx.font='bold 18px system-ui';ctx.fillText('FOUNTAIN',fountain.x*SCALE,20*SCALE+6);ctx.fillStyle='#d8c57a';ctx.fillRect(board.x*SCALE-3*SCALE,board.y*SCALE-1*SCALE,6*SCALE,2*SCALE);ctx.fillStyle='#172126';ctx.fillText('NOTICE BOARD',board.x*SCALE,board.y*SCALE+5);ctx.strokeStyle='#41645a';ctx.lineWidth=2;ctx.strokeRect(16*SCALE,3*SCALE,8*SCALE,17*SCALE);ctx.strokeRect(14*SCALE,8*SCALE,12*SCALE,7*SCALE);for(const p of peers.values())drawAvatar(p,false);drawAvatar(publicState(),true);}
function drawAvatar(p,me){const q=screen(p);ctx.fillStyle=me?'#6bd7ff':'#e4a95d';ctx.beginPath();ctx.arc(q.x,q.y,AV/2,0,Math.PI*2);ctx.fill();ctx.fillStyle='#eef6f5';ctx.font='12px system-ui';ctx.fillText(p.name||'DreamMeez',q.x,q.y-18);if(p.title){ctx.font='10px system-ui';ctx.fillText(p.title,q.x,q.y+24);}if(p.emote){ctx.font='bold 14px system-ui';ctx.fillText(p.emote,q.x,q.y-34);}if(p.chat){ctx.font='11px system-ui';ctx.fillText(p.chat.slice(0,28),q.x,q.y-48);}}
function move(dt){let dx=0,dy=0;if(keys.has('w')||keys.has('arrowup'))dy--;if(keys.has('s')||keys.has('arrowdown'))dy++;if(keys.has('a')||keys.has('arrowleft'))dx--;if(keys.has('d')||keys.has('arrowright'))dx++;const n=Math.hypot(dx,dy)||1;state.x=Math.max(1,Math.min(39,state.x+dx/n*4.2*dt));state.y=Math.max(1,Math.min(39,state.y+dy/n*4.2*dt));if(dx||dy){state.moved=true;emit('movement',publicState());}}
const keys=new Set();addEventListener('keydown',e=>{keys.add(e.key.toLowerCase());if(e.key==='Enter'&&document.activeElement!==document.getElementById('chat')){document.getElementById('chat').focus();e.preventDefault();}if(e.key.toLowerCase()==='e')sendEmote();});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
function sendChat(){const v=document.getElementById('chat').value.trim();if(!v)return;state.chat=v;emit('chat',publicState());log('You: '+v);document.getElementById('chat').value='';setTimeout(()=>{state.chat='';emit('movement',publicState());},5000);}
function sendEmote(){state.emote='*waves*';emit('emote',publicState());log('You emote.');setTimeout(()=>{state.emote='';emit('movement',publicState());},2000);}
function inspect(p){document.getElementById('iName').textContent=p.name||'DreamMeez';document.getElementById('iTitle').textContent='Title: '+(p.title||'New Arrival');document.getElementById('iScars').textContent='Scars: '+(p.scars||'None');document.getElementById('iCosmetics').textContent='Cosmetics: '+(p.cosmetics||'Default');document.getElementById('iSoul').textContent='Soul Tome: '+(p.soul||'No public summary');document.getElementById('inspect').classList.remove('hidden');}
c.addEventListener('click',e=>{const r=c.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*W/SCALE,y=(e.clientY-r.top)/r.height*H/SCALE;let best=null,bd=.9;for(const p of peers.values()){const d=Math.hypot(x-p.x,y-p.y);if(d<bd){bd=d;best=p;}}if(best)inspect(best);});
document.getElementById('enter').onclick=()=>{state.name=document.getElementById('name').value.trim()||state.name;spawn();};document.getElementById('name').value=state.name;document.getElementById('save').onclick=persist;document.getElementById('reset').onclick=()=>{localStorage.removeItem('kelplantis-dreammeez-'+state.id);location.reload();};document.getElementById('send').onclick=sendChat;document.getElementById('emote').onclick=sendEmote;document.getElementById('closeInspect').onclick=()=>document.getElementById('inspect').classList.add('hidden');
window.__KELPLANTIS_TEST__={snapshot:()=>({inDepth1:true,atFountain:Math.hypot(state.x-fountain.x,state.y-fountain.y)<=fountain.r,moved:state.moved,name:state.name,x:state.x,y:state.y,peerCount:peers.size,peers:[...peers.values()],lastPeerChat:state.lastPeerChat,lastPeerEmote:state.lastPeerEmote,transport,joined}),inspectFirstPeer:()=>{const p=[...peers.values()][0];if(!p)throw new Error('No peer available');inspect(p);},moveFar:()=>{state.x=35;state.y=35;emit('movement',publicState());},load,refreshPresence};
realtimeStart();
function frame(now){const dt=Math.min(.032,(now-state.last)/1000);state.last=now;move(dt);draw();document.getElementById('online').textContent='Players nearby: '+peers.size;requestAnimationFrame(frame);}requestAnimationFrame(frame);
</script></body></html>`;
}

module.exports={buildRuntimeHtml};
