-- Durable worker fencing, provenance quarantine, and Cortex health state.
create table if not exists public.worker_leases (
  lease_id uuid primary key default gen_random_uuid(),
  worker_id text not null,
  task_id text not null,
  acquired_at timestamptz not null default now(),
  expires_at timestamptz not null,
  fence_token bigint not null,
  released_at timestamptz
);
create unique index if not exists worker_leases_active_task_idx
  on public.worker_leases(task_id) where released_at is null;
create table if not exists public.task_fence_counters (
  task_id text primary key,
  current_fence bigint not null default 0
);
create table if not exists public.rejected_writes (
  id bigint generated by default as identity primary key,
  task_id text not null,
  presented_fence bigint not null,
  current_fence bigint not null,
  rejected_at timestamptz not null default now()
);
create table if not exists public.fossil_records (
  id uuid primary key default gen_random_uuid(),
  fossil_type text not null check (fossil_type in ('OBSERVATION','CLAIM','VERIFIED_FACT','CONTRADICTION','STALE_FACT','LEARNED_RULE')),
  entity_type text not null,
  entity_id text not null,
  payload jsonb not null,
  source text not null,
  observed_at timestamptz not null,
  confidence numeric(3,2),
  evidence_refs text[] not null default '{}',
  parent_fossil uuid references public.fossil_records(id),
  quarantine boolean not null default true,
  promoted_at timestamptz,
  promoted_by text,
  created_at timestamptz not null default now()
);
alter table public.worker_leases enable row level security;
alter table public.task_fence_counters enable row level security;
alter table public.rejected_writes enable row level security;
alter table public.fossil_records enable row level security;
create or replace function public.acquire_worker_lease(p_worker text,p_task text,p_ttl_seconds integer)
returns table(lease_id uuid,fence_token bigint) language plpgsql security invoker as $$
declare v_fence bigint;
begin
  insert into public.task_fence_counters(task_id,current_fence) values(p_task,1)
  on conflict(task_id) do update set current_fence=public.task_fence_counters.current_fence+1
  returning current_fence into v_fence;
  update public.worker_leases set released_at=now() where task_id=p_task and released_at is null;
  insert into public.worker_leases(worker_id,task_id,expires_at,fence_token)
    values(p_worker,p_task,now()+(p_ttl_seconds||' seconds')::interval,v_fence)
    returning public.worker_leases.lease_id into lease_id;
  fence_token:=v_fence;
  return next;
end $$;
create or replace function public.write_with_fence(p_task_id text,p_fence_token bigint,p_result jsonb)
returns boolean language plpgsql security invoker as $$
declare v_current bigint;
begin
  select current_fence into v_current from public.task_fence_counters where task_id=p_task_id;
  if v_current is null or p_fence_token < v_current then
    insert into public.rejected_writes(task_id,presented_fence,current_fence)
      values(p_task_id,p_fence_token,coalesce(v_current,0));
    return false;
  end if;
  return true;
end $$;
create or replace function public.promote_fossil(p_id uuid,p_by text)
returns void language plpgsql security invoker as $$
declare v_type text;
begin
  select fossil_type into v_type from public.fossil_records where id=p_id;
  if v_type not in ('VERIFIED_FACT','LEARNED_RULE') then
    raise exception 'only VERIFIED_FACT or LEARNED_RULE can be promoted';
  end if;
  update public.fossil_records set quarantine=false,promoted_at=now(),promoted_by=p_by
    where id=p_id and quarantine=true;
end $$;
create or replace view public.cortex_health as
select
 (select count(*) from public.economic_transitions where outcome='AWAITING_AUTHORIZATION') as awaiting_authorization,
 (select count(*) from public.economic_transitions where outcome='EXECUTING') as executing,
 (select count(*) from public.economic_transitions where outcome='PUBLISHED') as published,
 (select count(*) from public.economic_transitions where outcome='VERIFIED') as verified,
 (select count(*) from public.economic_transitions where outcome='FAILED') as failed,
 (select count(*) from public.worker_leases where released_at is null and expires_at>now()) as active_leases,
 (select count(*) from public.kill_switch_events where reversed_at is null) as active_kills,
 (select count(*) from public.fossil_records where quarantine=false) as promoted_fossils,
 (select count(*) from public.economic_transitions) as transition_count;