'use strict';
const fs=require('fs'); const path=require('path'); const crypto=require('crypto');
const ROOT=path.join(__dirname,'..'); const APPROVED=path.join(ROOT,'catalog','offers','approved.json'); const OUT=path.join(ROOT,'data','x402-factory');
const PRICES={entity:'0.10',claim:'0.05',receipt:'0.02'};
const sha=v=>crypto.createHash('sha256').update(v,'utf8').digest('hex');
const slug=v=>String(v).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,80);
function buildSilo(r){const b=slug(r.product_sku||r.offer_id); return Object.entries(PRICES).map(([kind,price])=>({version:'DREAMLEDGER/X402-ENDPOINT-SPEC/v1',endpoint_id:'x402-'+b+'-'+kind,silo:r.silo||'unknown',product_sku:r.product_sku,offer_id:r.offer_id,method:'POST',path:'/api/x402/'+b+'/verify/'+kind,price_usdc:price,description:'Machine verification endpoint for '+kind+' evidence.',input_schema:{type:'object',required:['subject'],properties:{subject:{type:'string',minLength:1,maxLength:4096},evidence:{type:'array',maxItems:50}}},output_schema:{type:'object',required:['endpoint_id','silo','status','receipt_id']},x402:{version:2,scheme:'exact',network:'CONFIGURE_BEFORE_LIVE',asset:'CONFIGURE_BEFORE_LIVE',payTo:'CONFIGURE_BEFORE_LIVE',facilitator:'CONFIGURE_BEFORE_LIVE',status:'SPEC_READY_NOT_LIVE'},truth:{paid_call:'UNVERIFIED until facilitator settlement receipt exists',business_truth:'FORBIDDEN until external payer, settlement, attribution, fulfillment and independent proof exist'}}));}
function run(){if(!fs.existsSync(APPROVED))throw Error('approved catalog missing'); const d=JSON.parse(fs.readFileSync(APPROVED,'utf8')); const rows=(d.approved||[]).filter(x=>x.payment_link_status==='ACTIVE_LIVEMODE'); const endpoints=rows.flatMap(buildSilo); const manifest={schema:'DREAMLEDGER/X402-MCP-MANIFEST/v1',generated_at_utc:new Date().toISOString(),status:'DISCOVERY_MANIFEST_READY_NOT_LIVE',tools:endpoints.map(e=>({name:e.endpoint_id,description:e.description,inputSchema:e.input_schema,x402:{version:2,price_usdc:e.price_usdc,network:e.x402.network,asset:e.x402.asset,payTo:e.x402.payTo},endpoint:e.path}))}; const report={schema:'DREAMLEDGER/X402-FACTORY-FACTORY/v1',generated_at_utc:new Date().toISOString(),approved_live_catalog_records:rows.length,endpoint_count:endpoints.length,pricing:PRICES,production_status:'NOT_LIVE',reason:'Payment rail configuration is intentionally fail-closed until a real receiving address, network, asset and facilitator are configured.',factory_loop:'APPROVED SILO -> ENDPOINT SPEC -> DISCOVERY MANIFEST -> PAYMENT RAIL -> EXTERNAL CALL -> SETTLEMENT -> RECEIPT -> TRUTH -> REPLICATION',endpoints_sha256:sha(JSON.stringify(endpoints)),manifest_sha256:sha(JSON.stringify(manifest))}; fs.mkdirSync(OUT,{recursive:true}); fs.writeFileSync(path.join(OUT,'endpoint-specs.json'),JSON.stringify({schema:'DREAMLEDGER/X402-ENDPOINTS/v1',endpoints},null,2)+'\n'); fs.writeFileSync(path.join(OUT,'mcp-manifest.json'),JSON.stringify(manifest,null,2)+'\n'); report.integrity_sha256=sha(JSON.stringify(report)); fs.writeFileSync(path.join(OUT,'FACTORY-FACTORY-REPORT.json'),JSON.stringify(report,null,2)+'\n'); return report;}
if(require.main===module)console.log(JSON.stringify(run(),null,2)); module.exports={run,buildSilo};
