create extension if not exists pgcrypto;
create table if not exists public.commerce_stores (id uuid primary key default gen_random_uuid(),slug text unique not null,name text not null,currency text not null default 'NZD',created_at timestamptz not null default now());
create table if not exists public.commerce_products (id uuid primary key default gen_random_uuid(),store_id uuid not null references public.commerce_stores(id),slug text not null,name text not null,description text not null default '',status text not null default 'draft',created_at timestamptz not null default now(),unique(store_id,slug));
create table if not exists public.commerce_variants (id uuid primary key default gen_random_uuid(),product_id uuid not null references public.commerce_products(id) on delete cascade,sku text,price_minor bigint not null,currency text not null default 'NZD',inventory_quantity bigint,digital boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.commerce_customers (id uuid primary key default gen_random_uuid(),store_id uuid not null references public.commerce_stores(id),email text not null,name text,created_at timestamptz not null default now(),unique(store_id,email));
create table if not exists public.commerce_orders (id uuid primary key default gen_random_uuid(),store_id uuid not null references public.commerce_stores(id),customer_id uuid references public.commerce_customers(id),status text not null default 'pending_payment',currency text not null default 'NZD',total_minor bigint not null,payment_status text not null default 'unpaid',external_payment_id text,created_at timestamptz not null default now(),paid_at timestamptz);
create table if not exists public.commerce_order_items (id uuid primary key default gen_random_uuid(),order_id uuid not null references public.commerce_orders(id) on delete cascade,variant_id uuid not null references public.commerce_variants(id),quantity bigint not null,unit_price_minor bigint not null);
create table if not exists public.commerce_fulfillments (id uuid primary key default gen_random_uuid(),order_id uuid not null references public.commerce_orders(id) on delete cascade,status text not null default 'pending',artifact_uri text,fulfilled_at timestamptz);
create table if not exists public.commerce_evidence (id uuid primary key default gen_random_uuid(),order_id uuid references public.commerce_orders(id),evidence_type text not null,external_id text,payload_hash text,source text,observed_at timestamptz not null default now());
create table if not exists public.commerce_webhook_events (id uuid primary key default gen_random_uuid(),provider text not null,external_event_id text not null,event_type text not null,received_at timestamptz not null default now(),processed_at timestamptz,unique(provider,external_event_id));
create index if not exists commerce_orders_store_created on public.commerce_orders(store_id,created_at desc);
create index if not exists commerce_evidence_order on public.commerce_evidence(order_id);
alter table public.commerce_stores enable row level security;
alter table public.commerce_products enable row level security;
alter table public.commerce_variants enable row level security;
alter table public.commerce_customers enable row level security;
alter table public.commerce_orders enable row level security;
alter table public.commerce_order_items enable row level security;
alter table public.commerce_fulfillments enable row level security;
alter table public.commerce_evidence enable row level security;
alter table public.commerce_webhook_events enable row level security;