'use strict';
const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const DATA_ROOT=process.env.BILLBOARD_DATA_DIR||'/var/data/billboard';
const PUBLIC_BASE=(process.env.PUBLIC_BASE_URL||'https://dreamledger.org').replace(/\/$/,'');
const STRIPE_SECRET_KEY=process.env.STRIPE_SECRET_KEY||'';
const ADMIN_TOKEN=process.env.MARKETPLACE_ADMIN_TOKEN||'';
const MAX_BYTES=5*1024*1024;
const CANVAS=1000;
const SIZES={small:{label:'Small',w:100,h:100,price:2900},medium:{label:'Medium',w:200,h:100,price:7900},wide:{label:'Wide',w:500,h:200,price:14900},large:{label:'Large',w:500,h:500,price:34900},takeover:{label:'Takeover',w:1000,h:1000,price:99900}};
const BAD_TEXT=/\b(?:n[i1]gg(?:er|a)|fagg(?:ot|ots)|kike|chink|spic|coon|wetback|retard(?:ed)?|kill\s+(?:all|the)|white\s+power|heil\s+hitler|gas\s+the|death\s+to)\b/i;
function mkdir(p){fs.mkdirSync(p,{recursive:true});}
function readJson(file,fallback){try{return JSON.parse(fs.readFileSync(file,'utf8'));}catch{return fallback;}}
function writeJson(file,value){mkdir(path.dirname(file));fs.writeFileSync(file,JSON.stringify(value,null,2)+'\n','utf8');}
function send(res,status,body){if(res.writableEnded)return;res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(body));}
function load(){return readJson(path.join(DATA_ROOT,'billboard.json'),{version:1,canvas:{w:CANVAS,h:CANVAS},ads:[]});}
function save(s){writeJson(path.join(DATA_ROOT,'billboard.json'),s);}
function textBlocked(v){return BAD_TEXT.test(String(v||''));}
function parseMultipart(req,raw){const ct=String(req.headers['content-type']||'');const m=ct.match(/boundary=(?:"([^"]+)"|([^;]+))/i);if(!m)throw new Error('multipart/form-data required');const boundary=Buffer.from('--'+(m[1]||m[2]));const parts=[];let start=0;while(true){const i=raw.indexOf(boundary,start);if(i<0)break;const j=i+boundary.length;if(raw.slice(j,j+2).equals(Buffer.from('--')))break;let p=j;if(raw.slice(p,p+2).equals(Buffer.from('\r\n')))p+=2;const next=raw.indexOf(boundary,p);if(next<0)break;const part=raw.slice(p,next-2);const sep=part.indexOf(Buffer.from('\r\n\r\n'));if(sep<0){start=next;continue;}const headers=part.slice(0,sep).toString('utf8');const body=part.slice(sep+4);const nm=headers.match(/name="([^"]+)"/i);const fn=headers.match(/filename="([^"]*)"/i);const typ=headers.match(/Content-Type:\s*([^\r\n]+)/i);parts.push({name:nm?nm[1]:'',filename:fn?fn[1]:'',contentType:typ?typ[1].trim():'',body});start=next;}return parts;}
function findPosition(state,w,h){for(let y=0;y<=CANVAS-h;y+=100){for(let x=0;x<=CANVAS-w;x+=100){const hit=state.ads.some(a=>a.status!=='REJECTED'&&x<a.x+a.w&&x+w>a.x&&y<a.y+a.h&&y+h>a.y);if(!hit)return{x,y};}}return null;}
function isAdmin(req){return ADMIN_TOKEN&&String(req.headers['x-marketplace-admin-token']||'')===ADMIN_TOKEN;}
async function stripe(params,key){if(!STRIPE_SECRET_KEY)throw new Error('STRIPE_SECRET_KEY is not configured');const form=new URLSearchParams();for(const[k,v]of Object.entries(params))form.set(k,String(v));const r=await fetch('https://api.stripe.com/v1/checkout/sessions',{method:'POST',headers:{Authorization:'Bearer '+STRIPE_SECRET_KEY,'Content-Type':'application/x-www-form-urlencoded','Idempotency-Key':key},body:form});const t=await r.text();let d;try{d=JSON.parse(t)}catch{d={raw:t}}if(!r.ok)throw new Error(d?.error?.message||'Stripe error '+r.status);return d;}
function handlePaidSession(session){if(session?.metadata?.product!=='DREAMLEDGER-BILLBOARD')return false;const id=session?.metadata?.ad_id;const s=load();const ad=s.ads.find(a=>a.id===id);if(!ad)return true;ad.payment_status=session.payment_status||'unknown';ad.paid_at=new Date().toISOString();ad.transaction_id=session.id;if(ad.human_review==='PASS')ad.status='PUBLISHED';else if(ad.human_review==='FAIL')ad.status='REJECTED';else ad.status='AWAITING_REVIEW';save(s);return true;}
async function handle(req,res,url){
if(req.method==='GET'&&url==='/api/billboard'){const s=load();return send(res,200,{canvas:s.canvas,ads:s.ads.filter(a=>a.status==='PUBLISHED').map(a=>({...a,image_url:'/billboard/media/'+a.id}))});}
if(req.method==='GET'&&url.startsWith('/billboard/media/')){const id=url.slice('/billboard/media/'.length);const s=load();const ad=s.ads.find(a=>a.id===id);if(!ad)return send(res,404,{error:'Not found'});const file=path.join(DATA_ROOT,'media',id+ad.ext);if(!fs.existsSync(file))return send(res,404,{error:'Media not found'});res.writeHead(200,{'Content-Type':ad.mime,'Cache-Control':'public,max-age=300'});return res.end(fs.readFileSync(file));}
if(req.method==='POST'&&url==='/api/billboard/submit'){let raw=Buffer.alloc(0);for await(const c of req){raw=Buffer.concat([raw,c]);if(raw.length>MAX_BYTES+200000)throw new Error('Request too large');}const parts=parseMultipart(req,raw);const val=n=>{const p=parts.find(x=>x.name===n);return p?p.body.toString('utf8').trim():''};const size=val('size');const z=SIZES[size];const title=val('title'),link=val('link'),name=val('name'),email=val('email'),image=parts.find(x=>x.name==='image');if(!z||!title||!link||!email||!image||!image.filename)return send(res,400,{error:'size, title, link, email and image are required'});if(image.body.length>MAX_BYTES)return send(res,413,{error:'Image exceeds 5MB'});if(!/^image\/(png|jpeg|webp|gif)$/i.test(image.contentType))return send(res,400,{error:'Only PNG, JPEG, WEBP or GIF images are accepted'});if([title,name,link].some(textBlocked))return send(res,422,{verdict:'FAIL',error:'Content failed automatic moderation'});let u;try{u=new URL(link);if(!/^https?:$/.test(u.protocol))throw 0;}catch{return send(res,400,{error:'link must be an http(s) URL'});}const s=load();const pos=findPosition(s,z.w,z.h);if(!pos)return send(res,409,{error:'No available billboard space for this size'});const id='ad_'+crypto.randomUUID();const ext=image.contentType==='image/jpeg'?'.jpg':image.contentType==='image/png'?'.png':image.contentType==='image/webp'?'.webp':'.gif';mkdir(path.join(DATA_ROOT,'media'));fs.writeFileSync(path.join(DATA_ROOT,'media',id+ext),image.body);const ad={id,status:'PENDING_PAYMENT',size,size_label:z.label,w:z.w,h:z.h,x:pos.x,y:pos.y,title,name,email,link,mime:image.contentType,ext,created_at:new Date().toISOString(),gauntlet:'PASS',human_review:'PENDING',payment_status:'unpaid'};s.ads.push(ad);save(s);try{const session=await stripe({mode:'payment',success_url:PUBLIC_BASE+'/billboard.html?paid=1&ad_id='+encodeURIComponent(id),cancel_url:PUBLIC_BASE+'/billboard.html?cancelled=1','metadata[ad_id]':id,'metadata[product]':'DREAMLEDGER-BILLBOARD','metadata[size]':size,'line_items[0][price_data][currency]':'nzd','line_items[0][price_data][unit_amount]':z.price,'line_items[0][price_data][product_data][name]':'DreamLedger Billboard - '+z.label,'line_items[0][quantity]':1},'dreamledger-billboard-'+id);ad.session_id=session.id;ad.status='AWAITING_REVIEW';save(s);return send(res,200,{ok:true,verdict:'PASS',human_review:'PENDING',ad_id:id,checkout_url:session.url});}catch(e){s.ads=s.ads.filter(a=>a.id!==id);save(s);try{fs.unlinkSync(path.join(DATA_ROOT,'media',id+ext));}catch{}return send(res,503,{error:e.message});}}
if(req.method==='GET'&&url==='/api/billboard/review-queue'){if(!isAdmin(req))return send(res,403,{error:'Forbidden'});const s=load();return send(res,200,{ads:s.ads.filter(a=>a.status==='AWAITING_REVIEW'||a.status==='REVIEW_HOLD'||a.status==='APPROVED_PENDING_PAYMENT')});}
if(req.method==='POST'&&url==='/api/billboard/review'){if(!isAdmin(req))return send(res,403,{error:'Forbidden'});let b='';for await(const c of req){b+=c;if(b.length>20000)throw new Error('Request too large');}const x=JSON.parse(b||'{}');const s=load();const ad=s.ads.find(a=>a.id===x.ad_id);if(!ad)return send(res,404,{error:'Ad not found'});if(!['APPROVE','REJECT','HOLD'].includes(x.decision))return send(res,400,{error:'decision must be APPROVE, REJECT or HOLD'});ad.human_review=x.decision==='APPROVE'?'PASS':x.decision==='REJECT'?'FAIL':'HOLD';ad.reviewed_at=new Date().toISOString();ad.review_note=String(x.note||'');if(x.decision==='APPROVE')ad.status=ad.payment_status==='paid'?'PUBLISHED':'APPROVED_PENDING_PAYMENT';else if(x.decision==='REJECT')ad.status='REJECTED';else ad.status='REVIEW_HOLD';save(s);return send(res,200,{ok:true,status:ad.status});}
return false;}
module.exports={handle,handlePaidSession};
