'use strict';
const fs=require('fs');const path=require('path');const crypto=require('crypto');const revenueLedger=require('../lib/revenueLedger');
const ROOT=process.env.BILLBOARD_DATA_DIR||'/var/data/billboard';const BASE=(process.env.PUBLIC_BASE_URL||'https://dreamledger.org').replace(/\/$/,'');const STRIPE=process.env.STRIPE_SECRET_KEY||'';const ADMIN=process.env.MARKETPLACE_ADMIN_TOKEN||'';const MAX=5*1024*1024;const CANVAS=1000;
const MARKETS={GLOBAL:'Global',NZ:'New Zealand',AU:'Australia',ZA:'South Africa',AMERICAS:'Americas',EUROPE:'Europe'};
const SIZES={small:{label:'Founding Tile',w:100,h:100,price:5000,inventory:100,sku:'BILLBOARD-SMALL'},medium:{label:'Medium',w:200,h:100,price:7900,inventory:50,sku:'BILLBOARD-MEDIUM'},wide:{label:'Wide',w:500,h:200,price:14900,inventory:30,sku:'BILLBOARD-WIDE'},large:{label:'Large',w:500,h:500,price:34900,inventory:20,sku:'BILLBOARD-LARGE'},takeover:{label:'Global Takeover',w:1000,h:1000,price:99900,inventory:1,sku:'BILLBOARD-TAKEOVER'}};
const BAD=/\b(?:n[i1]gg(?:er|a)|fagg(?:ot|ots)|kike|chink|spic|coon|wetback|retard(?:ed)?|kill\s+(?:all|the)|white\s+power|heil\s+hitler|gas\s+the|death\s+to)\b/i;
function mkdir(p){fs.mkdirSync(p,{recursive:true})}function read(f,d){try{return JSON.parse(fs.readFileSync(f,'utf8'))}catch{return d}}function write(f,v){mkdir(path.dirname(f));fs.writeFileSync(f,JSON.stringify(v,null,2)+'\n','utf8')}function send(res,s,b){if(res.writableEnded)return;res.writeHead(s,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(b))}
function market(v){v=String(v||'GLOBAL').toUpperCase();return MARKETS[v]?v:null}function file(m){return path.join(ROOT,'markets',m,'billboard.json')}function media(id){return path.join(ROOT,'media',id)}function load(m){return read(file(m),{version:2,market:m,canvas:{w:CANVAS,h:CANVAS},ads:[]})}function save(m,s){write(file(m),s)}
function parse(raw,ct){const m=String(ct||'').match(/boundary=(?:"([^"]+)"|([^;]+))/i);if(!m)throw Error('multipart/form-data required');const b=Buffer.from('--'+(m[1]||m[2]));const out=[];let p=0;while(true){const i=raw.indexOf(b,p);if(i<0)break;let j=i+b.length;if(raw.slice(j,j+2).equals(Buffer.from('--')))break;if(raw.slice(j,j+2).equals(Buffer.from('\r\n')))j+=2;const n=raw.indexOf(b,j);if(n<0)break;const part=raw.slice(j,n-2);const q=part.indexOf(Buffer.from('\r\n\r\n'));if(q<0){p=n;continue}const h=part.slice(0,q).toString();const body=part.slice(q+4);const nm=h.match(/name="([^"]+)"/i);const fn=h.match(/filename="([^"]*)"/i);const ty=h.match(/Content-Type:\s*([^\r\n]+)/i);out.push({name:nm?nm[1]:'',filename:fn?fn[1]:'',type:ty?ty[1].trim():'',body});p=n}return out}
function val(parts,n){const p=parts.find(x=>x.name===n);return p?p.body.toString('utf8').trim():''}function pos(s,w,h){for(let y=0;y<=CANVAS-h;y+=100)for(let x=0;x<=CANVAS-w;x+=100){if(!s.ads.some(a=>a.status!=='REJECTED'&&x<a.x+a.w&&x+w>a.x&&y<a.y+a.h&&y+h>a.y))return{x,y}}return null}
function remaining(s){const used=s.ads.filter(a=>a.status!=='REJECTED').reduce((n,a)=>n+a.w*a.h,0);return Math.max(0,Math.floor((1000000-used)/10000))}
function admin(req){return ADMIN&&String(req.headers['x-marketplace-admin-token']||'')===ADMIN}
async function stripe(params,key){if(!STRIPE)throw Error('STRIPE_SECRET_KEY is not configured');const f=new URLSearchParams();for(const[k,v]of Object.entries(params))f.set(k,String(v));const r=await fetch('https://api.stripe.com/v1/checkout/sessions',{method:'POST',headers:{Authorization:'Bearer '+STRIPE,'Content-Type':'application/x-www-form-urlencoded','Idempotency-Key':key},body:f});const t=await r.text();const d=JSON.parse(t);if(!r.ok)throw Error(d?.error?.message||'Stripe error');return d}
function allMarkets(){return Object.keys(MARKETS)}function findAd(id){for(const m of allMarkets()){const s=load(m);const a=s.ads.find(x=>x.id===id);if(a)return{m,s,a}}return null}
function publish(a){if(a.fulfillment_recorded||a.payment_status!=='paid'||a.human_review!=='PASS')return;if(Number(a.amount_total_minor)<=0)return;const f=revenueLedger.createFulfillment({transactionId:a.transaction_id,productId:a.sku,offerId:a.sku,silo:'BILLBOARD',amountMinor:a.amount_total_minor,currency:'NZD',customerEmail:a.email});revenueLedger.recordFulfillment({eventId:a.transaction_id+':fulfillment',transactionId:a.transaction_id,amountMinor:a.amount_total_minor,currency:'NZD',fulfillmentId:f.fulfillment.fulfillment_id,productId:a.sku,offerId:a.sku,silo:'BILLBOARD'});a.fulfillment_id=f.fulfillment.fulfillment_id;a.fulfillment_recorded=true;a.status='PUBLISHED';a.fulfilled_at=new Date().toISOString()}
function handlePaidSession(session,eventId){if(session?.metadata?.product!=='DREAMLEDGER-BILLBOARD')return false;const hit=findAd(session?.metadata?.ad_id);if(!hit)return true;const {m,s,a}=hit;a.payment_status=session.payment_status||'unknown';a.paid_at=new Date().toISOString();a.transaction_id=session.id;a.amount_total_minor=Number(session.amount_total||0);if(a.payment_status==='paid'&&!a.payment_recorded){revenueLedger.recordPayment({eventId:eventId||'billboard:'+session.id+':payment',transactionId:session.id,amountMinor:a.amount_total_minor,currency:session.currency||'nzd',productId:a.sku,offerId:a.sku,silo:'BILLBOARD'});a.payment_recorded=true}if(a.human_review==='PASS')publish(a);else if(a.human_review==='FAIL')a.status='REJECTED';else a.status='PAID_PENDING_REVIEW';save(m,s);return true}
async function handle(req,res,url){
let m=null;let q=url.split('/');if(url.startsWith('/api/billboard/inventory/'))m=market(q[4]);if(url.startsWith('/api/billboard/submit/'))m=market(q[4]);if(url.startsWith('/api/billboard/review-queue/'))m=market(q[4]);
if(req.method==='GET'&&url.startsWith('/api/billboard/inventory/')){if(!m)return send(res,400,{error:'Invalid market'});const s=load(m);return send(res,200,{market:m,market_name:MARKETS[m],canvas:s.canvas,founding_positions:100,founding_positions_remaining:remaining(s),sizes:Object.fromEntries(Object.entries(SIZES).map(([k,v])=>[k,{label:v.label,w:v.w,h:v.h,price_nzd:v.price/100,inventory:v.inventory,sku:v.sku}])),ads:s.ads.filter(a=>a.status==='PUBLISHED').map(a=>({...a,image_url:'/billboard/media/'+a.id}))})}
if(req.method==='GET'&&url==='/api/billboard'){return send(res,200,{markets:MARKETS,canonical:'/billboard',scarcity:'100 founding-equivalent positions per market'})}
if(req.method==='GET'&&url.startsWith('/billboard/media/')){const id=url.slice('/billboard/media/'.length);const hit=findAd(id);if(!hit||hit.a.status!=='PUBLISHED')return send(res,404,{error:'Not found'});const f=media(id);if(!fs.existsSync(f))return send(res,404,{error:'Media not found'});res.writeHead(200,{'Content-Type':hit.a.mime,'Cache-Control':'public,max-age=300'});return res.end(fs.readFileSync(f))}
if(req.method==='POST'&&url.startsWith('/api/billboard/submit/')){if(!m)return send(res,400,{error:'Invalid market'});let raw=Buffer.alloc(0);for await(const c of req){raw=Buffer.concat([raw,c]);if(raw.length>MAX+200000)throw Error('Request too large')}let parts;try{parts=parse(raw,req.headers['content-type'])}catch(e){return send(res,400,{error:e.message})}const size=val(parts,'size'),z=SIZES[size],title=val(parts,'title'),link=val(parts,'link'),name=val(parts,'name'),email=val(parts,'email'),image=parts.find(x=>x.name==='image');if(!z||!title||!link||!email||!image||!image.filename)return send(res,400,{error:'size, title, link, email and image are required'});if(image.body.length>MAX)return send(res,413,{error:'Image exceeds 5MB'});if(!/^image\/(png|jpeg|webp|gif)$/i.test(image.type))return send(res,400,{error:'Unsupported image type'});if([title,name,link].some(v=>BAD.test(String(v))))return send(res,422,{error:'Content failed automatic moderation'});let u;try{u=new URL(link);if(!/^https?:$/.test(u.protocol))throw 0}catch{return send(res,400,{error:'Destination must be http(s)'})}const s=load(m),p=pos(s,z.w,z.h);if(!p)return send(res,409,{error:'SOLD_OUT_FOR_MARKET_AND_SIZE',market:m});const id='ad_'+crypto.randomUUID();const ext=image.type==='image/jpeg'?'.jpg':image.type==='image/png'?'.png':image.type==='image/webp'?'.webp':'.gif';mkdir(path.dirname(media(id)));fs.writeFileSync(media(id),image.body);const a={id,market:m,sku:z.sku,status:'PENDING_PAYMENT',size,size_label:z.label,w:z.w,h:z.h,x:p.x,y:p.y,title,name,email,link,mime:image.type,ext,created_at:new Date().toISOString(),human_review:'PENDING',payment_status:'unpaid',scarcity_bucket:'FOUNDING_100'};s.ads.push(a);save(m,s);try{const session=await stripe({mode:'payment',success_url:BASE+'/billboard/'+m.toLowerCase()+'?paid=1&ad_id='+id,cancel_url:BASE+'/billboard/'+m.toLowerCase()+'?cancelled=1',customer_creation:'always','metadata[ad_id]':id,'metadata[product]':'DREAMLEDGER-BILLBOARD','metadata[market]':m,'metadata[sku]':z.sku,'metadata[size]':size,'line_items[0][price_data][currency]':'nzd','line_items[0][price_data][unit_amount]':z.price,'line_items[0][price_data][product_data][name]':'DreamLedger Billboard - '+z.label+' - '+MARKETS[m],'line_items[0][quantity]':1},'dreamledger-billboard-'+id);a.session_id=session.id;a.status='AWAITING_PAYMENT';save(m,s);return send(res,200,{ok:true,checkout_url:session.url,ad_id:id,market:m,price_nzd:z.price/100,founding_positions_remaining:remaining(s)})}catch(e){s.ads=s.ads.filter(x=>x.id!==id);save(m,s);try{fs.unlinkSync(media(id))}catch{}return send(res,503,{error:e.message})}}
if(req.method==='GET'&&url.startsWith('/api/billboard/review-queue/')){if(!admin(req)||!m)return send(res,403,{error:'Forbidden'});const s=load(m);return send(res,200,{market:m,ads:s.ads.filter(a=>['AWAITING_PAYMENT','PAID_PENDING_REVIEW','REVIEW_HOLD','APPROVED_PENDING_PAYMENT'].includes(a.status))})}
if(req.method==='POST'&&url.startsWith('/api/billboard/review/')){if(!admin(req)||!m)return send(res,403,{error:'Forbidden'});let b='';for await(const c of req)b+=c;const x=JSON.parse(b||'{}'),s=load(m),a=s.ads.find(v=>v.id===x.ad_id);if(!a)return send(res,404,{error:'Ad not found'});if(!['APPROVE','REJECT','HOLD'].includes(x.decision))return send(res,400,{error:'Invalid decision'});a.human_review=x.decision==='APPROVE'?'PASS':x.decision==='REJECT'?'FAIL':'HOLD';a.reviewed_at=new Date().toISOString();a.review_note=String(x.note||'');if(x.decision==='APPROVE'){if(a.payment_status==='paid')publish(a);else a.status='APPROVED_PENDING_PAYMENT'}else if(x.decision==='REJECT')a.status='REJECTED';else a.status='REVIEW_HOLD';save(m,s);return send(res,200,{ok:true,status:a.status})}
return false}
module.exports={handle,handlePaidSession};
