'use strict';
const crypto = require('crypto');
const ledger = require('../runtime/Ledger');
const agentBridge = require('../runtime/AgentBridge');
const ROOT = require('path').join(__dirname, '..');
const CONFIG = require('path').join(ROOT, 'distribution', 'config.json');
function loadConfig() { return JSON.parse(require('fs').readFileSync(CONFIG, 'utf8')); }
function safeText(value, max) { return String(value || '').slice(0, max || 160); }
function hashIp(req) { const ip = req.socket?.remoteAddress || 'unknown'; return crypto.createHash('sha256').update(ip).digest('hex').slice(0, 16); }
function cookie(req, name) { const raw = String(req.headers.cookie || ''); const m = raw.match(new RegExp('(?:^|;\\s*)' + name + '=([^;]+)')); return m ? decodeURIComponent(m[1]) : ''; }
function parseUserAgent(ua) { const s = String(ua || ''); const device = /iPhone|iPad|iPod/i.test(s) ? 'ios' : /Android/i.test(s) ? 'android' : /Mobile/i.test(s) ? 'mobile' : 'desktop'; const os = /Windows/i.test(s) ? 'windows' : /Mac OS X/i.test(s) ? 'macos' : /Android/i.test(s) ? 'android' : /iPhone|iPad|iPod/i.test(s) ? 'ios' : /Linux/i.test(s) ? 'linux' : 'unknown'; const browser = /Edg\\//i.test(s) ? 'edge' : /OPR\\//i.test(s) ? 'opera' : /Chrome\\//i.test(s) ? 'chrome' : /Firefox\\//i.test(s) ? 'firefox' : /Safari\\//i.test(s) && !/Chrome\\//i.test(s) ? 'safari' : 'other'; return { device, os, browser }; }
function send(res, status, body) { if (res.writableEnded) return true; res.writeHead(status, { 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-store' }); res.end(JSON.stringify(body)); return true; }
async function info(req, res, url) { const cfg = loadConfig(); const configuredToken = String(process.env.GO_INFO_TOKEN || ''); if (configuredToken && String(req.headers.authorization || '') !== 'Bearer ' + configuredToken) return send(res, 401, { error: 'Authorization required' }); const key = safeText(url.searchParams.get('key') || url.searchParams.get('src') || '', 120); if (!key) return send(res, 400, { error: 'key or src is required' }); const base = String(process.env.SUPABASE_URL || '').replace(/\\/$/, ''); const service = String(process.env.SUPABASE_SERVICE_ROLE_KEY || ''); if (!base || !service) return send(res, 503, { error: 'Attribution persistence is not configured' }); const q = '?select=payload&event_type=eq.DOORWAY_SESSION_STARTED&limit=10000'; const r = await fetch(base + '/rest/v1/telemetry_events' + q, { headers: { apikey: service, Authorization: 'Bearer ' + service } }); if (!r.ok) return send(res, 502, { error: 'Attribution store unavailable' }); const rows = await r.json(); const hits = (Array.isArray(rows) ? rows : []).map(x => x.payload || {}).filter(p => p.source === key || p.placement === key || p.campaign === key || p.offer_id === key); const unique = new Set(hits.map(p => p.ip_hash).filter(Boolean)).size; const devices = {}; const browsers = {}; const os = {}; for (const p of hits) { const ua = parseUserAgent(p.user_agent); devices[ua.device]=(devices[ua.device]||0)+1; browsers[ua.browser]=(browsers[ua.browser]||0)+1; os[ua.os]=(os[ua.os]||0)+1; } return send(res, 200, { key, scans: hits.length, unique_scans: unique, visits: hits.length, checkouts: 0, sales: 0, attribution_status: 'DOORWAY_CAPTURE_ONLY', devices, browsers, operating_systems: os, note: 'Checkout and sale attribution closes when the checkout producer carries session_id as Stripe client_reference_id.', doorway_id: cfg.doorway_id }); }
async function handle(req, res) { const url = new URL(req.url || '/', 'http://localhost'); if (req.method !== 'GET' || !url.pathname.startsWith('/go')) return false; if (url.pathname === '/go/info' || url.pathname === '/go/info/') return info(req, res, url); if (url.pathname !== '/go') return false; const cfg = loadConfig(); const q = url.searchParams; const source = safeText(q.get('utm_source') || q.get('src') || 'direct'); const medium = safeText(q.get('utm_medium') || 'direct'); const campaign = safeText(q.get('utm_campaign') || q.get('campaign') || cfg.default_campaign); const placement = safeText(q.get('placement') || 'unknown'); const experimentId = safeText(q.get('experiment_id') || q.get('experiment') || 'none'); const offerId = safeText(q.get('offer_id') || q.get('offer') || cfg.default_offer); const sessionId = crypto.randomUUID(); const repeatCookie = cookie(req, 'bec_go_session'); const ua = safeText(req.headers['user-agent'], 240); const parsedUa = parseUserAgent(ua); const ipHash = hashIp(req); const referrer = safeText(req.headers.referer || req.headers.referrer || '', 500); const country = safeText(req.headers['x-vercel-ip-country'] || req.headers['cf-ipcountry'] || req.headers['x-country-code'] || '', 8).toUpperCase(); const event = ledger.appendEvent({ graph_id: 'BEC-DISTRIBUTION', branch_id: campaign, node_id: 'canonical-doorway', event_type: 'DOORWAY_VISIT', silo: 'SILO_DREAMLEDGER', payload: { doorway_id: cfg.doorway_id, session_id: sessionId, source, medium, campaign, placement, experiment_id: experimentId, offer_id: offerId, ip_hash: ipHash, user_agent: ua, device: parsedUa.device, os: parsedUa.os, browser: parsedUa.browser, referrer, country, repeat: Boolean(repeatCookie) } }); const bridgeResult = await agentBridge.recordDoorwaySession({ session_id: sessionId, doorway_id: cfg.doorway_id, source, medium, campaign, placement, experiment_id: experimentId, offer_id: offerId, ip_hash: ipHash, user_agent: ua, device: parsedUa.device, os: parsedUa.os, browser: parsedUa.browser, referrer, country, repeat: Boolean(repeatCookie) }); const target = new URL(cfg.destination_path, 'https://dreamledger.org'); target.searchParams.set('utm_source', source); target.searchParams.set('utm_medium', medium); target.searchParams.set('utm_campaign', campaign); target.searchParams.set('session_id', sessionId); if (placement !== 'unknown') target.searchParams.set('placement', placement); if (experimentId !== 'none') target.searchParams.set('experiment_id', experimentId); if (offerId) target.searchParams.set('offer_id', offerId); res.writeHead(302, { Location: target.pathname + target.search, 'Cache-Control': 'no-store', 'Set-Cookie': `bec_go_session=${encodeURIComponent(sessionId)}; Max-Age=31536000; Path=/; Secure; SameSite=Lax`, 'X-BEC-Doorway-Event': event.event_id, 'X-BEC-Doorway-Session': sessionId, 'X-BEC-Agent-Bridge-Recorded': String(Boolean(bridgeResult.recorded)) }); res.end(); return true; }
module.exports = { handle };