'use strict';
const fs=require('fs');const path=require('path');const crypto=require('crypto');const https=require('https');
const ROOT=path.join(__dirname,'..');
const DATA_ROOT=process.env.DREAMIEZ_DATA_DIR||((fs.existsSync('/var/data')&&fs.statSync('/var/data').isDirectory())?'/var/data/dreamiez':path.join(ROOT,'data','dreamiez'));
const DATA=DATA_ROOT,USERS=path.join(DATA,'users.json'),GUILDS=path.join(DATA,'guilds.json'),COSMETICS=path.join(DATA,'cosmetics.json'),LISTINGS=path.join(DATA,'marketplace-listings.json'),MEDIA=path.join(DATA,'media');
function read(f,d){try{return JSON.parse(fs.readFileSync(f,'utf8'));}catch{return d;}}
function write(f,v){fs.mkdirSync(path.dirname(f),{recursive:true});const tmp=f+'.tmp-'+process.pid+'-'+Date.now();fs.writeFileSync(tmp,JSON.stringify(v,null,2)+'\n');fs.renameSync(tmp,f);}
function cookie(req,n){const m=String(req.headers.cookie||'').match(new RegExp('(?:^|;\\s*)'+n+'=([^;]+)'));return m?decodeURIComponent(m[1]):null;}
function userId(req,res){let id=cookie(req,'dreamiez_session')||cookie(req,'dreamiez_id');if(!id){id='u_'+crypto.randomBytes(6).toString('hex');res.setHeader('Set-Cookie','dreamiez_session='+encodeURIComponent(id)+'; Path=/; Max-Age=31536000; HttpOnly; SameSite=Lax');}return id;}
function passwordRecord(p){const salt=crypto.randomBytes(16).toString('hex');return{salt,hash:crypto.scryptSync(p,salt,64).toString('hex')};}
function verifyPassword(p,r){if(!r)return false;const a=Buffer.from(crypto.scryptSync(p,r.salt,64).toString('hex'),'hex'),b=Buffer.from(r.hash,'hex');return a.length===b.length&&crypto.timingSafeEqual(a,b);}
function ensureUser(id){const users=read(USERS,[]);let u=users.find(x=>x.id===id);if(!u){u={id,name:'Dreamer',email:null,email_verified:false,avatar:{height:2,build:2,skin:5},avatar_style:'dream',cosmetics:[],streak:0,lastVisit:null,guild:null};users.push(u);write(USERS,users);}const today=new Date().toISOString().slice(0,10);if(u.lastVisit!==today){const yesterday=new Date(Date.now()-86400000).toISOString().slice(0,10);u.streak=u.lastVisit===yesterday?u.streak+1:1;u.lastVisit=today;write(USERS,users);}return u;}
function rewards(u){return[{day:1,unlocked:u.streak>=1,asset:u.streak>=1?'dream-shell-day-1':null},{day:7,unlocked:u.streak>=7,asset:u.streak>=7?'elohim-bloom-day-7':null}];}
function account(u){return{account_id:u.id,streak:u.streak,avatar_style:u.avatar_style||'dream',avatar:u.avatar,cosmetics:u.cosmetics,rewards:rewards(u),email:u.email||null,email_verified:u.email_verified===true,name:u.name||'Dreamer'};}
async function body(req){return new Promise((resolve,reject)=>{let s='';req.on('data',c=>{s+=c;if(s.length>1000000)req.destroy();});req.on('end',()=>{try{resolve(s?JSON.parse(s):{});}catch(e){reject(e);}});req.on('error',reject);});}
function json(res,status,data){if(!res.writableEnded){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data));}return true;}
function listingPublic(x){return{id:x.id,seller_id:x.seller_id,seller_name:x.seller_name,title:x.title,description:x.description,category:x.category,price:x.price,currency:x.currency,condition:x.condition,location:x.location,photos:x.photos||[],status:x.status,created_at:x.created_at};}
function sendVerificationEmail(email,name,token){if(process.env.DREAMIEZ_SMOKE==='true')return Promise.resolve(true);const key=process.env.RESEND_API_KEY,from=process.env.RESEND_FROM_EMAIL,origin=process.env.PUBLIC_ORIGIN||'https://dreamledger.org';if(!key||!from)throw new Error('Email verification is not configured. Set RESEND_API_KEY and RESEND_FROM_EMAIL in Render.');const link=origin+'/dreamiez/verify-email.html?token='+encodeURIComponent(token);const payload=JSON.stringify({from,to:[email],subject:'Verify your DreamLedger account',html:'<p>Hi '+escapeHtml(name)+',</p><p>Verify your DreamLedger account:</p><p><a href="'+link+'">Verify my email</a></p><p>This link expires in 24 hours.</p>'});return new Promise((resolve,reject)=>{const request=https.request({hostname:'api.resend.com',path:'/emails',method:'POST',headers:{Authorization:'Bearer '+key,'Content-Type':'application/json','Content-Length':Buffer.byteLength(payload)}},r=>{let s='';r.on('data',c=>s+=c);r.on('end',()=>r.statusCode>=200&&r.statusCode<300?resolve(true):reject(new Error('Verification email provider rejected the request')))});request.on('error',reject);request.write(payload);request.end();});}
function escapeHtml(s){return String(s).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]||c));}
async function handle(req,res,url){url=typeof url==='string'?url:String(req.url||'').split('?')[0];if(!url.startsWith('/api/dreamiez')&&!url.startsWith('/api/account')&&!url.startsWith('/api/marketplace')&&!url.startsWith('/dreamiez'))return false;if(req.method==='GET'&&url==='/dreamiez'){res.writeHead(302,{Location:'/dreamiez/dreamiez.html'});res.end();return true;}const id=userId(req,res);let users=read(USERS,[]);const u=ensureUser(id);users=read(USERS,[]);
if(req.method==='POST'&&(url==='/api/dreamiez/account/create'||url==='/api/account/register')){const b=await body(req),email=String(b.email||'').trim().toLowerCase(),name=String(b.name||b.displayName||'Dreamer').trim().slice(0,60)||'Dreamer',password=String(b.password||'');if(!/^\S+@\S+\.\S+$/.test(email))return json(res,422,{error:'Please enter a valid email address.'});if(password.length<8)return json(res,422,{error:'Password must be at least 8 characters.'});const existing=users.find(x=>x.email===email);if(existing&&existing.id!==id)return json(res,409,{error:existing.email_verified?'An account with this email already exists.':'An account exists but is not verified. Log in and request a new verification email.'});const stored=users.find(x=>x.id===id)||u;stored.email=email;stored.name=name;stored.email_verified=false;stored.avatar_style=String(b.avatar_style||b.avatarStyle||'dream').slice(0,30);stored.password=passwordRecord(password);stored.account_created_at=new Date().toISOString();stored.email_verification_token=crypto.randomBytes(32).toString('hex');stored.email_verification_expires=new Date(Date.now()+86400000).toISOString();write(USERS,users);let verification_sent=false,verification_error=null;try{await sendVerificationEmail(email,name,stored.email_verification_token);verification_sent=true;}catch(err){verification_error=err.message;}res.setHeader('Set-Cookie','dreamiez_session='+encodeURIComponent(stored.id)+'; Path=/; Max-Age=31536000; HttpOnly; SameSite=Lax');return json(res,201,{ok:true,verification_required:true,verification_sent,message:verification_sent?'Account created. Check your email to verify it.':'Account created. You can log in now; email verification is still required before selling.',verification_error,next:'/verify-email.html'});}
if(req.method==='POST'&&(url==='/api/dreamiez/account/resend-verification'||url==='/api/account/resend-verification')){if(!u.email)return json(res,400,{error:'Create an account first.'});if(u.email_verified)return json(res,200,{ok:true,verified:true});const stored=users.find(x=>x.id===id)||u;stored.email_verification_token=crypto.randomBytes(32).toString('hex');stored.email_verification_expires=new Date(Date.now()+86400000).toISOString();write(USERS,users);try{await sendVerificationEmail(stored.email,stored.name,stored.email_verification_token);}catch(err){return json(res,503,{error:err.message});}return json(res,200,{ok:true,message:'Verification email sent.'});}
if(req.method==='GET'&&url==='/api/dreamiez/account/verify'){const q=String(req.url||'').split('?')[1]||'',params=new URLSearchParams(q),token=params.get('token')||'';const found=users.find(x=>x.email_verification_token===token);if(!found||!found.email_verification_expires||Date.parse(found.email_verification_expires)<Date.now())return json(res,400,{error:'Verification link is invalid or expired.'});found.email_verified=true;found.email_verification_token=null;found.email_verification_expires=null;write(USERS,users);res.setHeader('Set-Cookie','dreamiez_session='+encodeURIComponent(found.id)+'; Path=/; Max-Age=31536000; HttpOnly; SameSite=Lax');return json(res,200,{ok:true,account:account(found),next:'/account.html'});}
if(req.method==='POST'&&(url==='/api/dreamiez/account/login'||url==='/api/account/login')){const b=await body(req),found=users.find(x=>x.email===String(b.email||'').trim().toLowerCase());if(!found||!verifyPassword(String(b.password||''),found.password))return json(res,401,{error:'Invalid email or password.'});res.setHeader('Set-Cookie','dreamiez_session='+encodeURIComponent(found.id)+'; Path=/; Max-Age=31536000; HttpOnly; SameSite=Lax');return json(res,200,{ok:true,account:account(found),user:account(found),verification_required:found.email_verified!==true,next:'/account.html'});}
if(req.method==='POST'&&(url==='/api/dreamiez/account/logout'||url==='/api/account/logout')){res.setHeader('Set-Cookie','dreamiez_session=; Path=/; Max-Age=0; HttpOnly; SameSite=Lax');return json(res,200,{ok:true});}
if(req.method==='GET'&&(url==='/api/dreamiez/me'||url==='/api/account/me'))return json(res,200,{authenticated:Boolean(u),account:account(u),user:account(u),rewards:rewards(u)});
if(req.method==='GET'&&url==='/api/dreamiez/rewards')return json(res,200,{streak:u.streak,rewards:rewards(u)});
if(req.method==='GET'&&url==='/api/dreamiez/cosmetics')return json(res,200,read(COSMETICS,[]));
if(req.method==='POST'&&url==='/api/dreamiez/avatar'){if(u.email&&!u.email_verified)return json(res,403,{error:'Verify your email first.'});const b=await body(req);if(typeof b.height!=='number'||typeof b.build!=='number'||typeof b.skin!=='number')return json(res,422,{error:'Invalid avatar.'});const stored=users.find(x=>x.id===id)||u;stored.avatar={height:Math.max(0,Math.min(4,b.height)),build:Math.max(0,Math.min(4,b.build)),skin:Math.max(0,Math.min(9,b.skin))};stored.avatar_style=String(b.avatar_style||stored.avatar_style||'dream').slice(0,30);write(USERS,users);return json(res,200,{success:true,account:account(stored)});}
if(req.method==='POST'&&url==='/api/dreamiez/cosmetics/claim'){const b=await body(req),c=read(COSMETICS,[]).find(x=>x.id===b.cosmetic_id);if(!c||!c.streak_reward||u.streak<c.streak_reward)return json(res,403,{error:'Cosmetic is not unlocked.'});const stored=users.find(x=>x.id===id)||u;if(!stored.cosmetics.includes(c.id))stored.cosmetics.push(c.id);write(USERS,users);return json(res,200,{success:true,account:account(stored)});}
if(req.method==='GET'&&url==='/api/dreamiez/guilds/my')return json(res,200,{guild:read(GUILDS,[]).find(g=>g.id===u.guild)||null});
if(req.method==='POST'&&url==='/api/dreamiez/guilds'){const b=await body(req),name=String(b.name||'').trim();if(!name)return json(res,400,{error:'name required'});if(u.guild)return json(res,409,{error:'already in a guild'});const guilds=read(GUILDS,[]),guild={id:'g_'+crypto.randomBytes(4).toString('hex'),name,tag:name.replace(/[^A-Za-z0-9]/g,'').slice(0,4).toUpperCase(),members:[id],leader:id,created:new Date().toISOString()};guilds.push(guild);const stored=users.find(x=>x.id===id)||u;stored.guild=guild.id;write(GUILDS,guilds);write(USERS,users);return json(res,201,guild);}
if(req.method==='GET'&&url==='/api/dreamiez/leaderboard')return json(res,200,users.map(x=>({name:x.name||x.id.slice(0,8),score:(x.streak||0)*10+(x.cosmetics||[]).length*5})).sort((a,b)=>b.score-a.score));
if(req.method==='GET'&&url==='/api/marketplace/listings'){const listings=read(LISTINGS,[]).filter(x=>x.status==='APPROVED').map(listingPublic);return json(res,200,{items:listings});}
if(req.method==='GET'&&url==='/api/marketplace/my-listings'){const listings=read(LISTINGS,[]).filter(x=>x.seller_id===id).map(listingPublic);return json(res,200,{items:listings});}
if(req.method==='POST'&&url==='/api/marketplace/listings'){if(!u.email||u.email_verified!==true)return json(res,403,{error:'verified account required before selling'});const b=await body(req),title=String(b.title||'').trim().slice(0,100),description=String(b.description||'').trim().slice(0,2000),category=String(b.category||'Marketplace').trim().slice(0,40),condition=String(b.condition||'').trim().slice(0,40),location=String(b.location||'').trim().slice(0,100),price=Number(b.price);if(!title||!description||!Number.isFinite(price)||price<=0)return json(res,422,{error:'title, description and positive price are required'});const listings=read(LISTINGS,[]),item={id:'lst_'+crypto.randomBytes(8).toString('hex'),seller_id:id,seller_name:u.name||'Dreamer',title,description,category,condition,location,price:Math.round(price*100)/100,currency:'NZD',status:'PENDING',checkout_available:false,photos:Array.isArray(b.photos)?b.photos.slice(0,12):[],created_at:new Date().toISOString()};listings.push(item);write(LISTINGS,listings);return json(res,201,{ok:true,item:listingPublic(item),message:'Listing submitted for approval'});}
if(req.method==='POST'&&url==='/api/marketplace/media'){if(!u.email||u.email_verified!==true)return json(res,403,{error:'verified account required'});const b=await body(req),mime=String(b.mime||'').toLowerCase(),data=String(b.data||'');if(!/^image\/(jpeg|png|webp)$/.test(mime)||!data)return json(res,422,{error:'JPEG, PNG or WebP image required'});const raw=data.replace(/^data:[^;]+;base64,/,'');if(raw.length>8*1024*1024)return json(res,413,{error:'image too large'});const idm='img_'+crypto.randomBytes(8).toString('hex'),ext=mime==='image/png'?'png':mime==='image/webp'?'webp':'jpg';fs.mkdirSync(MEDIA,{recursive:true});fs.writeFileSync(path.join(MEDIA,idm+'.'+ext),Buffer.from(raw,'base64'));return json(res,201,{ok:true,id:idm,url:'/api/marketplace/media/'+idm});}
if(req.method==='GET'&&url.startsWith('/api/marketplace/media/')){const mid=url.slice('/api/marketplace/media/'.length),files=fs.existsSync(MEDIA)?fs.readdirSync(MEDIA).filter(x=>x.startsWith(mid+'.')):[];if(!files.length)return json(res,404,{error:'media not found'});const file=path.join(MEDIA,files[0]),ext=path.extname(file).toLowerCase(),mime=ext==='.png'?'image/png':ext==='.webp'?'image/webp':'image/jpeg';res.writeHead(200,{'Content-Type':mime,'Cache-Control':'public,max-age=31536000,immutable'});res.end(fs.readFileSync(file));return true;}
return false;}
module.exports={handle};