'use strict';
const fs=require('fs');const path=require('path');const crypto=require('crypto');
const ROOT=path.join(__dirname,'..');
const DATA_ROOT=process.env.DREAMIEZ_DATA_DIR||((fs.existsSync('/var/data')&&fs.statSync('/var/data').isDirectory())?'/var/data/dreamiez':path.join(ROOT,'data','dreamiez'));
const DATA=DATA_ROOT,USERS=path.join(DATA,'users.json'),GUILDS=path.join(DATA,'guilds.json'),COSMETICS=path.join(DATA,'cosmetics.json'),LISTINGS=path.join(DATA,'marketplace-listings.json');
function read(f,d){try{return JSON.parse(fs.readFileSync(f,'utf8'));}catch{return d;}}
function write(f,v){fs.mkdirSync(path.dirname(f),{recursive:true});const tmp=f+'.tmp-'+process.pid+'-'+Date.now();fs.writeFileSync(tmp,JSON.stringify(v,null,2)+'\n');fs.renameSync(tmp,f);}
function cookie(req,n){const m=String(req.headers.cookie||'').match(new RegExp('(?:^|;\\s*)'+n+'=([^;]+)'));return m?decodeURIComponent(m[1]):null;}
function userId(req,res){let id=cookie(req,'dreamiez_session')||cookie(req,'dreamiez_id');if(!id){id='u_'+crypto.randomBytes(6).toString('hex');res.setHeader('Set-Cookie','dreamiez_session='+encodeURIComponent(id)+'; Path=/; Max-Age=31536000; HttpOnly; SameSite=Lax');}return id;}
function passwordRecord(p){const salt=crypto.randomBytes(16).toString('hex');return{salt,hash:crypto.scryptSync(p,salt,64).toString('hex')};}
function verifyPassword(p,r){if(!r)return false;const a=Buffer.from(crypto.scryptSync(p,r.salt,64).toString('hex'),'hex'),b=Buffer.from(r.hash,'hex');return a.length===b.length&&crypto.timingSafeEqual(a,b);}
function ensureUser(id){const users=read(USERS,[]);let u=users.find(x=>x.id===id);if(!u){u={id,name:'Dreamer',email:null,avatar:{height:1,build:1,skin:5},avatar_style:'dream',cosmetics:[],streak:0,lastVisit:null,guild:null};users.push(u);write(USERS,users);}const today=new Date().toISOString().slice(0,10);if(u.lastVisit!==today){const yesterday=new Date(Date.now()-86400000).toISOString().slice(0,10);u.streak=u.lastVisit===yesterday?u.streak+1:1;u.lastVisit=today;write(USERS,users);}return u;}
function rewards(u){return[{day:1,unlocked:u.streak>=1,asset:u.streak>=1?'dream-shell-day-1':null},{day:7,unlocked:u.streak>=7,asset:u.streak>=7?'elohim-bloom-day-7':null}];}
function account(u){return{account_id:u.id,streak:u.streak,avatar_style:u.avatar_style||'dream',avatar:u.avatar,cosmetics:u.cosmetics,rewards:rewards(u),email:u.email||null,name:u.name||'Dreamer'};}
async function body(req){return new Promise((resolve,reject)=>{let s='';req.on('data',c=>{s+=c;if(s.length>1000000)req.destroy();});req.on('end',()=>{try{resolve(s?JSON.parse(s):{});}catch(e){reject(e);}});req.on('error',reject);});}
function json(res,status,data){if(!res.writableEnded){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data));}return true;}
function listingPublic(x){return{id:x.id,seller_id:x.seller_id,title:x.title,description:x.description,category:x.category,price:x.price,currency:x.currency,condition:x.condition,location:x.location,status:x.status,created_at:x.created_at};}
async function handle(req,res,url){url=typeof url==='string'?url:String(req.url||'').split('?')[0];if(!url.startsWith('/api/dreamiez')&&!url.startsWith('/api/marketplace')&&!url.startsWith('/dreamiez'))return false;if(req.method==='GET'&&url==='/dreamiez'){res.writeHead(302,{Location:'/dreamiez/dreamiez.html'});res.end();return true;}const id=userId(req,res);let users=read(USERS,[]);const u=ensureUser(id);users=read(USERS,[]);
if(req.method==='POST'&&url==='/api/dreamiez/account/create'){const b=await body(req),email=String(b.email||'').trim().toLowerCase(),name=String(b.name||b.displayName||'Dreamer').trim().slice(0,40)||'Dreamer',password=String(b.password||'');if(!/^\S+@\S+\.\S+$/.test(email))return json(res,422,{error:'valid email required'});if(password.length<8)return json(res,422,{error:'password must be at least 8 characters'});const existing=users.find(x=>x.email===email);if(existing&&existing.id!==id)return json(res,409,{error:'account already exists'});const stored=users.find(x=>x.id===id)||u;stored.email=email;stored.name=name;stored.avatar_style=String(b.avatar_style||b.avatarStyle||'dream');stored.password=passwordRecord(password);stored.account_created_at=new Date().toISOString();write(USERS,users);res.setHeader('Set-Cookie','dreamiez_session='+encodeURIComponent(stored.id)+'; Path=/; Max-Age=31536000; HttpOnly; SameSite=Lax');return json(res,201,{ok:true,account:account(stored),user:account(stored),next:'/account.html'});}
if(req.method==='POST'&&url==='/api/dreamiez/account/login'){const b=await body(req),found=users.find(x=>x.email===String(b.email||'').trim().toLowerCase());if(!found||!verifyPassword(String(b.password||''),found.password))return json(res,401,{error:'invalid email or password'});res.setHeader('Set-Cookie','dreamiez_session='+encodeURIComponent(found.id)+'; Path=/; Max-Age=31536000; HttpOnly; SameSite=Lax');return json(res,200,{ok:true,account:account(found),user:account(found),next:'/account.html'});}
if(req.method==='GET'&&url==='/api/dreamiez/me')return json(res,200,{account:account(u),user:account(u),rewards:rewards(u)});
if(req.method==='GET'&&url==='/api/dreamiez/rewards')return json(res,200,{streak:u.streak,rewards:rewards(u)});
if(req.method==='GET'&&url==='/api/dreamiez/cosmetics')return json(res,200,read(COSMETICS,[]));
if(req.method==='POST'&&url==='/api/dreamiez/avatar'){const b=await body(req);if(typeof b.height!=='number'||typeof b.build!=='number'||typeof b.skin!=='number')return json(res,422,{error:'invalid avatar'});const stored=users.find(x=>x.id===id)||u;stored.avatar={height:Math.max(0,Math.min(2,b.height)),build:Math.max(0,Math.min(2,b.build)),skin:Math.max(0,Math.min(9,b.skin))};stored.avatar_style=String(b.avatar_style||stored.avatar_style||'dream').slice(0,30);write(USERS,users);return json(res,200,{success:true,account:account(stored)});}
if(req.method==='POST'&&url==='/api/dreamiez/cosmetics/claim'){const b=await body(req),c=read(COSMETICS,[]).find(x=>x.id===b.cosmetic_id);if(!c||!c.streak_reward||u.streak<c.streak_reward)return json(res,403,{error:'streak reward not unlocked'});const stored=users.find(x=>x.id===id)||u;if(!stored.cosmetics.includes(c.id))stored.cosmetics.push(c.id);write(COSMETICS,read(COSMETICS,[]));write(USERS,users);return json(res,200,{success:true,account:account(stored)});}
if(req.method==='GET'&&url==='/api/dreamiez/guilds/my')return json(res,200,{guild:read(GUILDS,[]).find(g=>g.id===u.guild)||null});
if(req.method==='POST'&&url==='/api/dreamiez/guilds'){const b=await body(req),name=String(b.name||'').trim();if(!name)return json(res,400,{error:'name required'});if(u.guild)return json(res,409,{error:'already in a guild'});const guilds=read(GUILDS,[]),guild={id:'g_'+crypto.randomBytes(4).toString('hex'),name,tag:name.replace(/[^A-Za-z0-9]/g,'').slice(0,4).toUpperCase(),members:[id],leader:id,created:new Date().toISOString()};guilds.push(guild);const stored=users.find(x=>x.id===id)||u;stored.guild=guild.id;write(GUILDS,guilds);write(USERS,users);return json(res,201,guild);}
if(req.method==='GET'&&url==='/api/dreamiez/leaderboard')return json(res,200,users.map(x=>({name:x.name||x.id.slice(0,8),score:(x.streak||0)*10+(x.cosmetics||[]).length*5})).sort((a,b)=>b.score-a.score));
if(req.method==='GET'&&url==='/api/marketplace/listings'){const listings=read(LISTINGS,[]).filter(x=>x.status==='APPROVED').map(listingPublic);return json(res,200,{items:listings});}
if(req.method==='GET'&&url==='/api/marketplace/my-listings'){const listings=read(LISTINGS,[]).filter(x=>x.seller_id===id).map(listingPublic);return json(res,200,{items:listings});}
if(req.method==='POST'&&url==='/api/marketplace/listings'){const b=await body(req),title=String(b.title||'').trim().slice(0,100),description=String(b.description||'').trim().slice(0,2000),category=String(b.category||'B2B').trim().slice(0,40),condition=String(b.condition||'').trim().slice(0,40),location=String(b.location||'').trim().slice(0,100),price=Number(b.price);if(!u.email)return json(res,403,{error:'create an account before listing'});if(!title||!description||!Number.isFinite(price)||price<=0)return json(res,422,{error:'title, description and positive price are required'});const listings=read(LISTINGS,[]),item={id:'lst_'+crypto.randomBytes(8).toString('hex'),seller_id:id,seller_name:u.name||'Dreamer',title,description,category,condition,location,price:Math.round(price*100)/100,currency:'NZD',status:'PENDING',checkout_available:false,created_at:new Date().toISOString()};listings.push(item);write(LISTINGS,listings);return json(res,201,{ok:true,item:listingPublic(item),message:'Listing submitted for approval'});}
return false;}
module.exports={handle};
