'use strict';
const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const {URL}=require('url');

const DATA_ROOT=process.env.DREAMIEZ_DATA_DIR||((fs.existsSync('/var/data')&&fs.statSync('/var/data').isDirectory())?'/var/data/dreamiez':path.join(__dirname,'..','data','dreamiez'));
const USERS=path.join(DATA_ROOT,'users.json');
const COOKIE='dreamiez_session';
const BASE=String(process.env.SUPABASE_URL||'').replace(/\/$/,'');
const KEY=String(process.env.SUPABASE_SERVICE_ROLE_KEY||'');

function json(res,status,data){if(res.writableEnded)return true;res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(data));return true}
function html(res,status,data){if(res.writableEnded)return true;res.statusCode=status;res.setHeader('Content-Type','text/html; charset=utf-8');res.setHeader('Cache-Control','no-store');res.end(data);return true}
function cookie(req){const m=String(req.headers.cookie||'').match(/(?:^|;\s*)dreamiez_session=([^;]+)/);return m?decodeURIComponent(m[1]):null}
function users(){try{return JSON.parse(fs.readFileSync(USERS,'utf8'))}catch{return []}}
function currentUser(req){const id=cookie(req);return id?users().find(u=>u&&u.id===id&&u.email):null}
function esc(v){return String(v==null?'':v).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]))}
function validHandle(v){return /^[a-z0-9](?:[a-z0-9-]{0,28}[a-z0-9])?$/.test(v)}
function normalizeHandle(v){return String(v||'').trim().toLowerCase()}
async function supabase(pathname,options={}){if(!BASE||!KEY)throw new Error('Supabase persistence is not configured');const r=await fetch(BASE+'/rest/v1/'+pathname,{...options,headers:{apikey:KEY,Authorization:'Bearer '+KEY,'Content-Type':'application/json',Prefer:'return=representation',...(options.headers||{})}});const text=await r.text();let data=null;try{data=text?JSON.parse(text):null}catch{data=text}if(!r.ok){const e=new Error(data&&data.message?data.message:'Supabase request failed');e.status=r.status;e.data=data;throw e}return data}
async function ledger(handle){const rows=await supabase('dream_ledgers?select=id,handle,display_name,bio,avatar_url,dreammeez_id,theme,permanence_year,created_at,updated_at,status&handle=eq.'+encodeURIComponent(handle)+'&status=eq.active&limit=1');return Array.isArray(rows)?rows[0]||null:null}
async function items(id){return supabase('dream_ledger_items?select=id,item_type,title,body,target,position,created_at&ledger_id=eq.'+encodeURIComponent(id)+'&published=eq.true&order=position.asc,created_at.desc&limit=50')}
function page(ledger,items){const title=(ledger.display_name||ledger.handle)+' | Dream Ledger 3000';const description=(ledger.bio||'A persistent Ledger on Dream Ledger 3000.').slice(0,160);const image=ledger.avatar_url?'<meta property="og:image" content="'+esc(ledger.avatar_url)+'">':'';const cards=items.map(i=>{const target=i.target&&/^https?:\/\//i.test(i.target)?'<a class="card" href="'+esc(i.target)+'" rel="noopener noreferrer"><b>'+esc(i.title)+'</b><span>'+esc(i.body||i.item_type)+'</span></a>':'<div class="card"><b>'+esc(i.title)+'</b><span>'+esc(i.body||i.item_type)+'</span></div>';return target}).join('');return '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+esc(title)+'</title><meta name="description" content="'+esc(description)+'"><link rel="canonical" href="https://dreamledger.org/u/'+encodeURIComponent(ledger.handle)+'"><meta property="og:title" content="'+esc(title)+'"><meta property="og:description" content="'+esc(description)+'"><meta property="og:url" content="https://dreamledger.org/u/'+encodeURIComponent(ledger.handle)+'">'+image+'<meta name="twitter:card" content="summary"><script type="application/ld+json">'+JSON.stringify({'@context':'https://schema.org','@type':'ProfilePage','name':ledger.display_name||ledger.handle,'url':'https://dreamledger.org/u/'+ledger.handle,'description':description,image:ledger.avatar_url||undefined}).replace(/</g,'\\u003c')+'</script><style>body{margin:0;background:#0b0b10;color:#f5f5f7;font:16px system-ui,-apple-system,sans-serif}.wrap{max-width:760px;margin:auto;padding:28px 18px 70px}.top{display:flex;gap:18px;align-items:center}.avatar{width:88px;height:88px;border-radius:24px;object-fit:cover;background:#222}.name{font-size:32px;font-weight:800}.handle{opacity:.6}.bio{font-size:18px;line-height:1.5;margin:24px 0}.grid{display:grid;gap:12px}.card{display:flex;flex-direction:column;gap:6px;padding:18px;border:1px solid #292934;border-radius:18px;background:#15151d;color:inherit;text-decoration:none}.card span{opacity:.72}.brand{margin-top:40px;opacity:.55;font-size:13px}</style></head><body><main class="wrap"><section class="top">'+(ledger.avatar_url?'<img class="avatar" src="'+esc(ledger.avatar_url)+'" alt="">':'<div class="avatar"></div>')+'<div><div class="name">'+esc(ledger.display_name||ledger.handle)+'</div><div class="handle">@'+esc(ledger.handle)+'</div></div></section>'+(ledger.bio?'<p class="bio">'+esc(ledger.bio)+'</p>':'')+(cards?'<section class="grid">'+cards+'</section>':'<p class="bio">This Ledger is alive, but nothing has been published yet.</p>')+'<div class="brand">Dream Ledger 3000 · Your Ledger. Your World.</div></main></body></html>'}
function claimPage(handle){return '<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Claim @'+esc(handle)+' | Dream Ledger 3000</title><meta name="robots" content="noindex"></head><body style="font:18px system-ui;max-width:640px;margin:80px auto;padding:20px"><h1>@'+esc(handle)+' is available</h1><p>This Ledger does not exist yet.</p><a href="/register">Create an account</a> · <a href="/create">Claim this handle</a></body></html>'}
async function handle(req,res,p){
 if(req.method==='GET'&&/^\/u\/[A-Za-z0-9-]+\/?$/.test(p)){const raw=p.slice(3).replace(/\/$/,'');const h=normalizeHandle(raw);if(!validHandle(h))return html(res,404,claimPage(h));try{const l=await ledger(h);if(!l)return html(res,404,claimPage(h));return html(res,200,await (async()=>{const it=await items(l.id);return page(l,it)})())}catch(e){return html(res,503,'<h1>Ledger temporarily unavailable</h1>')}}
 if(req.method==='GET'&&p==='/create'){return html(res,200,'<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Create your Ledger | Dream Ledger 3000</title></head><body style="font:16px system-ui;max-width:640px;margin:40px auto;padding:20px"><h1>Create your Ledger</h1><form id="f"><input name="handle" placeholder="handle" required pattern="[a-z0-9-]+"><input name="display_name" placeholder="display name"><textarea name="bio" placeholder="bio"></textarea><button>Create Ledger</button></form><p id="m"></p><script>f.onsubmit=async e=>{e.preventDefault();m.textContent='Creating...';const b=Object.fromEntries(new FormData(f));const r=await fetch('/api/ledgers',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(b)});const d=await r.json();if(r.ok)location.href=d.url;else m.textContent=d.error||'Unable to create Ledger';}</script></body></html>')}
 if(req.method==='GET'&&p==='/api/ledgers/check'){const h=normalizeHandle(new URL(req.url,'http://localhost').searchParams.get('handle'));if(!validHandle(h))return json(res,422,{available:false,error:'Handle must be lowercase letters, numbers and hyphens.'});try{return json(res,200,{handle:h,available:!(await ledger(h))})}catch(e){return json(res,503,{available:false,error:'Ledger service unavailable'})}}
 if(req.method==='POST'&&p==='/api/ledgers'){const u=currentUser(req);if(!u)return json(res,401,{error:'Log in first to create a Ledger.'});let body={};try{body=JSON.parse(await new Promise((resolve,reject)=>{let s='';req.on('data',c=>{s+=c;if(s.length>100000)reject(new Error('Request too large'))});req.on('end',()=>{try{resolve(s?JSON.parse(s):{})}catch(e){reject(e)}});req.on('error',reject)}))}catch{return json(res,400,{error:'Invalid JSON'})}const h=normalizeHandle(body.handle);if(!validHandle(h))return json(res,422,{error:'Handle must be 1-30 characters using lowercase letters, numbers and hyphens.'});if(!/^[^\r\n]{1,80}$/.test(String(body.display_name||h)))return json(res,422,{error:'Invalid display name.'});try{if(await ledger(h))return json(res,409,{error:'That handle is already claimed.'});const row={id:crypto.randomUUID(),owner_account_id:u.id,handle:h,display_name:String(body.display_name||h).trim().slice(0,80),bio:String(body.bio||'').trim().slice(0,500),avatar_url:null,dreammeez_id:null,theme:'default',permanence_year:3000,status:'active'};const created=await supabase('dream_ledgers',{method:'POST',body:JSON.stringify(row)});return json(res,201,{ok:true,ledger:Array.isArray(created)?created[0]:created,url:'/u/'+h})}catch(e){if(e.status===409)return json(res,409,{error:'That handle is already claimed.'});return json(res,503,{error:'Ledger service unavailable'})}}
 return false;
}
module.exports={handle};
