'use strict';
const fs=require('fs');const path=require('path');
const ROOT=path.join(__dirname,'..');const SELLERS=path.join(ROOT,'data','sellers.json');const TX=path.resolve(process.env.LEDGER_DATA_DIR||path.join(ROOT,'data','transactions'));const ADMIN_TOKEN=process.env.MARKETPLACE_ADMIN_TOKEN||'';
function read(file,fallback){try{return JSON.parse(fs.readFileSync(file,'utf8'));}catch{return fallback;}}
function write(file,v){fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,JSON.stringify(v,null,2)+'\n');}
function authorized(req){return Boolean(ADMIN_TOKEN)&&String(req.headers['authorization']||'')===`Bearer ${ADMIN_TOKEN}`;}
async function body(req){return new Promise((resolve,reject)=>{let s='';req.on('data',c=>{s+=c;if(s.length>1000000)req.destroy();});req.on('end',()=>{try{resolve(s?JSON.parse(s):{});}catch(e){reject(e);}});req.on('error',reject);});}
function json(res,status,data){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data));}
async function handle(req,res,url){if(!url.startsWith('/api/sellers'))return false;if(!authorized(req))return json(res,401,{error:'Unauthorized'});if(req.method==='POST'&&url==='/api/sellers'){const b=await body(req);if(!b.id||!b.name)return json(res,400,{error:'id and name required'});const sellers=read(SELLERS,[]);if(sellers.some(x=>x.id===b.id))return json(res,409,{error:'seller already exists'});sellers.push({id:String(b.id),name:String(b.name),approved:Boolean(b.approved),registered_at:new Date().toISOString()});write(SELLERS,sellers);return json(res,201,{success:true});}const m=url.match(/^\/api\/sellers\/([^/]+)\/payouts$/);if(req.method==='GET'&&m){const sellerId=decodeURIComponent(m[1]);const files=fs.existsSync(TX)?fs.readdirSync(TX).filter(x=>x.endsWith('.json')):[];const transactions=[];for(const f of files){try{const t=read(path.join(TX,f),null);if(t&&t.seller===sellerId&&t.payment_status==='paid')transactions.push({transaction_id:t.transaction_id,amount_total_nzd:t.amount_total_nzd,net_to_seller_nzd:t.net_to_seller_nzd,payment_status:t.payment_status,created_at:t.created_at});}catch{}}const net=transactions.reduce((n,t)=>n+Number(t.net_to_seller_nzd||0),0);return json(res,200,{seller:sellerId,transaction_count:transactions.length,net_total_nzd:Math.round(net*100)/100,transactions});}return false;}
module.exports={handle};
