function json(data:any,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json','cache-control':'no-store'}})}
export default async function handler(request:Request){
 if(request.method!=='POST')return new Response('Method not allowed',{status:405});
 const secret=process.env.STRIPE_SECRET_KEY,base=process.env.SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!secret||!base||!key)return json({error:'Server configuration missing'},503);
 let body:any;try{body=await request.json()}catch{return json({error:'Invalid JSON'},400)}
 const sessionId=String(body.session_id||'').trim();const title=String(body.title||'').trim();const image_url=String(body.image_url||'').trim();const destination_url=String(body.destination_url||'').trim();if(!sessionId||!title||!image_url||!destination_url)return json({error:'session_id, title, image_url and destination_url are required'},400);if(title.length>80)return json({error:'Title too long'},400);
 try{new URL(image_url);new URL(destination_url)}catch{return json({error:'Invalid URL'},400)}
 const sr=await fetch('https://api.stripe.com/v1/checkout/sessions/'+encodeURIComponent(sessionId),{headers:{authorization:`Bearer ${secret}`}});const s=await sr.json();if(!sr.ok||s.payment_status!=='paid')return json({error:'Payment is not verified'},402);if(s.metadata?.billboard!=='true'||s.metadata?.molt_beach!=='true')return json({error:'Not a billboard session'},403);
 const url=base.replace(/\/$/,'')+'/rest/v1/molt_beach_campaigns?stripe_session_id=eq.'+encodeURIComponent(sessionId)+'&select=campaign_id,status';const q=await fetch(url,{headers:{apikey:key,authorization:`Bearer ${key}`}});if(!q.ok)return json({error:'Campaign lookup failed'},503);const rows=await q.json();if(!rows.length)return json({error:'Paid campaign not yet recorded. Retry shortly.'},409);if(rows[0].status==='PUBLISHED')return json({status:'PUBLISHED',campaign_id:rows[0].campaign_id});
 const patch=await fetch(base.replace(/\/$/,'')+'/rest/v1/molt_beach_campaigns?stripe_session_id=eq.'+encodeURIComponent(sessionId),{method:'PATCH',headers:{apikey:key,authorization:`Bearer ${key}`,'content-type':'application/json','prefer':'return=minimal'},body:JSON.stringify({title,image_url,destination_url,updated_at:new Date().toISOString()})});if(!patch.ok)return json({error:'Campaign intake update failed'},500);return json({status:'PAID_PENDING_REVIEW',campaign_id:rows[0].campaign_id,message:'Submission received. Human review is required before publication.'});
}
