'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const OUT = path.join(ROOT, 'compiled', 'website');
const INDEX = path.join(OUT, 'index.html');
const NEWS = path.join(ROOT, 'data', 'silo-news.json');
const AUCTIONS = path.join(ROOT, 'data', 'auctions.json');
const MANIFEST = path.join(ROOT, 'manifests', 'CUBE-PUBLIC-SURFACE-MANIFEST.json');

function read(file, fallback) {
  try { return JSON.parse(fs.readFileSync(file, 'utf8')); } catch { return fallback; }
}
function esc(value) {
  return String(value == null ? '' : value).replace(/[&<>\"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
}
function js(value) { return JSON.stringify(value).replace(/<\//g, '<\\/'); }
function write(file, value) { fs.mkdirSync(path.dirname(file), { recursive: true }); fs.writeFileSync(file, value, 'utf8'); }

if (!fs.existsSync(INDEX)) throw new Error('PublicSurfaceAugment: compiled index missing');
const manifest = read(MANIFEST, {});
const news = read(NEWS, {});
const auctions = Array.isArray(read(AUCTIONS, {}).auctions) ? read(AUCTIONS, {}).auctions : [];
let html = fs.readFileSync(INDEX, 'utf8');

const billboard = `<section class="section" id="billboard"><div class="head"><div class="eyebrow">BILLBOARD</div><h2>What is moving now.</h2><p>Approved offers, market lanes and fresh signals. The board is generated from the same public commerce sources as the storefront.</p></div><div id="dl-billboard" class="rail"></div></section>`;
const newsItems = Object.keys(news).reduce((all, key) => all.concat((Array.isArray(news[key]) ? news[key] : []).map(item => ({...item, silo:key}))), []).sort((a,b) => String(b.published_at).localeCompare(String(a.published_at))).slice(0, 8);
const liveAuctions = auctions.filter(a => a.status === 'live').slice(0, 6);
const seed = `<section class="section" id="community"><div class="head"><div class="eyebrow">COMMUNITY SEED</div><h2>Plant a lane. Prove it. Let it compound.</h2><p>DreamLedger is a public doorway, not a claim that a decentralized network already exists. The seed is deliberately small: discover useful signals, publish approved offers, keep silos separate, record proof, and let contributors build distinct lanes.</p></div><div class="collections"><article class="collection"><div><div class="eyebrow">01 / SIGNAL</div><h3>Bring a useful signal</h3><p>Problems, demand, market movement and customer requests become inputs, not noise.</p></div></article><article class="collection"><div><div class="eyebrow">02 / OFFER</div><h3>Turn signal into an offer</h3><p>Every public product remains approval-gated and server-authoritative.</p></div></article><article class="collection"><div><div class="eyebrow">03 / PROOF</div><h3>Make the result auditable</h3><p>Payments, fulfilment and deployment state should leave durable evidence.</p></div></article><article class="collection"><div><div class="eyebrow">04 / SILO</div><h3>Grow without contamination</h3><p>Each lane can compound independently while the commerce spine stays shared.</p></div></article></div></section>`;
const commerceDoorway = `<section class="section" id="commerce-doorway"><div class="head"><div><div class="eyebrow">COMMERCE DOORWAY</div><h2>Find it. Build it. Own it.</h2></div><p>Agent-ready commerce starts with useful data, explicit offers and trustworthy purchase paths. Live inventory is separated from experiments and future concepts.</p></div><div class="collections"><article class="collection"><div><div class="eyebrow">INVERSE SHOPPING</div><h3>Inverse Shopping</h3><p>Describe the exact thing you want. Match intent to available listings and keep the decision trail auditable.</p></div></article><article class="collection"><div><div class="eyebrow">AGENTIC COMMERCE</div><h3>ELoM</h3><p>Agent-ready product information, proof and routing for commerce systems that need structured truth rather than marketing fog.</p></div></article><article class="collection"><div><div class="eyebrow">DIGITAL PROPERTY</div><h3>Billboard</h3><p>Founding digital placement is live at NZ$50.00. Publication remains approval-gated.</p></div></article><article class="collection"><div><div class="eyebrow">DIAGNOSTIC</div><h3>Commander Deck Diagnostic</h3><p>Current public checkout target: NZ$29. The diagnostic lane remains separate from other commercial surfaces.</p></div></article><article class="collection"><div><div class="eyebrow">BUILD CANDIDATE</div><h3>Agentic Commerce Launch Pack</h3><p>NZ$59 concept. Validate demand before activation. No revenue is claimed until a real payment clears.</p></div></article><article class="collection"><div><div class="eyebrow">BUILD CANDIDATE</div><h3>DOOH Commerce Proof Pack</h3><p>NZ$59 concept. Designed around measurable digital out-of-home signals, placements and reporting. No revenue is claimed until checkout is live and paid.</p></div></article><article class="collection"><div><div class="eyebrow">WORLD / BRAND</div><h3>MaxiBrown Eye / Cortex / Kingdom</h3><p>Brand exploration lane only. Names are not presented as live products, customers or established businesses.</p></div></article><article class="collection"><div><div class="eyebrow">POSITION</div><h3>True Kingdom / Make the Real</h3><p>Messaging territory for future commerce and ownership products. No unsupported claims are made on the public surface.</p></div></article></div></section>`;

if (!html.includes('id="billboard"')) html = html.replace('<section class="section" id="catalog">', billboard + '<section class="section" id="catalog">');
if (!html.includes('id="community"')) html = html.replace('<section class="section"><div class="proof">', seed + '<section class="section"><div class="proof">');
if (!html.includes('id="commerce-doorway"')) html = html.replace('<main>', '<main>' + commerceDoorway);
if (!html.includes('href="/community.html"')) html = html.replace('<a class="btn gold" href="/marketplace.html">Marketplace</a>', '<a class="btn gold" href="/community.html">Community</a><a class="btn gold" href="/marketplace.html">Marketplace</a>');

const boardScript = `<script id="dreamledger-architecture-board">(()=>{const products=fetch('/api/products',{cache:'no-store'}).then(r=>r.ok?r.json():{products:[]}).then(x=>x.products||[]).catch(()=>[]);const auctions=${js(liveAuctions)};const news=${js(newsItems)};const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));const money=(v,c)=>String(c||'NZD').toUpperCase()+' '+(Number(v||0)/100).toFixed(2);Promise.all([products]).then(([ps])=>{const items=[...ps.slice(0,4).map(p=>({kind:'OFFER',title:p.name,desc:p.description||'Approved product',meta:money(p.price,p.currency),silo:p.silo,buy:p.id})),...auctions.map(a=>({kind:'AUCTION',title:a.title,desc:a.description,meta:'Buy now '+money(a.buy_now_price*100,a.currency),silo:a.silo})),...news.slice(0,3).map(n=>({kind:'NEWS',title:n.headline,desc:n.kind+' / '+n.source,meta:n.silo}))];const rail=document.getElementById('dl-billboard');if(!rail)return;rail.innerHTML=items.length?items.map(x=>'<article class="card"><div class="art">'+esc(x.kind)+'</div><div class="body"><span class="tag">'+esc(x.silo||'dreamledger')+'</span><h3>'+esc(x.title)+'</h3><div class="desc">'+esc(x.desc)+'</div><div class="price">'+esc(x.meta||'')+'</div>'+(x.buy?'<div class="actions"><button class="btn gold" data-dl-buy="'+esc(x.buy)+'">Buy now</button></div>':'')+'</div></article>').join(''):'<div class="card"><div class="body">No current board items.</div></div>';rail.querySelectorAll('[data-dl-buy]').forEach(b=>b.onclick=async()=>{b.disabled=true;b.textContent='Creating checkout...';try{const r=await fetch('/api/offer-checkout/create',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({offer_id:b.dataset.dlBuy})});const d=await r.json();if(!r.ok||!d.checkout_url)throw Error(d.error||'Checkout unavailable');location.href=d.checkout_url}catch(e){b.disabled=false;b.textContent='Buy now';alert(e.message)}})})})()</script>`;
if (!html.includes('id="dreamledger-architecture-board"')) html = html.replace('</body>', boardScript + '</body>');

write(INDEX, html);
const community = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Community Seed | DreamLedger</title><style>body{font:16px/1.6 system-ui,sans-serif;margin:0;background:#070707;color:#f7f7f3}.wrap{max-width:900px;margin:auto;padding:40px 20px}a{color:#f2c14e}article{border:1px solid #292929;border-radius:16px;padding:22px;margin:14px 0;background:#111}h1{font-size:clamp(3rem,8vw,6rem);line-height:.9;margin:0 0 20px}h2{color:#f2c14e}.muted{color:#999}</style></head><body><main class="wrap"><p><a href="/">DREAMLEDGER</a></p><h1>Community seed.</h1><p class="muted">A small public protocol for growing useful commerce lanes without collapsing them into one giant bucket.</p><article><h2>Signal</h2><p>Bring a real problem, request, market movement or useful discovery.</p></article><article><h2>Offer</h2><p>Turn validated demand into an explicit, approval-gated offer.</p></article><article><h2>Proof</h2><p>Publish evidence of what actually happened. Do not promote a capability as live until it is verified.</p></article><article><h2>Silo</h2><p>Keep distinct communities and commercial lanes separated. Shared infrastructure does not require shared identity or inventory.</p></article><article><h2>Compounding</h2><p>Successful lanes can attract contributors, new offers and new demand. The network effect is earned through useful outcomes, not declared in advance.</p></article><p><a href="/">Return to the public catalog</a></p></main></body></html>`;
write(path.join(OUT,'community.html'), community);
write(path.join(OUT,'community.json'), JSON.stringify({schema:'DREAMLEDGER-COMMUNITY-SEED/v1',status:'seed',principles:['signal','offer','proof','silo','compounding'],public_routes:(manifest.public_surfaces||[]).map(x=>x.route)}, null, 2)+'\n');
console.log(JSON.stringify({augment:'PASS',billboard:true,community_seed:true,commerce_doorway:true,news_items:newsItems.length,live_auctions:liveAuctions.length}));