'use strict';

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = path.join(__dirname, '..');
const OUT = path.join(ROOT, 'compiled', 'website');
const INDEX = path.join(OUT, 'index.html');
const CATALOG_TEMPLATE = path.join(ROOT, 'surface', 'catalog.html');
const CINEMA_TEMPLATE = path.join(ROOT, 'surface', 'cinema.html');
const DIGITAL_TEMPLATE = path.join(ROOT, 'surface', 'digital-products.html');
const MANIFEST = path.join(ROOT, 'manifests', 'CUBE-PUBLIC-SURFACE-MANIFEST.json');
const OFFERS = path.join(ROOT, 'catalog', 'offers', 'offers.json');
const IP = path.join(ROOT, 'catalog', 'ip-capabilities.json');
const PRODUCTS = path.join(ROOT, 'catalog', 'products');
const NEWS = path.join(ROOT, 'data', 'silo-news.json');
const AUCTIONS = path.join(ROOT, 'data', 'auctions.json');
const BILLBOARDS = path.join(ROOT, '..', 'commerce', 'dreamledger-regional-billboard-offers.json');
const PROOF = path.join(ROOT, 'PROOF-CUBE-SURFACE-COMPILATION.json');
const FORBIDDEN_PUBLIC = ['amplissa','bbw','big beautiful women','adult-only','adult only','stripe_secret_key','stripe_webhook_secret','/var/data/','127.0.0.1','BEC-PRIME','ELOHIM','internal control plane','CollectorsCoast','HappyHomarid'];
function must(file){if(!fs.existsSync(file))throw new Error('CUBE surface input missing: '+path.relative(ROOT,file));}
function digest(file){return crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');}
function json(file){return JSON.parse(fs.readFileSync(file,'utf8'));}
function write(file,value){fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,value,'utf8');}
function assertClean(label,content){const lower=String(content).toLowerCase();const hit=FORBIDDEN_PUBLIC.find(token=>lower.includes(token.toLowerCase()));if(hit)throw new Error('PUBLIC_SURFACE_GATE_FAILED: '+label+' contains forbidden token: '+hit);}
function accountShell(title,body){return '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+title+' | DreamLedger</title><style>body{font-family:system-ui,sans-serif;margin:0;background:#f6f7f9;color:#17191d}main{max-width:620px;margin:7vh auto;padding:28px;background:#fff;border:1px solid #ddd;border-radius:16px}h1{margin-top:0}label{display:block;margin:14px 0 6px;font-weight:600}input,select,textarea{width:100%;box-sizing:border-box;padding:12px;border:1px solid #bbb;border-radius:9px;font:inherit}button{margin-top:18px;padding:12px 16px;border:0;border-radius:9px;background:#17191d;color:#fff;font:inherit;cursor:pointer}.muted{color:#666}.error{color:#b00020;margin-top:12px}a{color:inherit}.avatar-preview{width:160px;height:160px;margin:20px auto;border-radius:50%;display:grid;place-items:center;background:linear-gradient(145deg,#fff,#e7dcff);border:2px solid #17191d;box-shadow:0 12px 30px #17151218}.avatar-face{width:82px;height:70px;border-radius:45%;background:#17191d;position:relative}.avatar-face:before,.avatar-face:after{content:"";position:absolute;top:23px;width:10px;height:10px;border-radius:50%;background:#fff}.avatar-face:before{left:20px}.avatar-face:after{right:20px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.grid button{margin:0;background:#eee;color:#17191d}.topline{display:flex;justify-content:space-between;gap:10px;margin-bottom:20px;font-size:.8rem}</style></head><body><main>'+body+'</main></body></html>';}
function buildAccountPages(){
  write(path.join(OUT,'login.html'),accountShell('Log in','<h1>Log in</h1><p class="muted">Use your DreamLedger account.</p><form id="login"><label>Email</label><input id="email" type="email" required><label>Password</label><input id="password" type="password" required><button type="submit">Log in</button><div id="msg"></div></form><p><a href="/register.html">Create a DreamLedger account</a></p>'));
  write(path.join(OUT,'register.html'),accountShell('Create account','<h1>Create account</h1><p class="muted">Create a standard DreamLedger account.</p><form id="register"><label>Name</label><input id="name" required><label>Email</label><input id="email" type="email" required><label>Password</label><input id="password" type="password" minlength="8" required><button type="submit">Create account</button><div id="msg"></div></form><p><a href="/login.html">Log in</a></p>'));
  write(path.join(OUT,'account.html'),accountShell('Account','<div class="topline"><a href="/">DreamLedger</a><a href="/marketplace.html">Marketplace</a></div><h1>Your DreamLedger account</h1><div id="state">Loading...</div><p><a href="/avatar.html">Customize avatar</a></p><p><a href="/login.html">Log in</a></p>'));
  write(path.join(OUT,'avatar.html'),accountShell('Avatar','<div class="topline"><a href="/account.html">Account</a><a href="/marketplace.html">Marketplace</a></div><h1>Your avatar</h1><p class="muted">Make the identity that appears around your DreamLedger account.</p><div class="avatar-preview"><div id="face" class="avatar-face"></div></div><div class="grid"><button type="button" data-height="0">Short</button><button type="button" data-height="2">Medium</button><button type="button" data-height="4">Tall</button><button type="button" data-build="0">Lean</button><button type="button" data-build="2">Classic</button><button type="button" data-build="4">Broad</button></div><label>Skin</label><input id="skin" type="range" min="0" max="9" value="5"><button id="save" type="button">Save avatar</button><div id="msg" class="muted"></div><script>(async function(){var state=document.getElementById("msg"),h=2,b=2,s=5;try{var r=await fetch("/api/account/me",{credentials:"include",cache:"no-store"}),d=await r.json();if(!d.authenticated){state.innerHTML="Please <a href=\"/login.html\">log in</a> first.";return}h=d.account.avatar.height;b=d.account.avatar.build;s=d.account.avatar.skin;document.getElementById("skin").value=s;function render(){var f=document.getElementById("face");f.style.transform="scale("+(0.82+h*0.06)+","+(0.85+b*0.07)+")";f.style.opacity=String(0.72+s*0.028)}render();document.querySelectorAll("[data-height]").forEach(function(x){x.onclick=function(){h=Number(x.dataset.height);render()}});document.querySelectorAll("[data-build]").forEach(function(x){x.onclick=function(){b=Number(x.dataset.build);render()}});document.getElementById("skin").oninput=function(){s=Number(this.value);render()};document.getElementById("save").onclick=async function(){var rr=await fetch("/api/dreamiez/avatar",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({height:h,build:b,skin:s})});var dd=await rr.json();if(!rr.ok)throw Error(dd.error||"Could not save avatar");state.textContent="Avatar saved."}}catch(e){state.textContent=e.message}})();</script>'));
  write(path.join(OUT,'marketplace.html'),accountShell('Marketplace','<div class="topline"><a href="/">DreamLedger</a><a href="/account.html">Account</a></div><h1>B2B Marketplace</h1><p class="muted">A launch-ready marketplace shell for approved services, products and implementations. Listings can be submitted by verified accounts and approved before publication.</p><div id="items">Loading marketplace...</div><p><a href="/register.html">Create account</a> or <a href="/login.html">log in</a> to submit an offering.</p><script>fetch("/api/marketplace/listings",{credentials:"include",cache:"no-store"}).then(r=>r.json()).then(d=>{var el=document.getElementById("items"),items=d.items||[];el.innerHTML=items.length?items.map(function(x){return "<article style=\"padding:14px 0;border-top:1px solid #ddd\"><strong>"+String(x.title).replace(/[<>]/g,"")+"</strong><p class=\"muted\">"+String(x.description).replace(/[<>]/g,"")+"</p><b>"+String(x.currency)+" "+String(x.price)+"</b></article>"}).join(""):"<p class=\"muted\">No approved listings yet. The marketplace is ready for its first supply.</p>"}).catch(function(){document.getElementById("items").textContent="Marketplace unavailable."});</script>'));
  write(path.join(OUT,'assets.html'),'<main><h1>DreamLedger Assets</h1><p>Approved public commerce assets.</p></main>');
}
const required=[MANIFEST,OFFERS,IP,PRODUCTS,NEWS,AUCTIONS,CATALOG_TEMPLATE,CINEMA_TEMPLATE,DIGITAL_TEMPLATE,BILLBOARDS];
required.forEach(must);fs.mkdirSync(path.join(OUT,'assets'),{recursive:true});
const manifest=json(MANIFEST), offers=json(OFFERS), ip=json(IP), news=json(NEWS), auctions=json(AUCTIONS), billboards=json(BILLBOARDS);
let html=fs.readFileSync(CATALOG_TEMPLATE,'utf8');
html=html.replace('__NEWS_JSON__',JSON.stringify(news).replace(/</g,'\\u003c')).replace('__BILLBOARDS_JSON__',JSON.stringify(billboards).replace(/</g,'\\u003c'));
const accountNav='<div class="account-nav" style="position:fixed;right:12px;top:10px;z-index:80;display:flex;gap:7px;align-items:center"><a href="/marketplace.html" style="padding:8px 10px;border:1px solid #ddd5c8;border-radius:999px;background:#fffdf8;font-size:.68rem;font-weight:800">Marketplace</a><a href="/account.html" aria-label="Account" style="width:38px;height:38px;border:2px solid #171512;border-radius:50%;background:linear-gradient(145deg,#fff,#e7dcff);display:grid;place-items:center;font-size:16px">●</a></div>';
html=html.replace('<header class="nav">',accountNav+'<header class="nav">');
html=html.replace('<a class="btn purple" style="padding:8px 13px;min-height:36px;margin:0" href="#new">Browse</a>','<div style="display:flex;gap:7px;align-items:center"><a class="btn" style="padding:8px 11px;min-height:36px;margin:0" href="/login.html">Log in</a><a class="btn purple" style="padding:8px 13px;min-height:36px;margin:0" href="#new">Browse</a></div>');
assertClean('catalog',html);write(INDEX,html);write(path.join(OUT,'cinema.html'),fs.readFileSync(CINEMA_TEMPLATE,'utf8'));write(path.join(OUT,'digital-products.html'),fs.readFileSync(DIGITAL_TEMPLATE,'utf8'));
assertClean('cinema',fs.readFileSync(path.join(OUT,'cinema.html'),'utf8'));assertClean('digital-products',fs.readFileSync(path.join(OUT,'digital-products.html'),'utf8'));buildAccountPages();
for(const page of ['login.html','register.html','account.html','avatar.html','marketplace.html','assets.html'])assertClean(page,fs.readFileSync(path.join(OUT,page),'utf8'));
const productCount=fs.readdirSync(PRODUCTS).filter(x=>x.endsWith('.json')).length,capabilityCount=Array.isArray(ip)?ip.length:(ip.capabilities||[]).length,offerCount=Array.isArray(offers)?offers.length:(offers.offers||[]).length,auctionCount=Array.isArray(auctions)?auctions.length:(auctions.auctions||[]).length,newsSilos=Object.keys(news||{}).length,billboardCount=Array.isArray(billboards.boards)?billboards.boards.length:0;
const build={type:'dreamledger-public-surface-compilation',status:'PASS',compiler:'surface-stable-v2',schema:manifest.schema,compiled_at:new Date().toISOString(),source_hashes:{catalog_template:digest(CATALOG_TEMPLATE),cinema_template:digest(CINEMA_TEMPLATE),digital_template:digest(DIGITAL_TEMPLATE),manifest:digest(MANIFEST),offers:digest(OFFERS),ip:digest(IP),news:digest(NEWS),auctions:digest(AUCTIONS),billboards:digest(BILLBOARDS),surface_html:crypto.createHash('sha256').update(html,'utf8').digest('hex')},counts:{capabilities:capabilityCount,offers:offerCount,products:productCount,news_silos:newsSilos,auctions:auctionCount,billboards:billboardCount},public_account_surfaces:['/login.html','/register.html','/account.html','/avatar.html','/marketplace.html','/assets.html'],public_surfaces:manifest.public_surfaces,gates:{approval_required_for_activation:manifest.surface_policy.approval_required_for_activation===true,private_material_excluded:manifest.surface_policy.private_material_excluded===true,silo_isolation_required:manifest.surface_policy.silo_isolation_required===true,forbidden_public_tokens_checked:true,template_compiled:true,cinema_surface_compiled:true,digital_products_surface_compiled:true,primary_account_pages_compiled:true,avatar_editor_compiled:true,marketplace_shell_compiled:true,top_right_account_control_compiled:true}};
write(PROOF,JSON.stringify(build,null,2)+'\n');console.log(JSON.stringify(build,null,2));
