'use strict';

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = path.join(__dirname, '..');
const OUT = path.join(ROOT, 'compiled', 'website');
const INDEX = path.join(OUT, 'index.html');
const CATALOG_TEMPLATE = path.join(ROOT, 'surface', 'catalog.html');
const CINEMA_TEMPLATE = path.join(ROOT, 'surface', 'cinema.html');
const DIGITAL_TEMPLATE = path.join(ROOT, 'surface', 'digital-products.html');
const MANIFEST = path.join(ROOT, 'manifests', 'CUBE-PUBLIC-SURFACE-MANIFEST.json');
const OFFERS = path.join(ROOT, 'catalog', 'offers', 'offers.json');
const IP = path.join(ROOT, 'catalog', 'ip-capabilities.json');
const PRODUCTS = path.join(ROOT, 'catalog', 'products');
const NEWS = path.join(ROOT, 'data', 'silo-news.json');
const AUCTIONS = path.join(ROOT, 'data', 'auctions.json');
const BILLBOARDS = path.join(ROOT, '..', 'commerce', 'dreamledger-regional-billboard-offers.json');
const PROOF = path.join(ROOT, 'PROOF-CUBE-SURFACE-COMPILATION.json');
const FORBIDDEN_PUBLIC = ['amplissa','bbw','big beautiful women','adult-only','adult only','stripe_secret_key','stripe_webhook_secret','/var/data/','127.0.0.1','BEC-PRIME','ELOHIM','internal control plane','CollectorsCoast','HappyHomarid'];
function must(file){if(!fs.existsSync(file))throw new Error('CUBE surface input missing: '+path.relative(ROOT,file));}
function digest(file){return crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');}
function json(file){return JSON.parse(fs.readFileSync(file,'utf8'));}
function write(file,value){fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,value,'utf8');}
function assertClean(label,content){const lower=String(content).toLowerCase();const hit=FORBIDDEN_PUBLIC.find(token=>lower.includes(token.toLowerCase()));if(hit)throw new Error('PUBLIC_SURFACE_GATE_FAILED: '+label+' contains forbidden token: '+hit);}
function accountShell(title,body){return '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#f5f0e7"><title>'+title+' | DreamLedger</title><style>:root{--bg:#f5f0e7;--paper:#fffdf8;--ink:#171512;--muted:#746f67;--line:#ddd5c8;--purple:#5d43d8;--gold:#d59d2f}*{box-sizing:border-box}body{font-family:system-ui,-apple-system,sans-serif;margin:0;background:var(--bg);color:var(--ink);font-size:15px;line-height:1.5}.site-nav{position:sticky;top:0;z-index:80;display:flex;align-items:center;justify-content:space-between;gap:10px;min-height:62px;padding:8px 14px;background:#f5f0e7f2;backdrop-filter:blur(16px);border-bottom:1px solid var(--line)}.site-brand{font-weight:950;letter-spacing:-.06em;white-space:nowrap}.site-brand span{color:var(--purple)}.site-links{display:flex;gap:8px;overflow-x:auto;white-space:nowrap;max-width:75%;scrollbar-width:none}.site-links::-webkit-scrollbar{display:none}.site-links a{font-size:.72rem;font-weight:850;padding:8px 10px;border:1px solid var(--line);border-radius:999px;text-decoration:none;color:var(--ink);flex:0 0 auto}main{max-width:720px;margin:28px auto;padding:24px;background:var(--paper);border:1px solid var(--line);border-radius:16px}h1{margin-top:0;letter-spacing:-.05em}label{display:block;margin:14px 0 6px;font-weight:700}input,select,textarea{width:100%;box-sizing:border-box;padding:12px;border:1px solid #bbb;border-radius:9px;font:inherit}button{margin-top:18px;padding:12px 16px;border:0;border-radius:9px;background:var(--ink);color:#fff;font:inherit;cursor:pointer}.muted{color:var(--muted)}.error{color:#b00020;margin-top:12px}a{color:inherit}.avatar-preview{width:160px;height:160px;margin:20px auto;border-radius:50%;display:grid;place-items:center;background:linear-gradient(145deg,#fff,#e7dcff);border:2px solid var(--ink);box-shadow:0 12px 30px #17151218}.avatar-face{width:82px;height:70px;border-radius:45%;background:var(--ink);position:relative}.avatar-face:before,.avatar-face:after{content:"";position:absolute;top:23px;width:10px;height:10px;border-radius:50%;background:#fff}.avatar-face:before{left:20px}.avatar-face:after{right:20px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.grid button{margin:0;background:#eee;color:var(--ink)}.topline{display:flex;justify-content:space-between;gap:10px;margin-bottom:20px;font-size:.8rem}@media(max-width:560px){.site-nav{padding:8px 10px}.site-links{max-width:72%;gap:5px}.site-links a{font-size:.66rem;padding:7px 8px}main{margin:16px 10px;padding:18px}}</style></head><body><header class="site-nav"><a class="site-brand" href="/">Dream<span>Ledger</span></a><nav class="site-links" aria-label="Main navigation"><a href="/avatar.html">Create avatar</a><a href="/billboard">Billboard</a><a href="/marketplace.html">Shop</a></nav></header><main>'+body+'</main></body></html>';}
function buildAccountPages(){
  write(path.join(OUT,'login.html'),accountShell('Log in','<h1>Log in</h1><p class="muted">Use your DreamLedger account.</p><form id="login"><label>Email</label><input id="email" type="email" required><label>Password</label><input id="password" type="password" required><button type="submit">Log in</button><div id="msg"></div></form><p><a href="/register.html">Create a DreamLedger account</a></p>'));
  write(path.join(OUT,'register.html'),accountShell('Create account','<h1>Create account</h1><p class="muted">Create a standard DreamLedger account.</p><form id="register"><label>Name</label><input id="name" required><label>Email</label><input id="email" type="email" required><label>Password</label><input id="password" type="password" minlength="8" required><button type="submit">Create account</button><div id="msg"></div></form><p><a href="/login.html">Log in</a></p>'));
  write(path.join(OUT,'account.html'),accountShell('Account','<div class="topline"><a href="/">DreamLedger</a><a href="/marketplace.html">Marketplace</a></div><h1>Your DreamLedger account</h1><div id="state">Loading...</div><p><a href="/avatar.html">Customize avatar</a></p><p><a href="/login.html">Log in</a></p>'));
  write(path.join(OUT,'avatar.html'),accountShell('Avatar','<h1>Make your avatar</h1><p class="muted">Choose a look, adjust the details and save it to your account.</p><div class="avatar-preview"><div id="face" class="avatar-face"></div></div><div class="grid"><button type="button" data-height="0">Short</button><button type="button" data-height="2">Medium</button><button type="button" data-height="4">Tall</button><button type="button" data-build="0">Lean</button><button type="button" data-build="2">Classic</button><button type="button" data-build="4">Broad</button></div><label>Skin</label><input id="skin" type="range" min="0" max="9" value="5"><button id="save" type="button">Save avatar</button><div id="msg" class="muted"></div><script>(async function(){var state=document.getElementById("msg"),h=2,b=2,s=5;try{var r=await fetch("/api/account/me",{credentials:"include",cache:"no-store"}),d=await r.json();if(!d.authenticated){state.innerHTML="Please <a href=\"/login.html\">log in</a> first.";return}h=d.account.avatar.height;b=d.account.avatar.build;s=d.account.avatar.skin;document.getElementById("skin").value=s;function render(){var f=document.getElementById("face");f.style.transform="scale("+(0.82+h*0.06)+","+(0.85+b*0.07)+")";f.style.opacity=String(0.72+s*0.028)}render();document.querySelectorAll("[data-height]").forEach(function(x){x.onclick=function(){h=Number(x.dataset.height);render()}});document.querySelectorAll("[data-build]").forEach(function(x){x.onclick=function(){b=Number(x.dataset.build);render()}});document.getElementById("skin").oninput=function(){s=Number(this.value);render()};document.getElementById("save").onclick=async function(){var rr=await fetch("/api/dreamiez/avatar",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({height:h,build:b,skin:s})});var dd=await rr.json();if(!rr.ok)throw Error(dd.error||"Could not save avatar");state.textContent="Avatar saved."}}catch(e){state.textContent=e.message}})();</script>'));
  write(path.join(OUT,'marketplace.html'),accountShell('Marketplace','<h1>Marketplace</h1><p class="muted">Browse approved products and services, or sign in to submit an offering.</p><div id="items">Loading marketplace...</div><p><a href="/register.html">Create account</a> or <a href="/login.html">log in</a> to submit an offering.</p><script>fetch("/api/marketplace/listings",{credentials:"include",cache:"no-store"}).then(r=>r.json()).then(d=>{var el=document.getElementById("items"),items=d.items||[];el.innerHTML=items.length?items.map(function(x){return "<article style=\"padding:14px 0;border-top:1px solid #ddd\"><strong>"+String(x.title).replace(/[<>]/g,"")+"</strong><p class=\"muted\">"+String(x.description).replace(/[<>]/g,"")+"</p><b>"+String(x.currency)+" "+String(x.price)+"</b></article>"}).join(""):"<p class=\"muted\">No approved listings yet. The marketplace is ready for its first supply.</p>"}).catch(function(){document.getElementById("items").textContent="Marketplace unavailable."});</script>'));
  write(path.join(OUT,'assets.html'),'<main><h1>DreamLedger Assets</h1><p>Approved public commerce assets.</p></main>');
}
function buildSiloCatalogPage(){
  const html=`<!doctype html><html lang="en-NZ"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,follow"><link rel="canonical" href="https://dreamledger.org/"><title>Explore DreamLedger</title><meta name="description" content="Find DreamLedger products, practical tools, and free evidence resources."><style>body{margin:0;background:#f7f5ef;color:#191a17;font:16px/1.65 system-ui,sans-serif}main{max-width:850px;margin:auto;padding:48px 22px}a{color:#4c3cb2}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px}.card{padding:20px;background:#fffdf8;border:1px solid #ddd8cd;border-radius:14px}h1{font-size:clamp(2.8rem,7vw,5rem);line-height:.96;letter-spacing:-.06em}p{color:#5b5a53}</style></head><body><main><p><a href="/">DreamLedger</a></p><h1>Explore DreamLedger</h1><p>Choose the tool or marketplace that fits your task. Free evidence resources are available without an account. Review each product page for current scope, terms, and availability.</p><div class="grid"><article class="card"><h2>Products and services</h2><p>Browse listed products with prices and product details.</p><a href="/shop.html">Browse products →</a></article><article class="card"><h2>Supplier quote comparison</h2><p>Compare 2–5 supplier quotations while keeping missing information visible.</p><a href="/quote-comparison/">View service →</a></article><article class="card"><h2>Free Truth Oracle</h2><p>Check sources, dates, contradictions, and unresolved questions.</p><a href="/truth-oracle.html">Use the free tool →</a></article><article class="card"><h2>Magic: The Gathering</h2><p>Explore cards and decks in the dedicated marketplace.</p><a href="/mtg/">Visit MTG →</a></article></div></main></body></html>`;
  assertClean('silos',html);write(path.join(OUT,'silos.html'),html);
}
const required=[MANIFEST,OFFERS,IP,PRODUCTS,NEWS,AUCTIONS,CATALOG_TEMPLATE,CINEMA_TEMPLATE,DIGITAL_TEMPLATE,BILLBOARDS];
required.forEach(must);fs.mkdirSync(path.join(OUT,'assets'),{recursive:true});
const manifest=json(MANIFEST), offers=json(OFFERS), ip=json(IP), news=json(NEWS), auctions=json(AUCTIONS), billboards=json(BILLBOARDS);
let html=fs.readFileSync(CATALOG_TEMPLATE,'utf8');
html=html.replace('__NEWS_JSON__',JSON.stringify(news).replace(/</g,'\\u003c')).replace('__BILLBOARDS_JSON__',JSON.stringify(billboards).replace(/</g,'\\u003c'));
const accountNav='<a href="/avatar.html" id="dreammee" aria-label="Create avatar" title="Create avatar" style="position:fixed;right:12px;top:10px;z-index:80;width:40px;height:40px;border:2px solid #171512;border-radius:50%;background:linear-gradient(145deg,#fff,#e7dcff);display:grid;place-items:center;font-size:16px">●</a>';
html=html.replace('<header class="nav">',accountNav+'<header class="nav">');
html=html.replace('<a class="btn purple" style="padding:8px 13px;min-height:36px;margin:0" href="#new">Browse</a>','<div style="display:flex;gap:7px;align-items:center"><a class="btn" style="padding:8px 11px;min-height:36px;margin:0" href="/login.html">Log in</a><a class="btn purple" style="padding:8px 13px;min-height:36px;margin:0" href="#new">Browse</a></div>');
assertClean('catalog',html);write(INDEX,html);write(path.join(OUT,'cinema.html'),fs.readFileSync(CINEMA_TEMPLATE,'utf8'));write(path.join(OUT,'digital-products.html'),fs.readFileSync(DIGITAL_TEMPLATE,'utf8'));
assertClean('cinema',fs.readFileSync(path.join(OUT,'cinema.html'),'utf8'));assertClean('digital-products',fs.readFileSync(path.join(OUT,'digital-products.html'),'utf8'));buildAccountPages();
buildSiloCatalogPage();
for(const page of ['login.html','register.html','account.html','avatar.html','marketplace.html','assets.html'])assertClean(page,fs.readFileSync(path.join(OUT,page),'utf8'));
const productCount=fs.readdirSync(PRODUCTS).filter(x=>x.endsWith('.json')).length,capabilityCount=Array.isArray(ip)?ip.length:(ip.capabilities||[]).length,offerCount=Array.isArray(offers)?offers.length:(offers.offers||[]).length,auctionCount=Array.isArray(auctions)?auctions.length:(auctions.auctions||[]).length,newsSilos=Object.keys(news||{}).length,billboardCount=Array.isArray(billboards.boards)?billboards.boards.length:0;
const build={type:'dreamledger-public-surface-compilation',status:'PASS',compiler:'surface-stable-v2',schema:manifest.schema,compiled_at:new Date().toISOString(),source_hashes:{catalog_template:digest(CATALOG_TEMPLATE),cinema_template:digest(CINEMA_TEMPLATE),digital_template:digest(DIGITAL_TEMPLATE),manifest:digest(MANIFEST),offers:digest(OFFERS),ip:digest(IP),news:digest(NEWS),auctions:digest(AUCTIONS),billboards:digest(BILLBOARDS),surface_html:crypto.createHash('sha256').update(html,'utf8').digest('hex')},counts:{capabilities:capabilityCount,offers:offerCount,products:productCount,news_silos:newsSilos,auctions:auctionCount,billboards:billboardCount},public_account_surfaces:['/login.html','/register.html','/account.html','/avatar.html','/marketplace.html','/assets.html'],public_surfaces:manifest.public_surfaces,gates:{approval_required_for_activation:manifest.surface_policy.approval_required_for_activation===true,private_material_excluded:manifest.surface_policy.private_material_excluded===true,silo_isolation_required:manifest.surface_policy.silo_isolation_required===true,forbidden_public_tokens_checked:true,template_compiled:true,cinema_surface_compiled:true,digital_products_surface_compiled:true,primary_account_pages_compiled:true,avatar_editor_compiled:true,marketplace_shell_compiled:true,top_right_account_control_compiled:true}};
write(PROOF,JSON.stringify(build,null,2)+'\n');console.log(JSON.stringify(build,null,2));
