'use strict';
const fs=require('fs');const path=require('path');const crypto=require('crypto');
const ROOT=path.join(__dirname,'..');const JOBS=path.join(ROOT,'data','mtg','edh-jobs');const PRODUCTS=path.join(ROOT,'catalog','products');const PIPELINE='edh-one-link-v1';
const HOSTS=new Set(['manabox.app','www.manabox.app','moxfield.com','www.moxfield.com','archidekt.com','www.archidekt.com','deckstats.net','www.deckstats.net','aetherhub.com','www.aetherhub.com']);
const now=()=>new Date().toISOString();const sha=s=>crypto.createHash('sha256').update(s).digest('hex');
function urlOk(raw){const u=new URL(raw);if(u.protocol!=='https:')throw Error('SOURCE_URL_MUST_BE_HTTPS');if(!HOSTS.has(u.hostname.toLowerCase()))throw Error('UNSUPPORTED_DECK_HOST');return u}
async function getText(u){const r=await fetch(u,{headers:{'user-agent':'DreamLedger-EDH-OneLink/1.0','accept':'text/html,text/plain,application/json'},redirect:'follow'});if(!r.ok)throw Error('SOURCE_HTTP_'+r.status);return await r.text()}
function unescape(s){return s.replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>')}
function parseList(html){const out=new Map();const add=(q,n)=>{n=unescape(String(n).replace(/<[^>]+>/g,' ').replace(/\\s+/g,' ').trim());if(!n||n.length>120)return;if(!/^[A-Za-z0-9][A-Za-z0-9 ,.'’&()\-/:+!?'\u2019]+$/.test(n))return;if(/^card|image|mana|commander$/i.test(n))return;out.set(n,(out.get(n)||0)+Number(q||1));};
for(const m of html.matchAll(/(?:quantity|count|qty)["']?\\s*[:=]\\s*["']?(\\d+)["']?[^}]{0,160}?(?:name|cardName)["']?\\s*[:=]\\s*["']([^"']{2,100})/gi))add(m[1],m[2]);
for(const m of html.matchAll(/<img[^>]+alt=["']([^"']{2,100})["'][^>]*>/gi))add(1,m[1]);
for(const line of html.replace(/<[^>]+>/g,'\\n').split(/\\n+/)){const m=line.trim().match(/^(\\d{1,2})x?\\s+(.{2,100})$/);if(m)add(m[1],m[2]);}
return [...out.entries()].map(([name,quantity])=>({name,quantity}));}
function normalize(cards){return cards.filter(c=>c.quantity>0).sort((a,b)=>a.name.localeCompare(b.name));}
function validate(cards){const total=cards.reduce((n,c)=>n+c.quantity,0);if(total<90)throw Error('INVALID_DECK_TOO_FEW_CARDS');if(total>120)throw Error('INVALID_DECK_TOO_MANY_CARDS');return total;}
function rng(seed){let a=seed>>>0;return()=>{a=(a+0x6D2B79F5)|0;let t=Math.imul(a^(a>>>15),1|a);t=(t+Math.imul(t^(t>>>7),61|t))^t;return((t^(t>>>14))>>>0)/4294967296;};}
function features(cards){const names=cards.flatMap(c=>Array(c.quantity).fill(c.name.toLowerCase()));const has=p=>names.filter(n=>p.test(n)).length;return{cards:names.length,ramp:has(/sol ring|signet|talisman|cultivate|ramp|mana crypt|mana vault|arcane signet/),draw:has(/draw|rhystic study|phyrexian arena|beast whisperer|guardian project|sign in blood|brainstorm/),interaction:has(/counterspell|swords to plowshares|path to exile|beast within|generous gift|removal|terminate|pongify|rapid hybridization/),tutors:has(/tutor|demonic|enlightened|vampiric|worldly/),lands:has(/\b(land|plains|island|swamp|mountain|forest|command tower|shock|fetch|triome)\b/)}};
function benchmark(a,b,seed=20260831,trials=5000){const fa=features(a),fb=features(b),ra=rng(seed);let wins=0;for(let i=0;i<trials;i++){const score=(f)=>f.ramp*.8+f.draw*.7+f.interaction*.45+f.tutors*.6+(f.lands/Math.max(1,f.cards))*20;const sa=score(fa)*(0.75+ra()*.5),sb=score(fb)*(0.75+ra()*.5);if(sa>=sb)wins++;}return{type:'FIXTURE_BENCHMARK',engine:'EDH-HEURISTIC-MONTE-CARLO',version:'1.0.0',seed,trials,turn_horizon:8,win_rate:Number((wins/trials).toFixed(4)),score_summary:{deck_a:fa,deck_b:fb},caveat:'Deterministic heuristic Monte Carlo. Not a rules-accurate Magic simulator.'};}
function primer(deck,benchmarks){const commander=deck.cards.find(c=>/legendary|commander/i.test(c.name))?.name||deck.name;return `# ${deck.name}\n\n## What the deck does\nA Commander deck built around ${commander}.\n\n## Commander and core plan\nUse the normalized list as the source of truth; prioritize the commander and the highest-signal engines identified in the benchmark.\n\n## Early-game priorities\nEstablish mana, deploy card advantage, then hold interaction for the deck's primary axis of play.\n\n## Strengths\nThe benchmark snapshot provides comparative evidence against the selected DreamLedger decks.\n\n## Trade-offs\nThis primer is generated from structured deck data and heuristic simulation, so strategic claims remain bounded by the available evidence.\n\n## Benchmark snapshot\n${benchmarks.map(b=>`- ${b.opponent}: ${Math.round(b.result.win_rate*100)}% estimated win rate (${b.result.type})`).join('\\n')}\n\n## Provenance\nSource: ${deck.source_url}\nSimulation caveat: ${benchmarks[0]?.result.caveat||'No benchmark.'}`;}
async function main(){const args=process.argv.slice(2);const source=args.find(x=>x.startsWith('--url='))?.slice(6)||args.find(x=>x.startsWith('http'));if(!source)throw Error('USAGE: node BEC-PRIME/edh/EDHOneLinkPipeline.js --url=https://manabox.app/decks/... [--compare=ID1,ID2] [--publish-approved]');const compare=(args.find(x=>x.startsWith('--compare='))?.slice(10)||'').split(',').map(x=>x.trim()).filter(Boolean).slice(0,5);const publish=args.includes('--publish-approved');const u=urlOk(source);const raw=await getText(u.href);const sourceHash=sha(raw);const cards=normalize(parseList(raw));const total=validate(cards);const id='EDH-'+sourceHash.slice(0,10).toUpperCase();const job='edh_job_'+sourceHash.slice(0,16);const dir=path.join(JOBS,job);fs.mkdirSync(dir,{recursive:true});const deck={schema_version:'edh-normalized-deck-v1',pipeline:PIPELINE,name:u.pathname.split('/').filter(Boolean).pop()||id,source_url:u.href,source_host:u.hostname,source_retrieved_at:now(),source_content_sha256:sourceHash,cards,total_cards:total};const benches=[];for(const id2 of compare){const f=path.join(PRODUCTS,id2+'.json');if(!fs.existsSync(f))continue;const p=JSON.parse(fs.readFileSync(f,'utf8'));const manifest=p.deck_manifest_file?path.join(ROOT,p.deck_manifest_file):'';if(manifest&&fs.existsSync(manifest)){const d=JSON.parse(fs.readFileSync(manifest,'utf8'));benches.push({opponent:id2,result:benchmark(cards,d.cards)});}else benches.push({opponent:id2,result:{type:'FIXTURE_BENCHMARK',engine:'NO_DECK_MANIFEST',version:'1.0.0',seed:0,trials:0,win_rate:null,caveat:'Comparison product has no normalized deck manifest yet.'}});}
const primerText=primer({...deck,name:deck.name},benches);const heroPrompt=`Premium product hero for a Commander deck named ${deck.name}. Commander/deck identity only from supplied card list. Show selected cards as recognizable tabletop objects, cinematic lighting, premium collector photography, no official Magic logo, no invented card text, no claim of official artwork.`;const product={id,silo:'mtg',name:deck.name+' Commander Deck',description:'Generated Commander deck product with normalized deck manifest, benchmark snapshot, primer and hero-media prompt.',price:0,price_unit:'minor',currency:'nzd',inventory:1,inventory_type:'physical',status:publish?'published':'draft',checkout_available:false,commercial_truth:{approval_required:true,sellable:false,activation_gate:'EXPLICIT_OPERATOR_APPROVAL'},edh_pipeline:{pipeline_version:PIPELINE,source_url:deck.source_url,deck_manifest_file:path.relative(ROOT,path.join(dir,'deck.json')).replace(/\\/g,'/'),primer_file:path.relative(ROOT,path.join(dir,'primer.md')).replace(/\\/g,'/'),benchmark_file:path.relative(ROOT,path.join(dir,'benchmark.json')).replace(/\\/g,'/'),hero_prompt_file:path.relative(ROOT,path.join(dir,'hero-prompt.txt')).replace(/\\/g,'/'),media_status:'PROMPT_READY',cinema_sku:benches.length?'CINEMA-'+id:null},created_at:now()};fs.writeFileSync(path.join(dir,'deck.json'),JSON.stringify(deck,null,2)+'\\n');fs.writeFileSync(path.join(dir,'benchmark.json'),JSON.stringify({schema_version:'edh-benchmark-manifest-v1',comparisons:benches},null,2)+'\\n');fs.writeFileSync(path.join(dir,'primer.md'),primerText+'\\n');fs.writeFileSync(path.join(dir,'hero-prompt.txt'),heroPrompt+'\\n');fs.writeFileSync(path.join(PRODUCTS,id+'.json'),JSON.stringify(product,null,2)+'\\n');const proof={schema_version:'edh-one-link-proof-v1',job_id:job,product_id:id,state:publish?'PUBLISHED':'CATALOGUE_READY_DRAFT',source_url:deck.source_url,source_sha256:sourceHash,normalized_deck_sha256:sha(JSON.stringify(deck)),comparison_ids:compare,benchmark_type:'FIXTURE_BENCHMARK',primer_sha256:sha(primerText),hero_prompt_sha256:sha(heroPrompt),media_status:'PROMPT_READY',generated_at:now(),approval_required:true};fs.writeFileSync(path.join(dir,'PROOF.json'),JSON.stringify(proof,null,2)+'\\n');console.log(JSON.stringify(proof,null,2));}
main().catch(e=>{console.error(JSON.stringify({status:'FAIL',error:e.message},null,2));process.exit(1);});
