'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto'),QRCode=require('qrcode');
const ROOT=path.join(__dirname,'..'),STORE=path.resolve(process.env.QR_DATA_DIR||path.join(ROOT,'data','qr')),CODES=path.join(STORE,'codes'),SCANS=path.join(STORE,'scans');
const API_KEY=process.env.QR_API_KEY||'',SALT=process.env.QR_IP_SALT||process.env.SECRET_KEY||'',BASE=(process.env.QR_BASE_URL||'https://qr.dreamledger.org').replace(/\/$/,'');
const HOSTS=new Set(String(process.env.QR_ALLOWED_HOSTS||'dreamledger.org,qr.dreamledger.org').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean));
const QR_HOST=new URL(BASE).hostname.toLowerCase();
fs.mkdirSync(CODES,{recursive:true});fs.mkdirSync(SCANS,{recursive:true});
function json(res,s,v){res.writeHead(s,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(v));}
function auth(req){return Boolean(API_KEY)&&req.headers.authorization===`Bearer ${API_KEY}`}
function readBody(req){return new Promise((ok,bad)=>{let s='';req.on('data',c=>{s+=c;if(s.length>1000000)req.destroy()});req.on('end',()=>{try{ok(s?JSON.parse(s):{})}catch(e){bad(e)}});req.on('error',bad)})}
function validUrl(v){try{const u=new URL(String(v));return u.protocol==='https:'&&HOSTS.has(u.hostname.toLowerCase())}catch{return false}}
function code(){return crypto.randomBytes(6).toString('base64url').replace(/[^A-Za-z0-9]/g,'').slice(0,8)}
function qfile(id){return path.join(CODES,`${id}.json`)}function sfile(id){return path.join(SCANS,`${id}.jsonl`)}
function get(id){return JSON.parse(fs.readFileSync(qfile(id),'utf8'))}
function all(){return fs.readdirSync(CODES).filter(x=>x.endsWith('.json')).map(x=>{try{return JSON.parse(fs.readFileSync(path.join(CODES,x),'utf8'))}catch{return null}}).filter(Boolean)}
function hashIp(ip){return crypto.createHash('sha256').update(`${SALT}:${ip||'unknown'}`).digest('hex')}
function device(ua){const x=String(ua||'').toLowerCase();return /ipad|tablet|android(?!.*mobile)/.test(x)?'tablet':/mobile|iphone|ipod|android/.test(x)?'mobile':'desktop'}
function count(id){const f=sfile(id);return fs.existsSync(f)?fs.readFileSync(f,'utf8').split('\n').filter(Boolean).length:0}
function choose(q,req){if(q.status!=='active')return null;if(q.rules?.expires_at&&Date.parse(q.rules.expires_at)<=Date.now())return null;if(Number.isFinite(q.rules?.scan_limit)&&count(q.id)>=Number(q.rules.scan_limit))return null;const country=String(req.headers['cf-ipcountry']||req.headers['x-country']||'').toUpperCase(),lang=String(req.headers['accept-language']||'').split(',')[0].split('-')[0].toLowerCase(),dev=device(req.headers['user-agent']);const g=q.rules?.geo_redirects?.find(x=>x.country?.toUpperCase()===country&&validUrl(x.url)),l=q.rules?.language_redirects?.find(x=>x.lang?.toLowerCase()===lang&&validUrl(x.url)),d=q.rules?.device_redirects?.find(x=>x.device?.toLowerCase()===dev&&validUrl(x.url));return g?{url:g.url,reason:'geo'}:l?{url:l.url,reason:'language'}:d?{url:d.url,reason:'device'}:{url:q.destination_url,reason:'default'}}
function log(q,req,r){const ip=String(req.headers['x-forwarded-for']||req.socket.remoteAddress||'').split(',')[0].trim();const row={scan_time:new Date().toISOString(),ip_hash:hashIp(ip),country:String(req.headers['cf-ipcountry']||req.headers['x-country']||'').toUpperCase()||null,city:String(req.headers['x-city']||'')||null,device:device(req.headers['user-agent']),browser_language:String(req.headers['accept-language']||'').split(',')[0]||null,redirect_url:r.url,redirect_reason:r.reason};fs.appendFileSync(sfile(q.id),JSON.stringify(row)+'\n')}
function analytics(id){const f=sfile(id);if(!fs.existsSync(f))return {total_scans:0,unique_scans:0,scans_by_country:[],scans_by_device:[],scans_by_date:[],scans_by_language:[]};const rows=fs.readFileSync(f,'utf8').split('\n').filter(Boolean).map(JSON.parse),unique=new Set(rows.map(x=>x.ip_hash));const group=k=>{const m={};rows.forEach(r=>{const v=r[k]||'unknown';m[v]=(m[v]||0)+1});return Object.entries(m).map(([value,n])=>({[k]:value,count:n})).sort((a,b)=>b.count-a.count)};const dates={};rows.forEach(r=>{const d=r.scan_time.slice(0,10);dates[d]=(dates[d]||0)+1});return {total_scans:rows.length,unique_scans:unique.size,scans_by_country:group('country'),scans_by_device:group('device'),scans_by_date:Object.entries(dates).map(([date,n])=>({date,count:n})),scans_by_language:group('browser_language')}}
async function create(req,res){if(!auth(req))return json(res,401,{error:'Unauthorized'});try{const b=await readBody(req);if(!validUrl(b.destination))return json(res,422,{error:'Destination host is not allowed'});let c=code();while(all().some(q=>q.short_code===c))c=code();const q={id:`qr_${crypto.randomBytes(10).toString('base64url')}`,short_code:c,type:String(b.type||'url'),title:String(b.title||c),destination_url:String(b.destination),design:b.design||{},rules:b.rules||{},metadata:b.metadata||{},translate:b.translate||{enabled:false,target_languages:[]},status:'active',created_at:new Date().toISOString(),updated_at:new Date().toISOString()};fs.writeFileSync(qfile(q.id),JSON.stringify(q,null,2)+'\n');const url=`${BASE}/${c}`;return json(res,201,{id:q.id,short_code:c,short_url:url,png_data_url:await QRCode.toDataURL(url,{width:512,margin:2}),svg:await QRCode.toString(url,{type:'svg',width:512,margin:2}),created_at:q.created_at})}catch(e){return json(res,422,{error:e.message})}}
async function update(req,res,id){if(!auth(req))return json(res,401,{error:'Unauthorized'});try{const q=get(id),b=await readBody(req);if(b.destination!==undefined){if(!validUrl(b.destination))return json(res,422,{error:'Destination host is not allowed'});q.destination_url=String(b.destination)}for(const k of ['title','type','design','rules','metadata','translate','status'])if(b[k]!==undefined)q[k]=b[k];q.updated_at=new Date().toISOString();fs.writeFileSync(qfile(id),JSON.stringify(q,null,2)+'\n');return json(res,200,{ok:true,id,updated_at:q.updated_at})}catch(e){return json(res,404,{error:e.message})}}
async function handle(req,res,url){const host=String(req.headers.host||'').split(':')[0].toLowerCase();if(url==='/api/qr/create'&&req.method==='POST'){await create(req,res);return true}let m=url.match(/^\/api\/qr\/([^/]+)$/);if(m&&req.method==='PUT'){await update(req,res,decodeURIComponent(m[1]));return true}m=url.match(/^\/api\/qr\/([^/]+)\/analytics$/);if(m&&req.method==='GET'){if(!auth(req))return json(res,401,{error:'Unauthorized'}),true;try{return json(res,200,analytics(decodeURIComponent(m[1]))),true}catch(e){return json(res,404,{error:e.message}),true}}if(url==='/api/qr'&&req.method==='GET'){if(!auth(req))return json(res,401,{error:'Unauthorized'});return json(res,200,{codes:all().map(q=>({id:q.id,short_code:q.short_code,title:q.title,status:q.status,created_at:q.created_at,total_scans:count(q.id)}))}),true}m=url.match(/^\/qr\/([^/]+)$/);if(m&&req.method==='GET'){try{const q=all().find(x=>x.short_code===decodeURIComponent(m[1]));if(!q)return json(res,404,{error:'QR not found'}),true;const r=choose(q,req);if(!r)return json(res,410,{error:'QR inactive or expired'}),true;log(q,req,r);res.writeHead(302,{Location:r.url,'Cache-Control':'no-store'});res.end();return true}catch(e){return json(res,500,{error:'QR redirect failed'}),true}}if(host===QR_HOST&&url!=='/'&&req.method==='GET'&&!url.startsWith('/api/')){const shortCode=decodeURIComponent(url.slice(1));if(/^[A-Za-z0-9]{3,32}$/.test(shortCode)){try{const q=all().find(x=>x.short_code===shortCode);if(!q)return json(res,404,{error:'QR not found'}),true;const r=choose(q,req);if(!r)return json(res,410,{error:'QR inactive or expired'}),true;log(q,req,r);res.writeHead(302,{Location:r.url,'Cache-Control':'no-store'});res.end();return true}catch(e){return json(res,500,{error:'QR redirect failed'}),true}}}return false}
module.exports={handle};
