'use strict';
const crypto=require('crypto');
const RAIL_SCHEMA='BECK-BRIDGE-RAIL-1.0';
const LEASE_TTL_SECONDS=900;
function config(){const url=String(process.env.SUPABASE_URL||'').replace(/\/$/,'');const token=String(process.env.DREAMLEDGER_AGENT_BRIDGE_TOKEN||'');const proxy=String(process.env.AGENT_BRIDGE_PROXY_URL||`${url}/functions/v1/agent-bridge-proxy`).replace(/\/$/,'');return {url,token,proxy,signingSecret:String(process.env.BECK_BRIDGE_SIGNING_SECRET||token)};}
function configured(){const c=config();return Boolean(c.url&&c.token&&c.proxy&&c.signingSecret);}
function authorized(req){const c=config();return configured()&&String(req.headers['x-dreamledger-agent-token']||'')===c.token;}
async function readJson(req){let body='';for await(const chunk of req){body+=chunk;if(body.length>200000)throw Object.assign(new Error('Request too large'),{statusCode:413});}try{return JSON.parse(body||'{}')}catch{throw Object.assign(new Error('Invalid JSON'),{statusCode:400})}}
async function supabase(path,options={}){const c=config();const method=String(options.method||'GET').toUpperCase();const r=await fetch(c.proxy,{method:'POST',headers:{'Content-Type':'application/json','x-dreamledger-agent-token':c.token},body:JSON.stringify({path,method,prefer:options.prefer||'return=representation',body:method==='GET'?undefined:JSON.parse(options.body||'{}')})});const text=await r.text();let data;try{data=JSON.parse(text||'null')}catch{data={raw:text}}if(!r.ok)throw Object.assign(new Error(data&&data.error?data.error:`Supabase rail proxy failed (${r.status})`),{statusCode:r.status});return data;}
function canonicalEnvelope(e){return JSON.stringify({schema_version:e.schema_version,lease_id:e.lease_id,job_id:e.job_id,worker_id:e.worker_id,issued_at:e.issued_at,expires_at:e.expires_at,objective:e.objective,silo_id:e.silo_id});}
function sign(e){return crypto.createHmac('sha256',config().signingSecret).update(canonicalEnvelope(e)).digest('hex');}
function verify(e,s){const expected=sign(e),a=Buffer.from(String(s||''),'utf8'),b=Buffer.from(expected,'utf8');return a.length===b.length&&crypto.timingSafeEqual(a,b);}
function send(res,status,body){if(res.writableEnded)return true;res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(body===null?'':JSON.stringify(body));return true;}
async function durableNote(from,to,subject,payload,correlationId,lane='execution'){const row={from_agent:from,to_agent:to,note_type:'HANDOFF',subject,body:JSON.stringify(payload),requires_response:false,correlation_id:correlationId,lane,priority:90,silo_id:payload.silo_id||'SILO_GENERAL',source_system:'beck-bridge-rail'};const created=await supabase('control_bridge_notes',{method:'POST',body:JSON.stringify(row)});return Array.isArray(created)?created[0]:created;}
async function leaseJob(workerId){const jobs=await supabase('jobs?select=id,type,status,attempt_count,payload,created_at&status=eq.pending&order=created_at.asc&limit=1');if(!Array.isArray(jobs)||!jobs.length)return null;const job=jobs[0],now=new Date(),expires=new Date(now.getTime()+LEASE_TTL_SECONDS*1000),leaseId=`LEASE_${crypto.randomUUID()}`,payload=job.payload&&typeof job.payload==='object'?job.payload:{};const envelope={schema_version:RAIL_SCHEMA,lease_id:leaseId,job_id:job.id,worker_id:String(workerId),issued_at:now.toISOString(),expires_at:expires.toISOString(),objective:String(payload.mission||payload.objective||job.type||'worker task'),silo_id:String(payload.silo_id||'SILO_GENERAL')};const signature=sign(envelope);const updated=await supabase(`jobs?id=eq.${encodeURIComponent(job.id)}&status=eq.pending`,{method:'PATCH',body:JSON.stringify({status:'leased',worker_id:String(workerId),started_at:now.toISOString(),leased_until:expires.toISOString(),attempt_count:Number(job.attempt_count||0)+1})});if(!Array.isArray(updated)||!updated.length)return null;await durableNote('system',String(workerId),`BRIDGE_LEASE:${leaseId}`,{rail_schema:RAIL_SCHEMA,stage:'LEASE_ISSUED',...envelope,signature},leaseId);return {envelope,signature,job:updated[0]};}
async function recordStage(input){const e=input&&input.envelope,sig=String(input&&input.signature||''),worker=String(input&&input.worker_id||'').trim(),actor=String(input&&input.actor_id||worker).trim().toLowerCase(),stage=String(input&&input.stage||'').trim().toUpperCase();if(!e||!verify(e,sig))throw Object.assign(new Error('Invalid bridge lease signature'),{statusCode:403});if(String(e.worker_id)!==worker)throw Object.assign(new Error('Worker identity does not match signed lease'),{statusCode:403});if(Date.parse(e.expires_at)<Date.now())throw Object.assign(new Error('Bridge lease expired'),{statusCode:409});if(!['WORKER_A_RESULT','WORKER_B_RESULT'].includes(stage))throw Object.assign(new Error('stage must be WORKER_A_RESULT or WORKER_B_RESULT'),{statusCode:400});if(stage==='WORKER_A_RESULT'&&actor!==worker)throw Object.assign(new Error('Worker A actor must match the leased worker'),{statusCode:403});if(stage==='WORKER_B_RESULT'&&actor===worker)throw Object.assign(new Error('Worker B requires an independent verifier actor'),{statusCode:403});const resultHash=crypto.createHash('sha256').update(JSON.stringify(input.result||{})).digest('hex'),payload={rail_schema:RAIL_SCHEMA,stage,lease_id:e.lease_id,job_id:e.job_id,worker_id:worker,actor_id:actor,parent_signature:sig,result_hash:resultHash,result:input.result||{},recorded_at:new Date().toISOString()};const note=await durableNote(actor,stage==='WORKER_A_RESULT'?'system':'truth_oracle',`BRIDGE_STAGE:${e.lease_id}:${stage}`,payload,e.lease_id);if(stage==='WORKER_B_RESULT'){await supabase(`jobs?id=eq.${encodeURIComponent(e.job_id)}&status=eq.leased`,{method:'PATCH',body:JSON.stringify({status:'completed',completed_at:new Date().toISOString(),last_error:null})});await durableNote('system','truth_oracle',`BRIDGE_PROOF:${e.lease_id}`,{rail_schema:RAIL_SCHEMA,status:'BRIDGE_PROVEN_CANDIDATE',lease_id:e.lease_id,job_id:e.job_id,worker_a_and_b_observed:true,independent_verifier:actor,worker_b_result_hash:resultHash,sealed_at:new Date().toISOString()},e.lease_id,'reconciliation');}return {rail_schema:RAIL_SCHEMA,accepted:true,stage,lease_id:e.lease_id,job_id:e.job_id,actor_id:actor,result_hash:resultHash,note_id:note&&note.note_id};}
async function handle(req,res){const path=String(req.url||'').split('?')[0];if(!path.startsWith('/api/agent-bridge/rail'))return false;if(!configured())return send(res,503,{error:'Bridge rail is not configured'});if(!authorized(req))return send(res,401,{error:'Bridge rail authentication required'});try{if(req.method==='GET'&&path==='/api/agent-bridge/rail/manifest')return send(res,200,{schema_version:RAIL_SCHEMA,status:'ARMED',authentication:'x-dreamledger-agent-token',runtime_authority:'signed HMAC lease envelope',durable_store:'Supabase jobs + control_bridge_notes',lease_ttl_seconds:LEASE_TTL_SECONDS,stages:['LEASE_ISSUED','WORKER_A_RESULT','WORKER_B_RESULT','BRIDGE_PROVEN_CANDIDATE'],irreversible_effects:false});if(req.method==='POST'&&path==='/api/agent-bridge/rail/lease'){const i=await readJson(req),worker=String(i.worker_id||'').trim().toLowerCase();if(!worker||!/^[a-z0-9_-]{2,64}$/.test(worker))return send(res,400,{error:'Valid worker_id required'});const lease=await leaseJob(worker);if(!lease){res.statusCode=204;res.end();return true;}return send(res,201,lease);}if(req.method==='POST'&&path==='/api/agent-bridge/rail/stage')return send(res,201,await recordStage(await readJson(req)));return send(res,404,{error:'Bridge rail route not found'});}catch(err){return send(res,err.statusCode||500,{error:err.message||'Bridge rail failure'});}}
module.exports={handle,configured,sign,verify,RAIL_SCHEMA};
