'use strict';
const workerPool=require('./worker-pool');
const DEFAULT_BRIDGE_URL=process.env.BEC_AGENT_BRIDGE_URL||process.env.AGENT_BRIDGE_URL||'http://127.0.0.1:3000';
const DEFAULT_RAIL_PATH='/api/agent-bridge/rail/lease';
const DEFAULT_STAGE_PATH='/api/agent-bridge/rail/stage';
const JOB_KIND_MAP=new Map([['analysis','analysis'],['code_change','code_change'],['gauntlet','gauntlet'],['compile','compile'],['test','test'],['lm_refinement','lm_refinement'],['revenue_prospecting','analysis']]);
function requiredString(v,f){const t=String(v==null?'':v).trim();if(!t)throw new Error(`${f} is required`);return t;}
function normalizeKind(v){return JOB_KIND_MAP.get(String(v||'').trim().toLowerCase())||'analysis';}
function toWorkerJob(j){if(!j||typeof j!=='object')throw new Error('job envelope is required');const objective=requiredString(j.objective,'objective'),jobId=requiredString(j.job_id,'job_id'),silo=String(j.silo||'BEC-ECONOMIC').trim()||'BEC-ECONOMIC',offerIds=Array.isArray(j.offer_ids)?j.offer_ids.filter(Boolean).map(String):[],evidenceRequirements=j.required_evidence||{},effects=Array.isArray(j.effects)?j.effects:[];return {job_id:`bridge_${jobId}`,kind:normalizeKind(j.job_type),silo,task:objective,inputs:{bridge_job_id:jobId,source:j.source||'agent-bridge-rail',candidate_id:j.candidate_id||null,offer_ids:offerIds,evidence_requirements:evidenceRequirements,existing_evidence:j.existing_evidence||null,approval_gate:j.approval_gate||null,next_permitted_action:j.next_permitted_action||null},effects,approval_required:true,public_action_allowed:false,worker_preference:j.worker_preference||'auto'};}
async function postStage(lease,result,options={}){const f=options.fetchImpl||globalThis.fetch,b=String(options.baseUrl||DEFAULT_BRIDGE_URL).replace(/\/$/,''),token=String(options.token||process.env.DREAMLEDGER_AGENT_BRIDGE_TOKEN||''),wid=String(lease.envelope.worker_id||'').trim().toLowerCase(),r=await f(`${b}${options.stagePath||DEFAULT_STAGE_PATH}`,{method:'POST',headers:{'x-dreamledger-agent-token':token,Accept:'application/json','Content-Type':'application/json'},body:JSON.stringify({envelope:lease.envelope,signature:lease.signature,worker_id:wid,actor_id:wid,stage:'WORKER_A_RESULT',result})}),t=await r.text();let body=null;try{body=JSON.parse(t||'null')}catch{throw new Error(`Bridge stage returned invalid JSON (${r.status})`)}if(!r.ok)throw new Error(body&&body.error?body.error:`Bridge stage failed (${r.status})`);return body;}
async function leaseNextJob(options={}){const f=options.fetchImpl||globalThis.fetch;if(typeof f!=='function')throw new Error('fetch is not available');const b=String(options.baseUrl||DEFAULT_BRIDGE_URL).replace(/\/$/,''),token=String(options.token||process.env.DREAMLEDGER_AGENT_BRIDGE_TOKEN||''),wid=String(options.workerId||process.env.BEC_WORKER_ID||'').trim().toLowerCase();if(!token)throw new Error('DREAMLEDGER_AGENT_BRIDGE_TOKEN is required');if(!wid||!/^[a-z0-9_-]{2,64}$/.test(wid))throw new Error('BEC_WORKER_ID must match ^[a-z0-9_-]{2,64}$');const r=await f(`${b}${options.path||DEFAULT_RAIL_PATH}`,{method:'POST',headers:{'x-dreamledger-agent-token':token,Accept:'application/json','Content-Type':'application/json'},body:JSON.stringify({worker_id:wid})}),t=await r.text();let body=null;try{body=JSON.parse(t||'null')}catch{throw new Error(`Bridge rail returned invalid JSON (${r.status})`)}if(r.status===204)return null;if(!r.ok)throw new Error(body&&body.error?body.error:`Bridge rail request failed (${r.status})`);const schema=body&&(body.rail_schema||body.envelope?.schema_version);if(!body||schema!=='BECK-BRIDGE-RAIL-1.0'||!body.envelope||!body.signature)throw new Error(`Bridge rail returned invalid lease envelope: keys=${body?Object.keys(body).join(','):''}`);if(!body.job){const jr=await f(`${b}/api/agent-bridge/jobs?status=leased&limit=50`,{headers:{'x-dreamledger-agent-token':token,Accept:'application/json'}}),jt=await jr.text();let jb=null;try{jb=JSON.parse(jt||'null')}catch{}const found=Array.isArray(jb&&jb.jobs)?jb.jobs.find(j=>String(j.job_id)===String(body.envelope.job_id)):null;if(found)body.job={id:body.envelope.job_id,type:found.job_type,payload:{mission:found.objective,objective:found.objective,approval_gate:found.approval_gate,next_permitted_action:found.next_permitted_action,offer_ids:found.offer_ids||[]}};}if(!body.job)throw new Error(`Bridge rail lease missing job record for ${body.envelope.job_id}`);return body;}
async function adaptJob(j,options={}){const pool=options.workerPool||workerPool;if(!pool||typeof pool.createJob!=='function'||typeof pool.execute!=='function')throw new Error('worker pool must expose createJob() and execute()');const w=toWorkerJob(j),created=await pool.createJob(w),id=typeof created==='string'?created:created&&created.job_id;if(!id)throw new Error('worker pool did not return a job id');const execution=await pool.execute(id),result=execution&&execution.result?execution.result:null,proof=execution&&execution.proof?execution.proof:null;return {schema_version:'BECK-ECONOMIC-WORKER-RESULT-1.0',source_job_id:j.job_id,worker_job_id:id,status:execution&&execution.job?execution.job.status:(result&&result.status)||'UNKNOWN',artifacts:result&&result.output?result.output:null,proof_ref:proof?(proof.proof_hash||proof.proof_id||null):null,evidence_claims:result&&result.evidence_claims?result.evidence_claims:{payment_claim:false,sale_claim:false,fulfillment_claim:false},irreversible_effects_triggered:false};}
async function runNext(options={}){const lease=await leaseNextJob(options);if(!lease)return {status:'IDLE'};const smoke=String(lease.envelope.objective||'')==='BRIDGE_HTTP_SMOKE_TEST';const workerPreference=lease.job.payload?.worker_preference||(smoke?'deterministic':'auto');const result=await adaptJob({job_id:lease.envelope.job_id,job_type:lease.job.type,objective:lease.envelope.objective,silo:lease.envelope.silo_id,source:'agent-bridge-rail',payload:lease.job.payload||{},offer_ids:lease.job.payload?.offer_ids||[],approval_gate:lease.job.payload?.approval_gate||null,next_permitted_action:lease.job.payload?.next_permitted_action||null,worker_preference:workerPreference},options),stageA=await postStage(lease,result,options);return {status:'LEASED_AND_EXECUTED',lease,result,stage_a:stageA};}
module.exports={leaseNextJob,toWorkerJob,adaptJob,postStage,runNext};
if(require.main===module)runNext().then(r=>console.log(JSON.stringify(r,null,2))).catch(e=>{console.error(e.message);process.exitCode=1;});
