'use strict';

const STATES = Object.freeze([
  'PAYMENT_RECEIVED',
  'PAYMENT_REJECTED',
  'ORDER_CREATED',
  'ORDER_CANCELLED',
  'INPUT_VALIDATED',
  'INPUT_INVALID',
  'JOB_AUTHORIZED',
  'AUTHORIZATION_DENIED',
  'JOB_EXECUTED',
  'JOB_FAILED',
  'OUTPUT_VERIFIED',
  'OUTPUT_INVALID',
  'FULFILMENT_CREATED',
  'FULFILMENT_FAILED',
  'DELIVERY_PENDING',
  'DELIVERY_FAILED',
  'DELIVERED',
  'RECONCILIATION_PENDING',
  'RECONCILIATION_FAILED',
  'RECONCILED',
  'PROOF_FINALIZED',
  'REFUND_PENDING',
  'REFUNDED',
  'REFUND_FAILED',
  'QUARANTINED',
  'MANUAL_REVIEW'
]);

const TRANSITIONS = Object.freeze({
  PAYMENT_RECEIVED: ['ORDER_CREATED', 'PAYMENT_REJECTED'],
  ORDER_CREATED: ['INPUT_VALIDATED', 'ORDER_CANCELLED'],
  INPUT_VALIDATED: ['JOB_AUTHORIZED'],
  INPUT_INVALID: ['INPUT_VALIDATED', 'QUARANTINED'],
  JOB_AUTHORIZED: ['JOB_EXECUTED', 'AUTHORIZATION_DENIED'],
  JOB_EXECUTED: ['OUTPUT_VERIFIED', 'JOB_FAILED'],
  JOB_FAILED: ['JOB_AUTHORIZED', 'QUARANTINED'],
  OUTPUT_VERIFIED: ['FULFILMENT_CREATED'],
  OUTPUT_INVALID: ['OUTPUT_VERIFIED', 'QUARANTINED'],
  FULFILMENT_CREATED: ['DELIVERY_PENDING', 'FULFILMENT_FAILED'],
  FULFILMENT_FAILED: ['FULFILMENT_CREATED', 'QUARANTINED'],
  DELIVERY_PENDING: ['DELIVERED', 'DELIVERY_FAILED'],
  DELIVERY_FAILED: ['DELIVERY_PENDING', 'QUARANTINED'],
  DELIVERED: ['RECONCILIATION_PENDING'],
  RECONCILIATION_PENDING: ['RECONCILED', 'RECONCILIATION_FAILED'],
  RECONCILIATION_FAILED: ['RECONCILIATION_PENDING', 'MANUAL_REVIEW'],
  RECONCILED: ['PROOF_FINALIZED', 'REFUND_PENDING'],
  REFUND_PENDING: ['REFUNDED', 'REFUND_FAILED'],
  REFUND_FAILED: ['REFUND_PENDING', 'MANUAL_REVIEW']
});

const TERMINAL = new Set(['PAYMENT_REJECTED', 'ORDER_CANCELLED', 'AUTHORIZATION_DENIED', 'PROOF_FINALIZED', 'REFUNDED', 'QUARANTINED', 'MANUAL_REVIEW']);
const RETRYABLE = new Set(['INPUT_INVALID', 'JOB_FAILED', 'OUTPUT_INVALID', 'FULFILMENT_FAILED', 'DELIVERY_FAILED', 'RECONCILIATION_FAILED', 'REFUND_FAILED']);

function assertState(state) {
  if (!STATES.includes(state)) throw new Error('UNKNOWN_STATE:' + state);
}

function canTransition(from, to) {
  assertState(from);
  assertState(to);
  return Array.isArray(TRANSITIONS[from]) && TRANSITIONS[from].includes(to);
}

function assertTransition(from, to) {
  if (!canTransition(from, to)) throw new Error('ILLEGAL_TRANSITION:' + from + '->' + to);
}

module.exports = { STATES, TRANSITIONS, TERMINAL, RETRYABLE, canTransition, assertTransition };
