services:
  - type: web
    name: dreamledger
    runtime: node
    rootDir: BEC-PRIME
    buildCommand: mkdir -p compiled/website && cp -rf cubes/*/outputs/website/*/* compiled/website/
    startCommand: node server.js
