'use strict';

// Minimal UCP adapter. Commercial truth remains in the canonical catalogs.
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const VERSION = process.env.UCP_VERSION || '2026-01-11';
const BASE = (process.env.PUBLIC_BASE_URL || 'https://dreamledger.org').replace(/\/$/, '');
const ROOT = __dirname;
const OFFER_CATALOG = path.join(ROOT, 'catalog', 'offers', 'offers.json');
const PRODUCT_CATALOG = path.join(ROOT, 'catalog', 'products');
const sessions = new Map();
const CAP_CHECKOUT = { name:'dev.ucp.shopping.checkout', version:VERSION, spec:`https://ucp.dev/${VERSION}/specification/checkout`, schema:`https://ucp.dev/${VERSION}/schemas/shopping/checkout.json` };
function json(file){return JSON.parse(fs.readFileSync(file,'utf8'));}
function offers(){return json(OFFER_CATALOG).offers||[];}
function products(){if(!fs.existsSync(PRODUCT_CATALOG))return [];return fs.readdirSync(PRODUCT_CATALOG).filter(x=>x.endsWith('.json')).map(x=>json(path.join(PRODUCT_CATALOG,x)));}
function findItem(id){const o=offers().find(x=>x.offer_id===id);if(o)return{kind:'offer',id:o.offer_id,silo:o.silo,name:o.name,description:o.output,price:o.price,currency:o.currency,approval_required:o.approval_required!==false,checkout_available:o.checkout_available===true};const p=products().find(x=>x.id===id);if(p)return{kind:'product',id:p.id,silo:p.silo,name:p.name,description:p.description,price:Number(p.price)/100,currency:p.currency,approval_required:Boolean(p.commercial_truth?.approval_required),checkout_available:p.status==='published'&&!p.commercial_truth?.approval_required&&Number(p.inventory)>0};return null;}
function profile(){return{ucp:{version:VERSION,services:{'dev.ucp.shopping':{version:VERSION,spec:`https://ucp.dev/${VERSION}/specification/overview`,rest:{schema:`https://ucp.dev/${VERSION}/services/shopping/openapi.json`,endpoint:`${BASE}/ucp/v1`}}},capabilities:[CAP_CHECKOUT]}};}
function responseMeta(){return{version:VERSION,capabilities:[CAP_CHECKOUT]};}
function totals(item){const minor=Math.round(Number(item.price)*100);return[{type:'subtotal',amount:minor},{type:'total',amount:minor}];}
function links(){return[{type:'privacy_policy',url:`${BASE}/legal/privacy`},{type:'terms_of_service',url:`${BASE}/legal/terms`}];}
function checkoutResponse(s){return{ucp:responseMeta(),id:s.id,line_items:s.line_items,status:s.status,currency:s.currency,totals:s.totals,messages:s.messages||[],links:links(),expires_at:s.expires_at,continue_url:s.continue_url,payment:{handlers:[]}};}
function body(req){return new Promise((resolve,reject)=>{let raw='';req.on('data',c=>{raw+=c;if(raw.length>1000000)req.destroy(new Error('Request too large'));});req.on('end',()=>{try{resolve(JSON.parse(raw||'{}'));}catch(e){reject(e);}});req.on('error',reject);});}
function send(res,status,value){if(res.headersSent)return;res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(value));}
async function handle(req,res){const url=String(req.url||'').split('?')[0];if(req.method==='GET'&&url==='/.well-known/ucp')return send(res,200,profile());if(!url.startsWith('/ucp/v1/'))return false;if(!req.headers['ucp-agent']&&req.method!=='OPTIONS')return send(res,400,{ucp:{version:VERSION},messages:[{type:'error',code:'missing_ucp_agent',severity:'unrecoverable',content:'UCP-Agent profile is required.'}]});
if(req.method==='POST'&&url==='/ucp/v1/checkout-sessions'){let input;try{input=await body(req);}catch{return send(res,400,{error:'Invalid JSON'});}const line=Array.isArray(input.line_items)?input.line_items[0]:null;const itemId=line?.item_id||line?.product_id||line?.offer_id||line?.id;const item=itemId?findItem(itemId):null;if(!item)return send(res,404,{ucp:{version:VERSION},messages:[{type:'error',code:'item_not_found',severity:'unrecoverable',content:'Requested item was not found.'}]});if(input.currency&&String(input.currency).toUpperCase()!==String(item.currency).toUpperCase())return send(res,422,{ucp:{version:VERSION},messages:[{type:'error',code:'currency_mismatch',severity:'unrecoverable',content:'Requested currency does not match merchant truth.'}]});const id=`ucp_${crypto.randomUUID()}`;const s={id,status:item.checkout_available?'ready_for_complete':'requires_escalation',currency:String(item.currency).toUpperCase(),line_items:[{id:item.id,quantity:1,title:item.name,price:Math.round(item.price*100)}],totals:totals(item),expires_at:new Date(Date.now()+21600000).toISOString(),continue_url:`${BASE}/?ucp_checkout=${encodeURIComponent(id)}`,messages:item.checkout_available?[]:[{type:'error',code:'approval_required',severity:'requires_buyer_input',content:'This offer is not activated for checkout.'}],item};sessions.set(id,s);return send(res,201,checkoutResponse(s));}
const match=url.match(/^\/ucp\/v1\/checkout-sessions\/([^/]+)$/);if(match){const s=sessions.get(decodeURIComponent(match[1]));if(!s)return send(res,404,{ucp:{version:VERSION},messages:[{type:'error',code:'checkout_not_found',severity:'unrecoverable',content:'Checkout session not found.'}]});if(req.method==='GET'||req.method==='PATCH')return send(res,200,checkoutResponse(s));if(req.method==='DELETE'){s.status='canceled';return send(res,200,checkoutResponse(s));}}
const complete=url.match(/^\/ucp\/v1\/checkout-sessions\/([^/]+)\/complete$/);if(req.method==='POST'&&complete){const s=sessions.get(decodeURIComponent(complete[1]));if(!s)return send(res,404,{ucp:{version:VERSION},messages:[{type:'error',code:'checkout_not_found',severity:'unrecoverable',content:'Checkout session not found.'}]});if(s.status!=='ready_for_complete')return send(res,409,{ucp:{version:VERSION},messages:[{type:'error',code:'requires_buyer_review',severity:'requires_buyer_input',content:'Checkout requires the merchant checkout UI.'}],continue_url:s.continue_url});s.status='requires_escalation';s.messages=[{type:'info',code:'merchant_checkout_required',severity:'requires_buyer_input',content:'Payment must be completed through the merchant checkout surface.'}];return send(res,200,checkoutResponse(s));}
return send(res,404,{ucp:{version:VERSION},messages:[{type:'error',code:'not_found',severity:'unrecoverable',content:'UCP endpoint not found.'}]});}
module.exports={handle,profile,VERSION};
