-- PHINHAVEN multiplayer MVP chat persistence
create table if not exists public.phinhaven_chat_messages (
  id bigint generated by default as identity primary key,
  player_id uuid not null references public.phinhaven_players(id) on delete cascade,
  player_name text not null,
  scene text not null check (scene in ('TOWN','DEPTH_2')),
  message text not null check (char_length(message) between 1 and 240),
  created_at timestamptz not null default now()
);
create index if not exists phinhaven_chat_messages_created_idx
  on public.phinhaven_chat_messages (created_at desc);
create index if not exists phinhaven_chat_messages_scene_created_idx
  on public.phinhaven_chat_messages (scene, created_at desc);
alter table public.phinhaven_chat_messages enable row level security;