const TOLERANCE=300;
const MARKETS:any={GLOBAL:1,NZ:1,AU:1,ZA:1,AMERICAS:1,EUROPE:1};
function json(data:any,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json'}})}
function hex(b:ArrayBuffer){return Array.from(new Uint8Array(b),x=>x.toString(16).padStart(2,'0')).join('')}
async function verify(payload:string,sig:string,secret:string){const parts=sig.split(',');const t=parts.find(x=>x.startsWith('t='));const vs=parts.filter(x=>x.startsWith('v1=')).map(x=>x.slice(3));if(!t||!vs.length)return false;const ts=Number(t.slice(2));if(!Number.isFinite(ts)||Math.abs(Math.floor(Date.now()/1000)-ts)>TOLERANCE)return false;const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const expected=hex(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(`${ts}.${payload}`)));return vs.some(v=>v.length===expected.length&&v.split('').every((c,i)=>c===expected[i]))}
export default async function handler(request:Request){
 if(request.method!=='POST')return new Response('Method not allowed',{status:405});
 const secret=process.env.STRIPE_WEBHOOK_SECRET;if(!secret)return json({error:'Webhook configuration missing'},503);const sig=request.headers.get('stripe-signature');if(!sig)return json({error:'Missing Stripe signature'},400);const body=await request.text();if(!(await verify(body,sig,secret)))return json({error:'Invalid Stripe signature'},400);
 let event:any;try{event=JSON.parse(body)}catch{return json({error:'Invalid JSON'},400)};if(event.type!=='checkout.session.completed')return json({received:true,ignored:true});const s=event.data?.object;if(!s||s.payment_status!=='paid'||s.metadata?.molt_beach!=='true')return json({received:true,ignored:true});
 const m=s.metadata,w=Number(m.width),h=Number(m.height),x=Number(m.x),y=Number(m.y),market=String(m.market||'GLOBAL').toUpperCase();if(!MARKETS[market])return json({error:'Invalid billboard market'},400);if(![100,200,500].includes(w)||![100,200,500].includes(h)||x<0||y<0||x+w>1000||y+h>1000)return json({error:'Invalid billboard geometry'},400);
 const base=process.env.SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!base||!key)return json({error:'Supabase configuration missing'},503);const id=`MB-${Date.now()}-${event.id.slice(-8)}`;const campaign={campaign_id:id,market,x,y,width:w,height:h,price_nzd:Number(m.price_nzd||0),owner_email:s.customer_details?.email||s.customer_email||null,image_url:String(m.image_url||'')||null,destination_url:String(m.destination_url||'')||null,content_hash:null,stripe_session_id:s.id,status:'PAID_PENDING_REVIEW',purchased_at:new Date().toISOString(),title:String(m.title||'')||null,owner_name:String(m.owner_name||'')||null};
 const r=await fetch(base.replace(/\/$/,'')+'/rest/v1/molt_beach_campaigns',{method:'POST',headers:{apikey:key,authorization:`Bearer ${key}`,'content-type':'application/json',prefer:'resolution=ignore-duplicates,return=minimal'},body:JSON.stringify(campaign)});if(!r.ok){const t=await r.text();console.error('MOLT_BEACH_WEBHOOK_WRITE_FAILED',t);return json({error:'Payment received but campaign persistence failed'},500)}console.log('MOLT_BEACH_PAYMENT',JSON.stringify(campaign));return json({received:true,campaign_id:id,market,status:'PAID_PENDING_REVIEW'});
}
